mmdet/models/bbox_heads/convfc_bbox_head.py
mmdet/models/utils/conv_module.py

Bug fix for ConvFCBBoxHead arguments

---

README.md
configs/cascade_mask_rcnn_r50_fpn_1x.py
configs/cascade_rcnn_r50_fpn_1x.py
configs/fast_mask_rcnn_r50_fpn_1x.py
configs/fast_rcnn_r50_fpn_1x.py
configs/faster_rcnn_r50_fpn_1x.py
configs/mask_rcnn_r50_fpn_1x.py
mmdet/core/post_processing/bbox_nms.py
mmdet/core/post_processing/merge_augs.py
mmdet/models/bbox_heads/bbox_head.py
mmdet/models/detectors/cascade_rcnn.py
mmdet/models/detectors/test_mixins.py
mmdet/models/rpn_heads/rpn_head.py
mmdet/ops/nms/cpu_soft_nms.pyx
mmdet/ops/nms/nms_wrapper.py

Note that the interface of `nms()` is changed. It will return a tuple of `(keep_bboxes, keep_inds)` instead of `keep_inds`.

Add support for soft-nms and potential new nms methods

---

.gitignore
mmdet/datasets/__init__.py
mmdet/datasets/concat_dataset.py
mmdet/datasets/utils.py
tools/train.py

support training on dataset with multiple ann_files

---

mmdet/models/detectors/base.py
mmdet/models/detectors/cascade_rcnn.py
mmdet/models/detectors/mask_rcnn.py

Allow mask visualization

---

README.md
mmdet/apis/train.py
mmdet/core/evaluation/__init__.py
mmdet/core/evaluation/class_names.py
mmdet/core/evaluation/eval_hooks.py
mmdet/datasets/__init__.py
mmdet/datasets/coco.py
mmdet/datasets/concat_dataset.py
mmdet/datasets/custom.py
mmdet/datasets/repeat_dataset.py
mmdet/datasets/voc.py
mmdet/datasets/xml_style.py
mmdet/models/detectors/base.py
tools/test.py

Example of training with VOC07+12 trainval:
```python
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(
mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
imgs_per_gpu=2,
workers_per_gpu=2,
train=dict(
type=dataset_type,
ann_file=[
data_root + 'VOC2007/ImageSets/Main/trainval.txt',
data_root + 'VOC2012/ImageSets/Main/trainval.txt'
],
img_prefix=[data_root + 'VOC2007/', data_root + 'VOC2012/'],
img_scale=(1000, 600),
img_norm_cfg=img_norm_cfg,
size_divisor=32,
flip_ratio=0.5,
with_mask=False,
with_crowd=True,
with_label=True),
val=dict(
type=dataset_type,
ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
img_prefix=data_root + 'VOC2007/',
img_scale=(1000, 600),
img_norm_cfg=img_norm_cfg,
size_divisor=32,
flip_ratio=0, …
```

Add VOC dataset

---

mmdet/models/anchor_heads/ssd_head.py

bug fix for argument name

---

mmdet/core/evaluation/mean_ap.py

hi, this pr would allow pass dataset.CLASSES as it is, like a list of label names

minor fix, print_map_summary

---

mmdet/datasets/coco.py

fix little potential  bug.......

fix a little bug in coco datasets loader

---

mmdet/core/anchor/anchor_target.py
mmdet/core/loss/losses.py

Bug fix for retinanet with 2 classes (fg/bg)

---

MODEL_ZOO.md

Correct mirror site links

---

mmdet/ops/__init__.py
mmdet/ops/dcn/__init__.py
mmdet/ops/dcn/modules/deform_conv.py
mmdet/ops/dcn/modules/deform_pool.py

1. add `num_offset_fcs` for `DeformRoIPoolingPack` and `num_mask_fcs` for `ModulatedDeformRoIPoolingPack`.
2. add `DeformConvPack` to integrate a 3x3 conv for offset prediction.

Add some arguments to DCN ops

---

mmdet/core/evaluation/eval_hooks.py

- add mAP_50/75/s/m/l and mAP_copypaste in the log
- use official barrier method
- print the progress bar only for rank 0

Update evaluation hooks

---

mmdet/apis/train.py

This is useful for custom datasets.
If users define a new dataset inherited from CocoDataset, it will use coco evaluation hooks instead of voc hooks during training.
```python
class SomeOtherDataset(CocoDataset):
CLASSES = ('a', 'b', 'c')
pass
```

Check dataset type by subclass instead of names

---

MODEL_ZOO.md

Update the comparison with other codebases in the model zoo

---

mmdet/models/backbones/resnet.py

the stride of conv2 in basic block should be 1

fix a bug in basicblock

---

mmdet/apis/inference.py

Fixed the bug that could not save the result picture when passing in `out_file` parameter. Relevant issues and pull requests are #613 and #403 .

fix bug of show_result

---

mmdet/apis/train.py

Support param-wise optimizer settings

---

tools/test.py

Bug fix for testing visualization

---

.gitignore

Ignore .log.json

---

TECHNICAL_DETAILS.md

Remove trailing space

---

tools/test.py
tools/train.py

Fix multiple checkpoint download bug.
Work together with https://github.com/open-mmlab/mmcv/pull/76

Set LOCAL_RANK in script

---

mmdet/models/losses/cross_entropy_loss.py

Fix the potential bug discussed in #845 .

fix potential bug in binary_cross_entropy

---

mmdet/models/backbones/resnet.py
mmdet/models/backbones/resnext.py

Bug fix for x101 gcnet

---

mmdet/ops/roi_align/functions/roi_align.py
mmdet/ops/roi_align/modules/roi_align.py
mmdet/ops/roi_pool/functions/roi_pool.py
mmdet/ops/roi_pool/modules/roi_pool.py

Support torchvision RoIPool and RoIAlign

---

.gitignore

It would be great to have pytorch checkpoints files added to .gitignore

pytorch checkpoint files added to gitignore

---

mmdet/datasets/custom.py
tools/test.py

1.Warning when skip image
2.added parameter skip_img_without_anno for dataset. It is useful , if we want to use images that has no annotation to train as negative sample.
3.Fix format

Warning when skip image

---

mmdet/datasets/transforms.py

Bug fix for mask resizing when aspect ratio is unfixed

---

mmdet/core/bbox/__init__.py

Bug fix for recursive imports

---

mmdet/datasets/transforms.py

Added vertical bounding box flipping for the `bbox_flip` function in `mmdet/datasets/transforms.py`. I needed this for implementing shearX/Y functionality. Hope it helps!

Added vertical flipping in bbox_flip

---

mmdet/ops/masked_conv/src/masked_conv2d_kernel.cu
mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu

Use int64_t instead of long in cuda kernels

---

mmdet/core/mask/mask_target.py
mmdet/models/bbox_heads/bbox_head.py
mmdet/models/bbox_heads/convfc_bbox_head.py
mmdet/models/bbox_heads/double_bbox_head.py
mmdet/models/mask_heads/fcn_mask_head.py
mmdet/models/mask_heads/grid_head.py
mmdet/models/mask_heads/maskiou_head.py
mmdet/models/roi_extractors/single_level.py
mmdet/ops/roi_align/roi_align.py
mmdet/ops/roi_pool/roi_pool.py

Support unsquare RoIs for bbox and mask heads

---

mmdet/models/anchor_heads/fcos_head.py

Fix bug of FCOS when image has no positive sample

---

tools/webcam_demo.py

Press "Esc", "q" or "Q" to exit from demo.

Press key to exit

---

mmdet/models/roi_extractors/single_level.py

Fix inplace add in roi extractor

---

docs/INSTALL.md

new setup.py requires g++ support.

add g++ requirement for INSTALL.md.

---

setup.py

Hello!
Here a simple way to preventing from having the requirements.txt not in sync with the list hardcoded in the setup.py.
It may prevent future bugs,
Thanks

Minor: requirements to list in setup to avoid repetitions

---

docs/GETTING_STARTED.md
docs/TECHNICAL_DETAILS.md

Two misspelled words in the docs.

Minor spelling fixes.

---

configs/albu_example/mask_rcnn_r50_fpn_1x.py
mmdet/datasets/pipelines/__init__.py
mmdet/datasets/pipelines/transforms.py
requirements.txt

Supporting aux augmentations from Albumentations (https://albumentations.readthedocs.io)
+  `Albu` transformation module as a wrapper
+  Example of usage based on MaskRCNN config file

Albumentations augs wrapper

---

mmdet/apis/train.py
mmdet/core/bbox/samplers/ohem_sampler.py
mmdet/models/anchor_heads/fcos_head.py
mmdet/models/anchor_heads/retina_head.py
mmdet/models/utils/scale.py

I was debugging issues I was having with RetinaNet and these docstrings / doctests were created in the process.

Add docs FCOS/Retina, OHEM, Scale, make_optimizer

---

mmdet/models/anchor_heads/ssd_head.py
mmdet/models/losses/ghm_loss.py

Fix SSD Head and GHM Loss on CPU

---

mmdet/datasets/pipelines/transforms.py

Allows to use not only 0.5 probability.

generalization of Expand transfrom probability

---

mmdet/apis/train.py

see https://github.com/open-mmlab/mmdetection/issues/1594

prevent silent skip of validation #1594

---

docs/GETTING_STARTED.md

Add documentation for evaluating class-wise mAP.

add class-wise doc

---

mmdet/core/mask/mask_target.py

Clip proposal boxes to valid range in single_mask_target

---

docs/INSTALL.md

Related to https://github.com/open-mmlab/mmcv/pull/146.

Update installation guide

---

tools/train.py

Put the config and version information into the log.

print log & version in train.py

---

mmdet/core/anchor/anchor_generator.py
mmdet/core/anchor/anchor_target.py
mmdet/core/anchor/guided_anchor_target.py
mmdet/datasets/pipelines/transforms.py
mmdet/models/anchor_heads/anchor_head.py
mmdet/models/anchor_heads/guided_anchor_head.py
mmdet/models/detectors/mask_scoring_rcnn.py
mmdet/models/mask_heads/maskiou_head.py
mmdet/models/plugins/generalized_attention.py
tests/test_forward.py

Just now, the yapf is updated to 0.29, this PR reformat the code for the yapf 0.29.

reformat for yapf0.29

---

mmdet/core/bbox/samplers/iou_balanced_neg_sampler.py

Fix one bug in IoU balanced sampling.

Fix IoU sampling

---

mmdet/datasets/loader/sampler.py

Fix the compatibility to mmcv v0.2.15

Fix imports of get_dist_info

---

configs/wider_face/ssd300_wider_face.py

Resolves #1740
Learning rate is changes according to @sunke123's experiments.

Adopt WIDER-SSD300 config to run on 8 GPUs

---

mmdet/core/bbox/samplers/iou_balanced_neg_sampler.py

Update floor_thr in iou sampling

---

mmdet/core/anchor/guided_anchor_target.py

Fix the return value of `ga_shape_target_single`

---

mmdet/apis/train.py
mmdet/models/backbones/hrnet.py
mmdet/models/backbones/resnet.py
mmdet/models/backbones/ssd_vgg.py
mmdet/models/detectors/base.py
mmdet/models/shared_heads/res_layer.py
tools/train.py

The first several logs (config, version, etc.) were not written to the log file. This PR fixes the issue.

Init logger before constructing Runner

---

mmdet/apis/inference.py

Small change to have consistent colors for all of the objects in the class.
I needed this to create a video for YT.

Per class colors in Mask results viz

---

mmdet/utils/contextmanagers.py

This PR fixes debug logging for `completed` contextmanager.

fix debug completed logging

---

mmdet/datasets/builder.py

in /mmdet/datasets/builder.py
`---  seg_prefixes = cfg.get('seg_prefixes', None)`
`+++ seg_prefixes = cfg.get('seg_prefix', None)`

solve the bug when seg_prefix is list

---

mmdet/models/anchor_heads/ssd_head.py

add nan checking in ssd head

---

mmdet/datasets/pipelines/transforms.py

Fix fovea no ann training error when using albu transform.

---

mmdet/datasets/pipelines/transforms.py

Convert masks to ndarray in transforms

---

setup.py

`1.0+<hash>` -> `1.0.0+<hash>`

Correct the version number

---

mmdet/datasets/coco.py

This PR fixed temporary directory clean up in COCO.

fixed tmp dir in coco

---

mmdet/ops/nms/nms_wrapper.py

Replace `new_tensor` with `to` in order to remove warning.

remove new_tensor

---

mmdet/datasets/pipelines/transforms.py

fix pad_val not used in class Pad when pad to a fixed size

---

docker/Dockerfile

set FORCE_CUDA

---

mmdet/ops/masked_conv/src/masked_conv2d_cuda.cpp
mmdet/ops/nms/src/nms_cuda.cpp
mmdet/ops/roi_align/src/roi_align_cuda.cpp
mmdet/ops/roi_pool/src/roi_pool_cuda.cpp
mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss.cpp

Fix device bug

---

requirements/tests.txt

fix ubelt == 0.8.8 since 0.8.9 is broken.

fixed test package

---

mmdet/apis/train.py

PR from this issue
https://github.com/open-mmlab/mmdetection/issues/2063

no weight decay in depthwise convolution

---

mmdet/core/fp16/hooks.py

PR from this issue
https://github.com/open-mmlab/mmdetection/issues/2131

fp16_speedup

---

mmdet/datasets/loader/build_loader.py

Fix worker_init_fn

---

mmdet/apis/__init__.py
mmdet/apis/test.py
mmdet/apis/train.py
mmdet/core/evaluation/eval_hooks.py
tools/test.py

This PR finally unified the api of testing script and eval hooks. The evaluation process will receive a speedup.

Use dataloader for eval hooks

---

mmdet/models/bbox_heads/bbox_head.py
mmdet/models/detectors/cascade_rcnn.py

This PR fixed some missing part of https://github.com/open-mmlab/mmdetection/pull/2105

fixed uint8 warning

---

mmdet/ops/roi_align/src/roi_align_kernel_v2.cu

This PR fixes the issue mentioned in #2262.

Fix type errors in roi_align_v2

---

mmdet/models/anchor_heads/atss_head.py

Fix atss uint8

---

mmdet/datasets/pipelines/transforms.py

Fix idx_mapper index calculation error of class label

---

mmdet/models/bbox_heads/bbox_head.py
mmdet/models/bbox_heads/convfc_bbox_head.py
mmdet/models/bbox_heads/double_bbox_head.py

Fix issue https://github.com/open-mmlab/mmdetection/issues/218.

Add comments about conv initialization in bbox heads

---

.isort.cfg
configs/mask_rcnn_r50_fpn_1x.py
docs/GETTING_STARTED.md
mmdet/models/detectors/cascade_rcnn.py
mmdet/models/detectors/double_head_rcnn.py
mmdet/models/detectors/grid_rcnn.py
mmdet/models/detectors/htc.py
mmdet/models/detectors/two_stage.py
tools/pytorch2onnx.py

This PR is based on https://github.com/open-mmlab/mmdetection/pull/1082. 
The experimental ONNX conversion is added. The customized operators are not supported for now.

Add onnx convert script

---

tools/test.py

This change adds ability to pass list options to test.py script and slightly cleans up the
original code
On branch list_to_kvaction
modified:   tools/test.py

Add ability to pass list options to test.py script

---

mmdet/ops/carafe/grad_check.py

Fix a typo in grad_check of CARAFE

---

docs/GETTING_STARTED.md
mmdet/datasets/cityscapes.py

This PR fixed doc about Cityscapes.

fixed cityscapes doc

---

configs/_base_/models/cascade_mask_rcnn_r50_fpn.py
configs/_base_/models/cascade_rcnn_r50_fpn.py
configs/_base_/models/fast_rcnn_r50_fpn.py
configs/_base_/models/faster_rcnn_r50_fpn.py
configs/_base_/models/mask_rcnn_r50_fpn.py
configs/_base_/models/retinanet_r50_fpn.py
configs/_base_/models/rpn_r50_fpn.py
configs/atss/atss_r50_fpn.py
configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py
configs/fcos/fcos_x101_64x4d_fpn_gn-head_mstrain_640-800_4x2_2x_coco.py
configs/foveabox/fovea_r50_fpn_4x4_1x_coco.py
configs/grid_rcnn/grid_rcnn_r50_fpn_gn-head_2x_coco.py
configs/htc/htc_without_semantic_r50_fpn_1x_coco.py
configs/htc/htc_x101_32x4d_fpn_16x1_20e_coco.py
configs/htc/htc_x101_64x4d_fpn_16x1_20e_coco.py
configs/htc/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco.py
configs/reppoints/reppoints_moment_r50_fpn_1x_coco.py
requirements/runtime.txt

This PR add `norm_eval= True` in all configs files.

Add norm eval in configs

---

mmdet/models/detectors/cascade_rcnn.py
mmdet/models/detectors/test_mixins.py

Fix augtest error

---

configs/empirical_attention/faster_rcnn_r50_fpn_attention_0010_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_0010_dcn_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_dcn_1x_coco.py
configs/gcnet/mask_rcnn_r50_fpn_r16_gcb_c3-c5_1x_coco.py
configs/gcnet/mask_rcnn_r50_fpn_r4_gcb_c3-c5_1x_coco.py
configs/gcnet/mask_rcnn_r50_fpn_syncbn-backbone_r16_gcb_c3-c5_1x_coco.py
configs/gcnet/mask_rcnn_r50_fpn_syncbn-backbone_r4_gcb_c3-c5_1x_coco.py
mmdet/models/backbones/resnet.py
mmdet/models/utils/res_layer.py
mmdet/ops/__init__.py
mmdet/ops/context_block.py
mmdet/ops/generalized_attention.py
mmdet/ops/plugin.py
tests/test_backbone.py

This PR refactored GCNet and empirical attention into plugin.

Refactor gcnet/emperical into plugin

---

mmdet/core/post_processing/bbox_nms.py
mmdet/models/anchor_heads/rpn_head.py
mmdet/ops/__init__.py
mmdet/ops/nms/__init__.py
mmdet/ops/nms/nms_wrapper.py
mmdet/ops/nms/src/cuda/nms_kernel.cu

Speed up RPN head.
| Model             | Original Inf time (s/iter) | New Inf time (s/iter) |
|-------------------|----------------------------|-----------------------|
| Faster R-CNN R-50 | 16.0                       | 18.0                  |
| Mask R-CNN R-50   | 10.9                       | 11.9                  |
| Retinanet R-50    | 16                         |   16.1                    |

V2.0 speedup rpn

---

tools/analyze_logs.py
tools/coco_error_analysis.py
tools/publish_model.py
tools/slurm_test.sh
tools/slurm_train.sh
tools/upgrade_model_version.py

This PR fixes the bug introduced in https://github.com/open-mmlab/mmdetection/pull/2433, which also replaces '_' by '-' in the necessary arguments.

V2.0 command fix

---

mmdet/core/anchor/__init__.py
mmdet/core/anchor/utils.py
mmdet/core/utils/__init__.py
mmdet/core/utils/misc.py

`unmap` function is duplicate in `mmdet/core/utils/misc.py` and `mmdet/core/anchor/utils.py`. 
This PR removed the one in `mmdet/core/anchor/utils.py`.

Remove duplicate unmap function

---

mmdet/core/post_processing/bbox_nms.py

This PR fixes the bug mentioned in #2475.

Check if max_num > 0 before slicing in nms

---

mmdet/datasets/pipelines/transforms.py

add reminder for PhotoMetricDistortion

---

mmdet/models/anchor_heads/guided_anchor_head.py
tests/test_heads.py

This PR fixed typo in `GuidedAnchorHead()` and added unit tests.

Guided anchor fix

---

docs/COMPATIBILITY.md

This PR adds documentation for V2.0. 
The newly added document mainly discusses the compatibility between the codebases of V2.0 and the V1.x version for reference.

Add documentation

---

mmdet/datasets/coco.py
mmdet/models/anchor_heads/ga_rpn_head.py
tests/test_pipelines/test_loading.py

Fix the bugs caused by the `f-string` PR and  that in ga_rpn_head caused by anchor head refactoring.

Fix f-string bugs and ga_rpn_head bug

---

mmdet/core/mask/structures.py

This PR fixes several bugs in mask structure.
After fixing the bug that quantizes the box, the Mask RCNN r50 model achieves higher mask AP (0.2% absolute).

Fix bugs in mask structure

---

.isort.cfg
mmdet/apis/train.py
mmdet/datasets/xml_style.py
mmdet/ops/dcn/deform_conv.py

This PR merges the newest master

Merge master to v2.0

---

docs/tutorials/new_dataset.md

This PR enriches the dataset tutorial of v2.0.

Enrich V2.0 dataset tutorial

---

configs/foveabox/fovea_align_r50_fpn_gn-head_4x4_2x_coco.py
configs/free_anchor/retinanet_free_anchor_r50_fpn_1x_coco.py
configs/ghm/retinanet_ghm_r50_fpn_1x_coco.py

This PR adds gradient clip to some models to avoid the loss going to Nan.

Add gradient clip back in cfgs

---

configs/cityscapes/faster_rcnn_r50_fpn_1x_cityscapes.py
configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_0010_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_0010_dcn_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_1x_coco.py
configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_dcn_1x_coco.py

This PR fixed the following configs. 
1. cityscapes `load_from` link.

Fix config files

---

docs/getting_started.md
mmdet/apis/test.py
tools/test.py

Add score threshold parameter in order to filter out all the detections below this threshold.

Add score threshold

---

README.md
docs/changelog.md
docs/getting_started.md
docs/install.md
tools/dist_test.sh
tools/dist_train.sh
tools/slurm_test.sh
tools/slurm_train.sh

Add python path in scripts

---

README.md
docs/model_zoo.md

1. Fixed a small bug that model_zoo url is inaccessible
2. Added FSAF model zoo

Fix a small bug that model_zoo url is inaccessible

---

docs/tutorials/finetune.md

spelling miss

---

mmdet/core/evaluation/mean_ap.py

Closes multiprocessing pool.
Potentially resolves #2670.

Close multiprocessing Pool

---

mmdet/datasets/wider_face.py

mistake occur in f-string in reading widerface.
mmdet/datasets/wider_face.py 
see in detail.

fix bug. use f-string format

---

docs/getting_started.md

- CAMERA-ID was mentioned for image_demo.py

Command usage of Image and Webcam demo were wrong.

---

docs/install.md

addresses common gotcha found in  #2627

adds note to remove build folder when rebuilding

---

README.md
docs/getting_started.md
mmdet/core/fp16/decorators.py

This PR adds some direction links in README.md and getting_started.md

Add links in docs

---

README.md
docs/getting_started.md
docs/projects.md

Add a page in the doc that links to other related projects.

Extension link

---

mmdet/models/detectors/base.py

Fix mask show

---

mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp

Fixed #2661 base on [this comment](https://github.com/open-mmlab/mmdetection/issues/2661#issuecomment-630436030)

Fix DCN contiguous

---

docs/tutorials/new_dataset.md
mmdet/datasets/__init__.py
mmdet/datasets/builder.py
mmdet/datasets/coco.py
mmdet/datasets/custom.py
mmdet/datasets/dataset_wrappers.py
mmdet/datasets/xml_style.py
tests/test_dataset.py

This PR added `RepeatFactorDataset` for all datasets.

add ClassBalancedDataset

---

configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person.py

('person') will be parsed as string.
It should be a tuple

fix bug for coco person subset

---

docs/install.md
requirements/build.txt

Fix gcc requirement

---

tests/test_async.py
tests/test_heads.py

fix async test

---

mmdet/apis/test.py
mmdet/core/mask/__init__.py
mmdet/core/mask/utils.py
mmdet/models/detectors/base.py
mmdet/models/detectors/cascade_rcnn.py
tools/test_robustness.py

Fix show bug

---

configs/cascade_rcnn/README.md
configs/instaboost/README.md

Fix some tweaks in configs readme.

Fix configs

---

mmdet/apis/test.py

Possible deadlock prevention

---

mmdet/ops/nms/src/cpu/nms_cpu.cpp

data/data_ptr conversions, int/size_t warning

fixed nms build warning

---

mmdet/core/bbox/transforms.py
mmdet/models/detectors/base.py

Fix https://github.com/open-mmlab/mmdetection/issues/2850
Fix https://github.com/open-mmlab/mmdetection/issues/2804
Fix https://github.com/open-mmlab/mmdetection/issues/2421

Fix bug in test time aug

---

README.md
docs/projects.md

This PR update project links and add link of tutorials in the README.md

Update project links

---

mmdet/core/bbox/transforms.py
mmdet/core/post_processing/merge_augs.py
mmdet/datasets/pipelines/__init__.py
mmdet/datasets/pipelines/formating.py
mmdet/datasets/pipelines/test_aug.py
mmdet/datasets/pipelines/test_time_aug.py
mmdet/models/detectors/reppoints_detector.py
mmdet/models/detectors/rpn.py
mmdet/models/roi_heads/cascade_roi_head.py
mmdet/models/roi_heads/htc_roi_head.py
mmdet/models/roi_heads/test_mixins.py

fixed vertical flip TTA

---

mmdet/models/backbones/hrnet.py
mmdet/models/backbones/regnet.py
mmdet/models/backbones/res2net.py
mmdet/models/backbones/resnet.py
mmdet/models/backbones/resnext.py

This PR mainly changes Normally to Default in the docstring of backbones

change Normally to Default in the docstring of backbones

---

.isort.cfg
mmdet/models/roi_heads/cascade_roi_head.py
mmdet/models/roi_heads/htc_roi_head.py

Fix https://github.com/open-mmlab/mmdetection/issues/2930

Fix bugs in TTA of cascade rcnn & htc

---

.gitignore
README.md
configs/grid_rcnn/grid_rcnn_r50_fpn_gn-head_1x_coco.py
configs/groie/README.md
configs/groie/faster_rcnn_r50_fpn_groie_1x_coco.py
configs/groie/grid_rcnn_r50_fpn_gn-head_groie_1x_coco.py
configs/groie/mask_rcnn_r101_fpn_syncbn-backbone_r4_gcb_c3-c5_groie_1x_coco.py
configs/groie/mask_rcnn_r50_fpn_groie_1x_coco.py
configs/groie/mask_rcnn_r50_fpn_syncbn-backbone_r4_gcb_c3-c5_groie_1x_coco.py
docs/model_zoo.md
mmdet/models/roi_heads/roi_extractors/__init__.py
mmdet/models/roi_heads/roi_extractors/groie.py
mmdet/ops/plugin.py
tests/test_roi_extractor.py

Signed-off-by: Leonardo Rossi <leonardo.rossi@studenti.unipr.it>

roi_extractors: GRoIE addition

---

mmdet/core/bbox/iou_calculators/iou2d_calculator.py
mmdet/core/evaluation/bbox_overlaps.py

In new coord system, box area can be 0.

avoid nan in iou_calculator

---

mmdet/models/backbones/resnet.py
tests/test_backbone.py

add with_cp for basicblock of resnet

---

docs/projects.md

More paper of CVPR2020 added. 21 projects now.

Update project link

---

mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu

Add fl num class check

---

mmdet/ops/dcn/deform_conv.py

Modify mdconv doc

---

docker/Dockerfile

fixed docker pycocotools

---

.travis.yml
mmdet/apis/train.py
mmdet/models/detectors/base.py
requirements/runtime.txt
tests/test_forward.py

Used along with the latest MMCV.

Switch to EpochBasedRunner

---

mmdet/datasets/custom.py
mmdet/models/detectors/base.py

This PR changes the `len(data['img'].data)` to `len(data['img_metas']` in `train_step` and `test_step` for more general usage.

Use len(data['img_metas']) to indicate num_samples

---

mmdet/datasets/cityscapes.py

Fixed #3099 
Fixed #2396 
Fixed #2971 
Fixed #2974

Fixed cityscapes eval with ms_rcnn

---

.dev_scripts/benchmark_filter.py
configs/wider_face/ssd300_wider_face.py

Fix https://github.com/open-mmlab/mmdetection/issues/3123

Fix num_classes in SSD

---

configs/nas_fcos/nas_fcos_fcoshead_r50_caffe_fpn_gn-head_4x4_1x_coco.py
configs/nas_fcos/nas_fcos_nashead_r50_caffe_fpn_gn-head_4x4_1x_coco.py

This PR fixes the legacy bug in the pre-trained models of NASFCOS configs.

fix pretrain bug in nas fcos

---

mmdet/models/roi_heads/dynamic_roi_head.py

Fixed dynamic rcnn eval

---

.github/workflows/build.yml
mmdet/datasets/pipelines/formating.py
mmdet/datasets/pipelines/loading.py
mmdet/datasets/pipelines/transforms.py
tests/test_pipelines/test_formatting.py
tests/test_pipelines/test_loading.py
tests/test_pipelines/test_models_aug_test.py
tests/test_pipelines/test_transform.py

Multi scale test

---

.isort.cfg
mmdet/core/mask/structures.py
mmdet/datasets/pipelines/transforms.py

This PR fixes the bug caused by the API change of `mmcv.impad`.

Update for mmcv.impad API changes

---

docs/install.md
requirements/build.txt

add `conda install Cython` before installing the forked version of `pycocotools`

doc: Update install.md

---

docs/getting_started.md

This PR fixes some tweaks in the docs.

Fix bug of ordered list in getting_started

---

docs/getting_started.md

Hello,
I add GUI link in getting_started.md

add GUI link in getting_started.md

---

mmdet/models/backbones/res2net.py

Fix https://github.com/open-mmlab/mmdetection/issues/3129 based on [this comment](https://github.com/open-mmlab/mmdetection/issues/3129#issuecomment-659140745)

Fix Res2Net+DCN RuntimeError

---

mmdet/models/dense_heads/atss_head.py

fix atss when sampler per gpu is 1

---

mmdet/apis/inference.py
mmdet/datasets/pipelines/__init__.py
mmdet/datasets/pipelines/loading.py
tests/test_data/test_loading.py

This PR added `LoadImageFromWebcam` loading pipeline for webcam demo. 
Fixed #3623
Fixed #3631

[Bug] Fixed webcam demo

---

tools/eval_metric.py

Add eval metric

---

docs/tutorials/new_modules.md

- Fix itemize issues
- Fix some typos.

Fix tutorial

---

mmdet/__init__.py
mmdet/core/bbox/transforms.py
mmdet/core/mask/structures.py
mmdet/datasets/pipelines/transforms.py
tests/test_data/test_transform.py
tests/test_masks.py

[Feature] Support RandomFlip with horizontal/vertical/diagonal 

---

mmdet/datasets/pipelines/__init__.py
mmdet/models/roi_heads/__init__.py

This PR supplements some classes in the init lists.

Update init lists

---

mmdet/datasets/coco.py

This PR makes the CocoDataset training without 'segmentation' annotations.

Support non-mask training for CocoDataset

---

mmdet/apis/test.py

Fix show during test

---

tools/browse_dataset.py

Dataset label ids start with 0

fix browser dataset labels

---

docs/getting_started.md

This commits adds installation section to getting_started.md.
The contents are refactored from install.md and some ordered lists are fixed.

[Doc] Add installation

---

mmdet/models/roi_heads/cascade_roi_head.py

fix sabl validating bug in cascade_rcnn

---

docs/tutorials/1_exist_data_model.md

Rearrange from get_started.md
Add more instruction words
Update old link / model names

[doc] tutorial for existing dataset and model 

---

configs/vfnet/vfnet_r50_fpn_1x_coco.py
configs/vfnet/vfnet_r50_fpn_mstrain_2x_coco.py
mmdet/models/dense_heads/vfnet_head.py

Hi @hellock, I just found some small issues and have got them fixed.

VFNet: fix multiscale_mode issue and update with the latest change of mmdetection

---

mmdet/core/anchor/anchor_generator.py

Fix bug in https://github.com/open-mmlab/mmdetection/issues/4042#issue-733933244 .

Add f-string

---

mmdet/core/utils/__init__.py
mmdet/core/utils/dist_utils.py
mmdet/models/dense_heads/atss_head.py
mmdet/models/dense_heads/gfl_head.py
mmdet/models/dense_heads/vfnet_head.py

Clean duplicated `reduce_mean`  function in dense heads.
Resolves #4046

[Refactor]: clean duplicated reduce_mean function

---

docs/projects.md

aLRP-Loss, accepted in NeurIPS2020, added to projects.md

add aLRP-Loss

---

configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person-bicycle-car.py
configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person.py

`num_classes` in model should be the same as the number of dataset class

[fix-bug-pr] fix bug for faster rcnn config

---

docs/faq.md

Resolves #4131 , resolves #4047 , resolves #4160

[DOC] Edit FAQ to add 30 series installation problem

---

configs/detr/detr_r50_8x4_150e_coco.py
mmdet/models/dense_heads/transformer_head.py

This PR supports DETR epoch150 config, and reformat some codes.

Supports DETR e150 config

---

mmdet/models/dense_heads/vfnet_head.py

Resolves https://github.com/open-mmlab/mmdetection/issues/4172, continues on #4173

Ensure dcn offset have similar type as feats

---

configs/detr/README.md
mmdet/models/dense_heads/gfl_head.py

Resolves https://github.com/open-mmlab/mmdetection/issues/4227

Add detr performans and model link

---

mmdet/models/necks/fpn.py

FPN deprecated warning

---

mmdet/models/dense_heads/transformer_head.py
mmdet/models/detectors/base.py
tests/test_models/test_heads.py

fix typo in batch_input_shape for detr

---

mmdet/datasets/pipelines/formating.py

This PR fix #4242 , fix docstring in class 'WrapFieldsToLists'.

Fix docstring in WrapFieldsToLists

---

.github/workflows/build.yml

This is just a temporary fix. Will refactor CI later.

Fixed CI temporarily

---

.dev_scripts/gather_models.py

This PR supports to get the last epoch info from reading the config in gather_model.py

Get the last epoch info from reading config in gather_model

---

docs/tutorials/config.md
tools/eval_metric.py
tools/test.py
tools/train.py

Related MMCV PR: https://github.com/open-mmlab/mmcv/pull/732

Add config options docstring

---

docs/stat.py

modify the counting way of ckpts

modify the counting way of ckpts

---

docs/stat.py

remove the papers should not be included and the models without any checkpoint

modify counting way of papers

---

docs/get_started.md

Add cpu compatibility info
Resolves #4311 
Resolves #4313

Add cpu compatibility info

---

mmdet/models/dense_heads/cascade_rpn_head.py

Fix cpu device inference error

Fix cpu device inference error

---

mmdet/models/dense_heads/corner_head.py

Fix the nms error when there is no prediction box

Fix the nms error when there is no prediction box

---

docs/1_exist_data_model.md

Add batch inference docs about deprecate ImageToTensor

Add batch inference docs about deprecate ImageToTensor

---

mmdet/core/visualization/image.py

Fix window data won't destroy error when out_file is not None and show is False

Fix window data won't destroy error

---

configs/fp16/README.md
docs/stat.py

update stat and modify the tag of fp16

update stat to classify papers

---

mmdet/core/utils/__init__.py
mmdet/core/utils/misc.py
mmdet/core/visualization/__init__.py
mmdet/core/visualization/image.py
mmdet/datasets/__init__.py
mmdet/datasets/utils.py
tests/test_misc.py
tests/test_visualization.py
tools/analyze_results.py
tools/browse_dataset.py

New add results quality evaluation

[Feature] Support to visualize results based on prediction quality

---

configs/albu_example/README.md
configs/cityscapes/README.md
configs/dcn/README.md
configs/deepfashion/README.md
configs/hrnet/README.md
configs/pascal_voc/README.md
configs/res2net/README.md
configs/scratch/README.md
configs/wider_face/README.md

Fix config tag

---

docs/1_exist_data_model.md

Fix Missing documentation

---

mmdet/datasets/custom.py

pls use `iou_thrs` instead of `iou_thr`
#4580

fix RPN evaluation `iou_thrs` bug

---

configs/detectors/README.md
configs/htc/README.md
configs/scnet/README.md
docs/1_exist_data_model.md

Update HTC/DetectoRS/SCNet Dataset docs

Update HTC/DetectoRS/SCNet Dataset docs

---

docs/2_new_data_model.md

spelling correction, 'ballon' -> 'balloon'

spelling correction in `2_new_data_model.md`

---

docs/useful_tools.md

Add result_analysis docs

---

mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py

[Enhance]: Add roi_extractor comment

---

mmdet/core/bbox/coder/delta_xywh_bbox_coder.py
mmdet/core/bbox/coder/tblr_bbox_coder.py
mmdet/models/detectors/single_stage.py
tests/test_utils/test_coder.py

[Refactor]: bbox coder support batch infer

---

mmdet/models/roi_heads/roi_extractors/base_roi_extractor.py
mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py

#4753
Docstring data type correction

Correct docstring data type

---

configs/tridentnet/tridentnet_r50_caffe_1x_coco.py
mmdet/models/roi_heads/trident_roi_head.py

In the previous version, it will raise a bug when the batch size in inference is greater than 1.

Fix TridentNet batch inference bug

---

mmdet/models/dense_heads/yolact_head.py

similar warning: https://github.com/open-mmlab/mmdetection/pull/2602

fix torch.nonzero warning

---

mmdet/datasets/coco.py
tests/test_data/test_datasets/test_coco_dataset.py

[Feature]: Add check for ann_ids not unique

---

mmdet/models/roi_heads/bbox_heads/bbox_head.py
mmdet/models/roi_heads/test_mixins.py
tests/test_models/test_roi_heads/test_bbox_head.py

[Feature]: Support Batch for Faster R-CNN

[Feature]: Support Batch for Faster R-CNN

---

mmdet/apis/inference.py

Deprecate LoadImage

---

tools/analysis_tools/coco_error_analysis.py

improve coco_error_analysis.py

---

docs/1_exist_data_model.md

Support no gt test mode

---

docs/tutorials/onnx2tensorrt.md
docs/tutorials/pytorch2onnx.md

This PR focus on add new content related to batches infer and dynamic shapes in pytorch2onnx.md and onnx2tensorrt.md.

[Doc]: update doc for pytorch2onnx and onnx2tensorrt

---

.dev_scripts/batch_test.py
tools/analysis_tools/test_robustness.py

- check for CLASSES in checkpoint meta when key meta does not exists

[Fix] check for CLASSES in checkpoint meta

---

mmdet/core/bbox/assigners/region_assigner.py

fix cacscade_rpn no gt

---

docs/tutorials/onnx2tensorrt.md
docs/tutorials/pytorch2onnx.md
tools/deployment/pytorch2onnx.py

This PR update pytorch2onnx.py to test dynamic shape and multi-batch for ONNXRuntime backend.
Dynamic shape and multi-batch tests of the below models show correct visualized results
|    Model    |                          Config                          | Dynamic Shape | Batch Inference | Note  |
| :---------: | :------------------------------------------------------: | :-----------: | :-------------: | :---: |
|    FCOS     | `configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py` |       Y       |        Y        |       |
|     SSD     |               `configs/ssd/ssd300_coco.py`               |       Y       |        Y        |       |
|   YOLOv3    |    `configs/yolo/yolov3_d53_mstrain-608_273e_coco.py`    |       Y       |        Y        |       |
|    FSAF     | …

[Enhancement]: update pytorch2onnx to test dynamic shape and multi-batch inference

---

docs/robustness_benchmarking.md
docs/useful_tools.md

add test_robustness description

---

demo/image_demo.py
mmdet/apis/inference.py
mmdet/models/roi_heads/base_roi_head.py

Fix async error and privide aysnc demo

---

mmdet/datasets/api_wrappers/coco_api.py
mmdet/datasets/lvis.py

[Bug Fix] Fix pycocotools warning

---

requirements/runtime.txt

fixes https://github.com/open-mmlab/mmdetection/issues/4970

add windows support by updating requirements.txt

---

mmdet/models/dense_heads/ssd_head.py

fixed torch.nonzero warning

---

mmdet/apis/inference.py
mmdet/core/anchor/anchor_generator.py
mmdet/core/anchor/point_generator.py
mmdet/core/bbox/iou_calculators/iou2d_calculator.py
mmdet/core/bbox/match_costs/match_cost.py
mmdet/datasets/dataset_wrappers.py
mmdet/datasets/pipelines/auto_augment.py
mmdet/datasets/pipelines/compose.py
mmdet/datasets/pipelines/formating.py
mmdet/datasets/pipelines/instaboost.py
mmdet/datasets/pipelines/loading.py
mmdet/datasets/pipelines/test_time_aug.py
mmdet/datasets/pipelines/transforms.py
mmdet/models/dense_heads/dense_test_mixins.py
mmdet/models/dense_heads/rpn_test_mixin.py
mmdet/models/roi_heads/test_mixins.py
mmdet/utils/util_mixins.py
tests/test_data/test_pipelines/test_loading.py
tests/test_models/test_dense_heads/test_paa_head.py
tests/test_runtime/test_fp16.py
tools/analysis_tools/analyze_results.py

Remove unnecessary (object) in class definition

---

README.md
configs/seesaw_loss/README.md

Fix doc link
fix doc link in README.md and configs/seesaw_loss/README.md.

fix doc link

---

.dev_scripts/convert_test_benchmark_script.py
.dev_scripts/gather_models.py

fix total_epochs error 
replace `total_epochs` to `.runner.max_epochs`

fix total_epochs error

---

.dev_scripts/benchmark_test_image.py

Quickly detect whether the inference code is correct.

[Feature] add benchmark_test_image.py

---

docs/projects.md

Updated title of Generalizable Pedestrian Detection: The Elephant In The Room --> Generalizable Pedestrian Detection: The Elephant In The Room.
Conference venue to CVPR2021.
Update request in the file [projects using mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/docs/projects.md).

Updated title and venue for Pedestrian Detection: The Elephant In The Room

---

docs/tutorials/finetune.md

Delete the wrong comment. #5270

[Docs] Delete bug comment

---

docs/get_started.md

Add install guide using MIM to getting_start document.

[Doc] Add install guide with MIM

---

.dev_scripts/gather_models.py
setup.cfg

Add stript to generate PWC metafile when gather models.
Run `.dev_scripts/gather_models.py` and it will generate a metafile.yml.
You need to fill in the download link in ` Weights:` after uploading the model to the cloud.
Also,  the `Collections` in metafile should be written manually.
And finally, do not forget to write the metafile path into model_zoo.yml.

[Feature] Add dev_script to generate metafile.

---

docs/faq.md
docs/model_zoo.md
docs/tutorials/config.md
docs/tutorials/onnx2tensorrt.md
docs/useful_tools.md

Please refer to #5185.
I modified some links and one typo.
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If this PR introduces a new feature, it is better to list some use cases …

[Fix] Fix web links in docs ending with `.md`

---

.dev_scripts/gather_models.py

Add config path when generating PWC metafile and fix a mistake.

[Fix]Config path in metafile script

---

configs/seesaw_loss/README.md

Update the bibtex of Seesaw Loss

Seesaw Loss - update bibtex

---

mmdet/models/roi_heads/cascade_roi_head.py

Bug fix.
Some loss (Seesaw loss..) may have custom activation to get the predicted labels.
I add custom activation to get correct ```cls_score```, which is used to compute ```roi_labels/bbox_labels```.
And  ```roi_labels/bbox_labels``` are used to refine bboxes when ```reg_class_agnostic = False ```.
Does the modification introduce changes that break the back-compatibility of …

Some loss (Seesaw loss..) may have custom activation to get the predicted labels.

---

configs/autoassign/README.md

Fix the style of backbone in AutoAssign readme
resolve #5101

change pytorch to caffe

---

docker/Dockerfile

Resolve:https://github.com/open-mmlab/mmdetection/issues/5501

Fix docker dependent mmcv versions

---

demo/MMDet_Tutorial.ipynb

fix a typo error in demo/MMDet_Tutorial.ipynb

[Docs] Fix typo

---

mmdet/apis/train.py

hot fix a crash caused by `get_root_logger` when cfg.log_level is not None, cause first arg in `get_root_logger` is `log_file`, not `log_level`
using keyword to call `get_root_logger` to pass the correct arg to `log_level`
If this PR introduces a new feature, it is better to list …

fixing crash caused by `get_root_logger`

---

requirements/mminstall.txt

The version of mmcv-full in mminstall.txt needs to be updated.

Fix mim dependent mmcv version

---

configs/cascade_rcnn/cascade_mask_rcnn_r50_caffe_fpn_1x_coco.py

Fix a pretrained error in mask rcnn

fix pretraied error

---

mmdet/datasets/custom.py

Here is the scenario: I created my own test data via Labelme, and converted the data into coco-style. Then I wanted to use CocoDataset to deal with my own data in mmdet. Soon I found a bug in description after 'build_dataset(cfg.data.train)'. My own data has  6 categories in total, but the description only printed first 5 categories. Then I checked the code and found the code works fine with coco dataset since it had 80 categories (can be divided by 5).
I added a few lines to address the issue mentioned above. Specifically, I …

[Fix] custom dataset description bug fix

---

mmdet/models/detectors/detr.py

Fix get_flops.py raising error when computing flops of DETR and Deformable DETR.
Multi-head attention does not support flops computing. The results are not correct. 
I add a warning in forward_dummy of DETR
resolve #5528 
resolve #5648

[Fix]: Fix get_flops.py raising error for DETR and Deformable DETR.

---

docs/conventions.md
mmdet/models/roi_heads/cascade_roi_head.py
mmdet/models/roi_heads/htc_roi_head.py
mmdet/models/roi_heads/scnet_roi_head.py
mmdet/models/roi_heads/sparse_roi_head.py
mmdet/models/roi_heads/test_mixins.py
tests/test_models/test_forward.py

Fix two-stage runtime error when empty proposal
Resolve: https://github.com/open-mmlab/mmdetection/issues/5037
All two-stage models deal with the case of empty proposal specially.

Fix two-stage runtime error when empty proposal

---

docs/tutorials/config.md
docs_zh-CN/tutorials/config.md

This PR adds a Chinese version of the config tutorial.

[Docs]: add Chinese version of config doc

---

configs/yolox/yolox_tiny.py

fix tiny config error

---

mmdet/datasets/builder.py

Reset resource limit to avoid being killed.

[Enhance] Reset resource limit

---

configs/yolox/yolox_l.py
configs/yolox/yolox_nano.py
configs/yolox/yolox_x.py

Update yolox-nano, m, l, and x to new settings.

Update YOLOX config

---

configs/yolox/yolox_s.py

fix mixup scale

---

mmdet/datasets/dataset_wrappers.py

adjust param

---

.gitignore
configs/fpg/README.md
docs/1_exist_data_model.md
docs/api.rst
docs/compatibility.md
docs/get_started.md
docs/tutorials/index.rst
docs/tutorials/robustness_benchmarking.md
mmdet/core/bbox/assigners/region_assigner.py
mmdet/core/bbox/iou_calculators/iou2d_calculator.py
mmdet/core/export/pytorch2onnx.py
mmdet/datasets/pipelines/transforms.py
mmdet/datasets/samplers/group_sampler.py
mmdet/models/dense_heads/anchor_head.py
mmdet/models/dense_heads/autoassign_head.py
mmdet/models/detectors/base.py

Some parts of the documentation are out of order.
Some errors are fixed and descriptions are rephrased.

Optimize `Get stated` in the documentation and fix some format errors

---

requirements/tests.txt
tests/data/configs_mmtrack/faster_rcnn_r50_dc5.py
tests/data/configs_mmtrack/faster_rcnn_r50_fpn.py
tests/data/configs_mmtrack/mot_challenge.py
tests/data/configs_mmtrack/selsa_faster_rcnn_r101_dc5_1x.py
tests/data/configs_mmtrack/tracktor_faster-rcnn_r50_fpn_4e.py
tests/test_downstream/test_mmtrack.py

This PR implements unit test for MMTracking to avoid potential bc-breakings from mmdetection.

[Feature] add unittest for mmtracking

---

mmdet/models/roi_heads/test_mixins.py
tests/test_models/test_forward.py

Fix empty rois error when test_cfg is None.

[Fix] Fix empty rois error when test_cfg is None

---

docs/tutorials/onnx2tensorrt.md
docs/tutorials/pytorch2onnx.md

Path of deployment docs were changed in MMCV, some links need to be updated.

[Fix]: Fix deployment doc links.

---

mmdet/core/bbox/assigners/__init__.py
mmdet/core/bbox/assigners/sim_ota_assigner.py
mmdet/models/dense_heads/__init__.py
mmdet/models/dense_heads/yolox_head.py
mmdet/models/losses/iou_loss.py
tests/test_models/test_dense_heads/test_yolox_head.py

Add YOLOXHead, SimOTAAssigner, and loss.

[Feature] Add YOLOXHead, SimOTAAssigner, and loss.

---

docker/serve/Dockerfile

Dinamically install mmcv from PYTORCH and CUDA args
Use bash brace expansion https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html to dynamically install mmcv from docker ARGs …

Use dynamic mmcv download link in TorchServe dockerfile

---

mmdet/core/hook/__init__.py
mmdet/core/hook/ema.py
tests/test_utils/test_hook_ema.py

Add EMA hook used in YOLOX.
add hook/ema.py and uinttest.

[Feature] Add EMA hook

---

mmdet/datasets/pipelines/__init__.py
mmdet/datasets/pipelines/transforms.py
tests/test_data/test_pipelines/test_transform/test_transform.py

Add RandomAffine transform which is used in YOLOX.

[Feature] Add RandomAffine transform.

---

docs_zh-CN/tutorials/data_pipeline.md

add Chinese version of data_pipline

[Docs] add Chinese version of data_pipline

---

mmdet/core/visualization/image.py

See: https://github.com/open-mmlab/mmdetection/issues/5844

Fix lose randomness in imshow_det_bboxes

---

docs/1_exist_data_model.md
docs_zh-CN/1_exist_data_model.md
tools/dataset_converters/images2coco.py

In order to facilitate users to test unlabeled images, a convert script has been added.

[Enhance] Add unlabeled image list to coco format scripts

---

docs/tutorials/customize_losses.md

As suggested in https://github.com/open-mmlab/mmdetection/pull/5826#discussion_r684874831, I add bold to the corresponding text

[fix] modify customize_losses.md

---

docs/useful_tools.md
setup.cfg
tools/analysis_tools/optimize_anchors.py

Support two different algorithm to optimize YOLO's anchors:
K-means refers from [darknet](https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L1421).
You can run:
```shell
python tools/analysis_tools/optimize_anchors.py ${CONFIG} --algorithm k-means --input-shape ${INPUT_SHAPE [WIDTH HEIGHT]} --output-dir ${OUTPUT_DIR}
```
To use differential evolution to optimize anchors, run:
```shell
python tools/analysis_tools/optimize_anchors.py ${CONFIG} --algorithm differential_evolution --input-shape ${INPUT_SHAPE [WIDTH HEIGHT]} --output-dir ${OUTPUT_DIR}
```
E.g.,
```shell
python tools/analysis_tools/optimize_anchors.py configs/yolo/yolov3_d53_320_273e_coco.py --algorithm differential_evolution --input-shape 608 608 --device cuda --output-dir work_dirs
```
You will get:
```
loading …
```

[Feature]: Add YOLO anchor optimizing tool

---

configs/libra_rcnn/README.md

This PR adds bibtex for Libra R-CNN's journal version.

add bibtex for Libra R-CNN's journal version

---

mmdet/datasets/pipelines/transforms.py

I followed https://github.com/open-mmlab/mmdetection/pull/5897 to modify and fixed the mosaic coordinate error.

Fix mosaic coordinate error

---

mmdet/datasets/coco_panoptic.py
tests/test_data/test_datasets/test_panoptic_dataset.py

Support classwise evaluation in CocoPanopticDataset.

[Enhance] Support classwise evaluation in CocoPanopticDataset

---

mmdet/models/backbones/darknet.py
mmdet/models/backbones/detectors_resnet.py
mmdet/models/backbones/hrnet.py
mmdet/models/backbones/mobilenet_v2.py
mmdet/models/backbones/regnet.py
mmdet/models/backbones/resnet.py
mmdet/models/backbones/ssd_vgg.py
mmdet/models/backbones/swin.py
mmdet/models/roi_heads/shared_heads/res_layer.py
tests/test_models/test_backbones/test_detectors_resnet.py

Just polished some messages with grammatical errors.

Polish assertion error msgs

---

configs/panoptic_fpn/README.md
docs/1_exist_data_model.md
docs/conventions.md
docs/tutorials/customize_dataset.md
docs_zh-CN/1_exist_data_model.md

Add dataset information in the README file for PanopticFPN.
Just like HTC and SCNet.

[Enhance] Add dataset information in the README file for PanopticFPN

---

tests/test_data/test_pipelines/test_transform/__init__.py
tests/test_data/test_pipelines/test_transform/test_img_augment.py
tests/test_data/test_pipelines/test_transform/test_rotate.py
tests/test_data/test_pipelines/test_transform/test_shear.py
tests/test_data/test_pipelines/test_transform/test_transform.py
tests/test_data/test_pipelines/test_transform/utils.py

Add data type check in transform unit test.
* Move some common functions into utils.py and add data type check.
* Assert dtype of box is float32.
None.

[Enhance]: Check dtype in transform unit tests.

---

mmdet/models/dense_heads/yolox_head.py

YOLOX supports fp16 training
Resolve: https://github.com/open-mmlab/mmdetection/issues/5981

YOLOX supports fp16 training

---

mmdet/models/roi_heads/htc_roi_head.py

The same fix as https://github.com/open-mmlab/mmdetection/pull/5221
Possibly fix https://github.com/open-mmlab/mmdetection/issues/6085

Fix aug_test of HTC when len(det_bboxes) is 0

---

tools/deployment/pytorch2onnx.py

1. Support dynamic input shape when using onnxsim.
2. Add check and warning to onnxsim.
Refer to https://github.com/open-mmlab/mmclassification/pull/438

[Enhance]: Support onnxsim with dynamic input shape.

---

mmdet/models/dense_heads/dense_test_mixins.py
mmdet/models/detectors/single_stage.py

Fix aug test error when the number of prediction bboxes is 0

Fix aug test error when the number of prediction bboxes is 0

---

configs/groie/README.md

Signed-off-by: Leonardo Rossi <leonardo.rossi@unipr.it>

configs: update groie README

---

docs/1_exist_data_model.md
docs_zh-CN/1_exist_data_model.md

[Fix] fix config path in docs

---

configs/groie/README.md
docs/1_exist_data_model.md
docs/2_new_data_model.md
docs_zh-CN/1_exist_data_model.md
mmdet/apis/__init__.py
mmdet/apis/inference.py
mmdet/apis/train.py
mmdet/models/backbones/pvt.py
mmdet/models/backbones/swin.py
tools/train.py

fix typo in docs https://github.com/open-mmlab/mmdetection/issues/6446
Edit https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/docs/2_new_data_model.md?plain=1#L260

Fix type error in 2_new_data_mode

---

mmdet/datasets/pipelines/transforms.py

Fix mosaic repr
`Mosaicimg_scale=(640, 640), center_ratio_range=(0.5, 1.5))pad_val=114`
--> `Mosaic(img_scale=(640, 640), center_ratio_range=(0.5, 1.5), pad_val=114)`

[Fix] Fix typo

---

docs/useful_tools.md

This is a very small PR. We use mmdetection in our research paper, training multiple models. I refer to documentation each time and copy the wrong command to convert MMDetection model to ONNX (happened multiple times now 😅 ) so I thought to fix this in the docs.
Updates the MMDetection model to ONNX command in docs to the right one
3. …

Fix MMDetection model to ONNX command in docs

---

README.md
README_zh-CN.md
docs/conf.py
docs_zh-CN/conf.py
mmdet/apis/train.py
tools/train.py

Remove unnecessary custom_import from train.py

Remove unnecessary custom_import from train.py

---

mmdet/models/dense_heads/lad_head.py

Fix LAD repeatedly output warning message
replace `anchor_generator` with `prior_generator`

Fix LAD repeatedly output warning message

---

.github/workflows/build.yml
.github/workflows/lint.yml

Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Testing skip CI
Add ignoring paths in GitHub yml. …

Skip CI on ignoring paths

---

.github/workflows/build.yml

Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Fix ignoring paths
Using `paths-ignore` instead …

Ignoring paths

---

tests/test_runtime/test_config.py

PR #6592 cleans FP16 configs but forgets to update unit tests.
Fix tests/test_config.py
N/A

Fix CI of FP16

---

README.md
README_zh-CN.md
docs/conf.py
docs_zh-CN/conf.py

Add mmhuman3d reference
Add mmhuman3d reference
no
n/a

[Enhance] Add mmhuman3d reference

---

docs/faq.md
docs_zh-CN/faq.md

Add doc for `detect_anomalous_params` in `OptimizerHook` 
Can be merged after https://github.com/open-mmlab/mmcv/pull/1547

[Doc]Add doc for detect_anomalous_params

---

mmdet/models/detectors/yolox.py

Support keeping image ratio in the multi-scale training of YOLOX
Modify the `_random_resize()` function in the YOLOX detector.
No BC-breaking.
3. If the modification has potential influence on downstream projects, this PR should …

Support keeping image ratio in the multi-scale training of YOLOX

---

docs/faq.md
docs_zh-CN/faq.md
mmdet/models/dense_heads/base_dense_head.py

Fix https://github.com/open-mmlab/mmdetection/issues/6718

Fix dtype bug in base_dense_head

---

.github/workflows/build.yml
.github/workflows/build_pat.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml

Cancel the outdated action in .github/workflows/*.yml file
modified: .github/workflows/build.yml
modified: .github/workflows/deploy.yml
modified: .github/workflows/lint.yml
[MMCV](https://github.com/open-mmlab/mmcv/pull/1537)
[MMSegmentation](https://github.com/open-mmlab/mmsegmentation/pull/1118)
[MIM](https://github.com/open-mmlab/mim/pull/91)
Different repo has different *.yml files in .github/workflows/.

[Fix] Cancel previous runs that are not completed

---

.pre-commit-config.yaml
configs/resnest/metafile.yml
model-index.yml

Use precommit to check readme.
Add a repo in `.pre-commit-config.yaml`

[Feature]Use precommit to check readme.

---

mmdet/core/bbox/assigners/sim_ota_assigner.py
tests/test_models/test_dense_heads/test_yolox_head.py

add unit test for SimOTA with no valid bbox

---

mmdet/models/detectors/base.py

The description of imgs in forward_train is not correct.
Fix #6793

[docs] Update mmdet/models/detectors/base.py

---

mmdet/core/hook/sync_norm_hook.py

Tigger bug when BN layer not exist.

fix norm sync bug

---

configs/strong_baselines/README.md

Fix typo in README.md of Strong Baselines.
Fixed large-scale "jittor" to large-scale jitter.

Fix typo in README.md of Strong Baselines

---

tests/test_models/test_forward.py

Fix YOLOX CI failed.
Reslove:  https://github.com/open-mmlab/mmdetection/issues/6863

Fix YOLOX CI failed

---

README.md
README_zh-CN.md

Add MMRazor and MMSelfSup link and info

---

mmdet/models/dense_heads/tood_head.py

Fix typo of tood 

---

mmdet/datasets/custom.py
requirements/runtime.txt

Increase the clarity of the installation process by downloading the model used in the verification sample code.
I have issues when training people to use these models that they stumble around the verification code, I found with this alteration there was less human error in verifying the installation.
Added shell commands for downloading config and weights.

Clearer verification of installation

---

docs/en/tutorials/data_pipeline.md
docs/zh_cn/tutorials/data_pipeline.md

fix broken image link
fix link url

fix broken image link

---

docs/en/changelog.md

Correct the contributors in v2.20.0.

[Fix] Correct the contributors in v2.20.0

---

.github/workflows/build.yml
README.md
README_zh-CN.md

Modification to promote OpenMMLab Platform following https://github.com/open-mmlab/mmdeploy/pull/64

Add link of OpenMMLab Platform

---

README.md
docs/en/tutorials/onnx2tensorrt.md
docs/en/tutorials/pytorch2onnx.md
docs/zh_cn/tutorials/onnx2tensorrt.md
docs/zh_cn/tutorials/pytorch2onnx.md

promote to use mmdeploy

---

mmdet/utils/__init__.py
mmdet/utils/setup_env.py
tests/test_utils/test_setup_env.py
tools/test.py
tools/train.py

Add setup multi-processing both in train and test.
Add unit tests.

[Enhance] Add setup multi-processing both in train and test.

---

.dev_scripts/check_links.py

Add check link script
```bash
Python .dev_scripts/check_links.py \ 
[--num-threads  ${NUM_THREADS}] \
[--https-proxy ${HTTPS_PROXY}] \
[--out ${OUT}]
```

Add check link script

---

docs/en/2_new_data_model.md
docs/zh_cn/2_new_data_model.md

Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Update code demo in doc
Just a line added in doc.
No
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like …

[doc] Update code demo in doc

---

.dev_scripts/benchmark_inference_fps.py
.pre-commit-config.yaml
mmdet/core/bbox/assigners/assign_result.py
mmdet/core/bbox/samplers/sampling_result.py
mmdet/core/mask/structures.py
mmdet/datasets/api_wrappers/panoptic_evaluation.py
mmdet/datasets/builder.py
mmdet/datasets/lvis.py
mmdet/models/backbones/pvt.py
setup.cfg
setup.py
tests/test_data/test_pipelines/test_transform/test_img_augment.py
tests/test_models/test_forward.py
tests/test_models/test_roi_heads/test_bbox_head.py
tests/test_models/test_roi_heads/test_mask_head.py
tests/test_runtime/test_config.py
tests/test_utils/test_anchor.py
tools/analysis_tools/test_robustness.py

Related PR  https://github.com/open-mmlab/mmflow/pull/87
1.Remove seed-isort-config in pre-commit hook
2.Upgrade isort to v5.10.1 (latest version)
3.Replace known_standard_library with extra_standard_library
4.imports order changes resulted from upgrading isort

[Enhancement] Upgrade isort in pre-commit hook

---

.github/workflows/build.yml
docs/en/get_started.md
docs/zh_cn/get_started.md

Update the version limitation of mmcv-full and pytorch in CI following https://github.com/open-mmlab/mmtracking/pull/409.
If this PR introduces a new feature, it is better to list some use cases here, and update the …

[Fix] Update the version limitation of mmcv-full and pytorch in CI.

---

.github/workflows/build.yml
mmdet/models/dense_heads/autoassign_head.py
mmdet/models/dense_heads/fcos_head.py

[FIX] add Ci of pytorch 1.10 and comments for bbox clamp (#7081)

---

.owners.yml

Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Add code owners config file in repo.
To enable the function for assigning devs automatically in `dele-bot`, check more details in https://github.com/open-mmlab/openmmlab-bot
If this PR introduces a new feature, it is better to list …

Add code owners

---

README.md
README_zh-CN.md

Add `mmrotate` link in `README.md`. …

Add mmrotate link in README.md

---

mmdet/core/bbox/assigners/sim_ota_assigner.py

[Enhance] Speed up SimOTA matching.

---

README.md
README_zh-CN.md

Group OpenMMLab projects based on their taxonomy, so that users could see related projects together.
README.md & README_zh-CN.md
1. Pre-commit or other linting tools are used …

Reorganizing OpenMMLab projects in readme

---

configs/yolact/README.md

An external link is broken.
Replace the old one with a valid link.

[Doc] Fix broken link

---

configs/yolact/README.md

Fix broken doc link

---

docs/en/useful_tools.md

fix image 'loss_curve.png' path error

Update useful_tools.md--fix image 'loss_curve.png' path error

---

README.md
README_zh-CN.md
docs/en/useful_tools.md
docs/zh_cn/tutorials/onnx2tensorrt.md
mmdet/models/necks/fpn.py
tools/test.py

[Fix] Fix typo in FPN neck

---

docs/en/get_started.md

Improve the docs.
a minor grammatical typo.
1. [x] Pre-commit or other linting tools are used to fix the potential lint issues.
2. [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. [x] If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. [x] The documentation has been modified accordingly, like docstring or example tutorials.

[Docs] a minor grammatical typo get_started.md

---

mmdet/core/utils/dist_utils.py
mmdet/datasets/samplers/distributed_sampler.py
mmdet/datasets/samplers/infinite_sampler.py

This is a supplementary note of https://github.com/open-mmlab/mmdetection/pull/7432
1. Pre-commit or other …

[Enchance] Supplementary notes of  sync_random_seed

---

mmdet/datasets/pipelines/instaboost.py
mmdet/datasets/pipelines/transforms.py
tools/analysis_tools/get_flops.py

[Enchance] Unified name of orig as ori

---

docs/en/tutorials/how_to.md
docs/en/tutorials/index.rst
docs/zh_cn/tutorials/how_to.md
docs/zh_cn/tutorials/index.rst

Added documentation on mmdet using mmcls‘s backbone.
1. Pre-commit or other linting tools are used to fix the …

[Enchance] Added documentation on mmdet using mmcls‘s backbone

---

.github/workflows/build.yml
configs/yolox/yolox_s_8x8_300e_coco.py
configs/yolox/yolox_tiny_8x8_300e_coco.py
docs/zh_cn/tutorials/finetune.md
mmdet/datasets/api_wrappers/panoptic_evaluation.py
mmdet/datasets/coco_panoptic.py
mmdet/datasets/custom.py
mmdet/datasets/pipelines/loading.py
mmdet/datasets/pipelines/transforms.py
mmdet/models/dense_heads/centripetal_head.py
mmdet/models/dense_heads/corner_head.py
mmdet/models/dense_heads/ssd_head.py
mmdet/models/dense_heads/yolox_head.py
mmdet/models/detectors/yolox.py
mmdet/models/necks/fpn.py
mmdet/utils/__init__.py
mmdet/utils/logger.py
tests/test_data/test_pipelines/test_loading.py
tests/test_utils/test_logger.py

Update pat CI and build.
.github/workflow/build_pat.yml
2. The modification is covered by …

Update mmcv installation in Pat CI

---

.pre-commit-config.yaml

The master branch of pre-commit-hooks may be unstable
rev: v0.2.0
2. The modification is …

[Fix]the master branch of pre-commit-hooks may be unstable

---

configs/fast_rcnn/README.md

Update  fast_rcnn README.
2. The …

[Doc] How to train fast_rcnn model.

---

configs/efficientnet/README.md
configs/efficientnet/metafile.yml
configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco.py
configs/faster_rcnn/README.md

Release efficientnet backbone pretrain model …

[Fix] Release efficientnet backbone pretrain model

---

mmdet/__init__.py

Bump max mmcv version to 1.6.0
1. Pre-commit or other linting tools are used to …

Increase max mmcv version limit to 1.6.0

---

demo/image_demo.py
mmdet/apis/inference.py

solve #7611
Add param `out_file`

[Enhance] Add param `out_file` in image_demo.py

---

mmdet/models/utils/transformer.py

[Enhance] Add comments for proposals in deformable detr

---

mmdet/apis/inference.py
mmdet/models/detectors/kd_one_stage.py
tests/test_runtime/test_apis.py

Closes #7649 
Fix to allow Path

[Feature] Support Pathlib for Config.fromfile

---

mmdet/core/hook/__init__.py
mmdet/core/hook/memory_profiler_hook.py
tests/test_utils/test_hook.py

[Feature] Support memory profile hook

---

docs/en/conf.py
docs/zh_cn/conf.py
requirements/docs.txt

Following https://github.com/open-mmlab/mmcv/pull/1287, use myst-parser so that we can beautify the doc in the future.
- modified:   docs/en/conf.py
- modified:   docs/zh_cn/conf.py
- modified:   requirements/docs.txt
N/A
3. If …

Use myst-parser to replace recommonmark

---

.dev_scripts/gather_models.py

`python .dev_scripts/gather_models.py ./work_dir ./gather `
- metafile
```
- Name: mask2former_r50_lsj_8x2_50e_coco_epoch
In …
```

[Enhance] IterBasedRunner mode for gather_model

---

requirements/docs.txt

Fix requirements.txt.
`pre-commit run --all-files`
2. The modification is covered by complete …

[Fix]Fix requirements.txt.

---

mmdet/models/backbones/resnet.py

fix #7795 
I checked that there is no model use two continuously plugins in resnet.
1. Pre-commit or other …

[Fix] Bug in resnet plugin

---

mmdet/apis/train.py
tools/train.py

#7668 move `samples_per_gpu` into `train_dataloader`, which causes `no attribute samples_per_gpu` error in `auto_scale_lr` #7482.
If this PR introduces a new feature, it is better to list …

[Fix] Fix no attribute 'samples_per_gpu' bug in `auto_scale_lr`

---

README.md
README_zh-CN.md

fix #7798 
2. The modification …

[Docs] Update readme

---

.github/workflows/build.yml

Fix GPG key error in CI and docker, which refer to https://github.com/open-mmlab/mmocr/pull/988/files
1. …

[Fix] Fix GPG key error in CI and docker

---

docs/en/stat.py

add model zoo statistics

---

configs/dyhead/README.md
configs/dyhead/atss_swin-l-p4-w12_fpn_dyhead_mstrain_2x_coco.py
configs/dyhead/atss_swin-l-p4-w12_fpn_dyhead_mstrain_3x_coco.py
configs/dyhead/metafile.yml

Release big model of dyhead + swin-l and align performance with dyhead paper.
The results are as below,
|  Model | Backbone | Lr schd |   Training image scale   | Testing image scale | bbox |
|:------:|:--------:|:-------:|:------------------------:|:-------------------:|:----:|
| DyHead |  Swin-L  |    2x   | (2000, 480)~(2000, 1200) |     (2000 1200)     | 56.2 |
The results with TTA are in progress.
Does the modification introduce changes that break the …

[Feature] Release dyhead big model.

---

docs/zh_cn/conf.py

Add myst_heading_anchors=4 in docs/en/conf.py to fix the error that the heading anchors do not work.
1. …

[Docs] Fix heading anchor in documentation

---

README.md
README_zh-CN.md

Add SOLOv2 because the author forgot to add it.
Add SOLOv2 to Overview of Benchmark and Model Zoo of `README.md` and `README_zh-CN.md`.

Add SOLOv2 to Overview of Benchmark and Model Zoo

---

mmdet/core/visualization/image.py
mmdet/datasets/api_wrappers/panoptic_evaluation.py
mmdet/datasets/coco_panoptic.py
tests/test_models/test_necks.py
tools/analysis_tools/analyze_results.py

1. Support panoptic segmentation result analysis.  The total evaluation time on results (coco val2017) generated by mask2former_r50 takes around 6 mins.
bad sample
000000017905.jpg with PQ = 0.308
good sample
000000455624.jpg with PQ = 0.887
2. add args `overlay_gt_pred`. image with gts and image with predictions will be concated.
set `overlay_gt_pred = False`, to plot gts and predictions on the images separately.
set `overlay_gt_pred = True`, to plot gts and predictions on the same images.
1. Add `print_log` in …

[Feature] Support panoptic segmentation result analysis

---

setup.py

Add mim to extras_require in setup.py …

[Fix] Add mim to extras_require in setup.py

---

.github/workflows/test_mim.yml

Test search command of mim in CI to ensure the format of metafile is correct..
Add .github/workflows/test_mim.yml.
No
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …

Test commands of mim in CI

---

.github/workflows/test_mim.yml
configs/cascade_rcnn/metafile.yml

Test commands of mim in CI 

---

mmdet/core/hook/wandblogger_hook.py

The motivation is to fix issue #8248.
Checking if meta dict has key `exp_name`. 
2. The …

Fix WandbLogger Hook Error #8248

---

mmdet/models/dense_heads/maskformer_head.py
mmdet/models/detectors/maskformer.py

Update maskformer.py and Update maskformer_head.py，For compatibility, the configuration cfg is a dictionary

Update maskformer.py and Update maskformer_head.py

---

requirements/docs.txt

Markdown 3.4 is released which causes issues in the shpinx markdown tables.
See https://github.com/open-mmlab/mmcv/pull/2121
requirements/docs.txt
N/A
N/A
4. The documentation has been modified …

Fix markdown version

---

mmdet/models/dense_heads/detr_head.py
mmdet/models/dense_heads/mask2former_head.py

[Fix] Fix Mask2Former

---

mmdet/core/visualization/image.py

https://github.com/open-mmlab/mmdetection/issues/4926
Set height and width on macOS.
2. The …

[Fix] set new hw on macos

---

.dev_scripts/batch_test_list.py
mmdet/datasets/transforms/formatting.py
mmdet/models/dense_heads/rpn_head.py
mmdet/structures/det_data_sample.py
mmdet/testing/_utils.py
mmdet/visualization/local_visualizer.py
tests/test_datasets/test_transforms/test_formatting.py
tests/test_structures/test_det_data_sample.py
tests/test_visualization/test_local_visualizer.py

Support panoptic_seg visualization

---

docs/en/2_new_data_model.md

#8390
Add checkpoint file download link for doc
Add checkpoint file download link for doc
2. …

Add checkpoint file download link for doc

---

mmdet/__init__.py

[Fix] update mmcv max version in init to fix CI

---

mmdet/models/data_preprocessors/data_preprocessor.py

[Fix] Bug related to PixelData

---

configs/_base_/default_runtime.py
configs/_base_/schedules/schedule_1x.py
configs/_base_/schedules/schedule_20e.py
configs/_base_/schedules/schedule_2x.py
configs/common/mstrain-poly_3x_coco_instance.py
configs/common/mstrain_3x_coco.py
configs/common/mstrain_3x_coco_instance.py
configs/grid_rcnn/grid_rcnn_r50_fpn_gn-head_2x_coco.py
configs/lad/lad_r101_paa_r50_fpn_coco_1x.py
configs/lad/lad_r50_paa_r101_fpn_coco_1x.py
configs/mask2former/mask2former_r50_lsj_8x2_50e_coco-panoptic.py
configs/maskformer/maskformer_r50_mstrain_16x1_75e_coco.py
configs/maskformer/maskformer_swin-l-p4-w12_mstrain_64x1_300e_coco.py
configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py
configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py
configs/pascal_voc/retinanet_r50_fpn_1x_voc0712.py
configs/wider_face/ssd300_wider_face.py
configs/yolox/yolox_s_8x8_300e_coco.py
configs/yolox/yolox_tiny_8x8_300e_coco.py
tools/train.py

[Fix] Fix auto scale lr

---

configs/_base_/datasets/coco_panoptic.py
configs/maskformer/maskformer_swin-l-p4-w12_mstrain_64x1_300e_coco.py
mmdet/evaluation/metrics/coco_panoptic_metric.py
tests/test_evaluation/test_metrics/test_coco_panoptic_metric.py

[Fix] FIx bug when evaluate with multi nodes

---

configs/lad/lad_r101_paa_r50_fpn_coco_1x.py
configs/lad/lad_r50_paa_r101_fpn_coco_1x.py
mmdet/models/detectors/lad.py

[Fix] fix LAD bug in dev-3.x

---

mmdet/evaluation/metrics/voc_metric.py

Fix eval_mode assert error in voc metric. …

[Fix] fix eval_mode assert error in voc metric

---

.dev_scripts/batch_test_list.py
mmdet/__init__.py
mmdet/datasets/transforms/formatting.py
mmdet/models/data_preprocessors/data_preprocessor.py
mmdet/models/dense_heads/anchor_free_head.py
mmdet/models/dense_heads/detr_head.py
mmdet/models/dense_heads/mask2former_head.py
mmdet/models/dense_heads/rpn_head.py
mmdet/structures/det_data_sample.py
mmdet/testing/_utils.py
mmdet/version.py
mmdet/visualization/local_visualizer.py
tests/test_datasets/test_transforms/test_formatting.py
tests/test_structures/test_det_data_sample.py
tests/test_visualization/test_local_visualizer.py

[Fix] Fix rebase

---

mmdet/models/layers/ema.py

PyTorch 1.6 does not support divide int with float.
Convert `step` to float

[Fix] Fix EMA with pytorch1.6.

---

mmdet/datasets/transforms/geometric.py

[Fix] Fix augment tests

---

mmdet/apis/inference.py

Support no meta field when weights converted from elsewhere

---

tests/test_visualization/test_local_visualizer.py

Fix visualization CI

---

mmdet/models/dense_heads/solov2_head.py

[Fix] fix solov2 head to support PyTorch 1.6

---

mmdet/datasets/transforms/geometric.py
tests/test_datasets/test_transforms/test_geometric.py

[Fix] Fix Shear and Translate

---

tools/train.py

Support auto resume

---

tests/test_datasets/test_transforms/test_loading.py

[Fix] fix ut for FliterAnnotations

---

mmdet/datasets/transforms/loading.py

[Fix] update polygon mask and bitmap mask

---

tools/analysis_tools/analyze_results.py

The bbox results exported by configs/convnext are in tuple format, it gave me an error when trying to parse them
Added functionality to parse tuple formatted data
1. …

Added tuple support in formatting results

---

mmdet/engine/hooks/memory_profiler_hook.py
tests/test_engine/test_hooks/test_memory_profiler_hook.py

[Fix] Fix memory profiler

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/transforms.py
tests/test_datasets/test_transforms/test_transforms.py

[Feature] Random erasing

---

mmdet/engine/__init__.py
mmdet/engine/runner/__init__.py
mmdet/engine/runner/loops.py
tests/test_engine/test_runner/test_loops.py

[Feature] Support MultiValLoop

---

docs/zh_cn/index.rst

Please refer to Issue #8563.
Thanks!

Added missed Chinese tutorial link

---

mmdet/engine/hooks/__init__.py
mmdet/engine/hooks/mean_teacher_hook.py
tests/test_engine/test_hooks/test_mean_teacher_hook.py

[Feature] Support MeanTeacher

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/loading.py
tests/test_datasets/test_transforms/test_loading.py

[Feature] Support LoadEmptyAnnotations

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/wrappers.py
tests/test_datasets/test_transforms/test_wrappers.py

[Feature] Support ShuffledSequence

---

mmdet/models/data_preprocessors/__init__.py
mmdet/models/data_preprocessors/data_preprocessor.py
tests/test_models/test_data_preprocessors/test_data_preprocessor.py

[Feature] Support MultiDataPreprocessor

---

mmdet/models/dense_heads/__init__.py

[Fix] Clean repeated import of CascadeRPNHead

---

.dev_scripts/benchmark_test.py
.dev_scripts/benchmark_train.py
mmdet/testing/__init__.py
mmdet/testing/_fast_stop_training_hook.py
mmdet/testing/_utils.py

support ceph, auto-resume, auto_scale_lr and benchmark_test

---

mmdet/datasets/transforms/augment_wrappers.py
mmdet/datasets/transforms/formatting.py
mmdet/datasets/transforms/geometric.py
mmdet/datasets/transforms/loading.py
mmdet/datasets/transforms/transforms.py
mmdet/models/data_preprocessors/data_preprocessor.py
mmdet/models/utils/__init__.py
mmdet/models/utils/misc.py
mmdet/structures/bbox/__init__.py
mmdet/structures/bbox/base_boxes.py
mmdet/structures/bbox/box_type.py
mmdet/structures/mask/structures.py
mmdet/testing/_utils.py
tests/test_datasets/test_transforms/test_geometric.py
tests/test_datasets/test_transforms/test_loading.py
tests/test_datasets/test_transforms/test_transforms.py
tests/test_datasets/test_transforms/utils.py
tests/test_models/test_data_preprocessors/test_data_preprocessor.py
tests/test_structures/test_bbox/test_base_boxes.py
tools/analysis_tools/browse_dataset.py

Refactor pipelines with new BoxList structures.
RetinaNet
- report: 36.5%
- retrain: 36.5%
Faster RCNN
- report: 37.4%
- retrain: 37.5%
If this PR introduces a new feature, it is better to list some use cases here, and …

[Refactor] Refactor pipelines with boxlist.

---

mmdet/datasets/transforms/formatting.py

correct vaild_idx to valid_idx

correct spelling error

---

docs/en/tutorials/customize_dataset.md
docs/zh_cn/tutorials/customize_dataset.md

[Docs] update dataset docs

---

tests/test_engine/test_hooks/test_mean_teacher_hook.py
tests/test_engine/test_runner/test_loops.py

[Fix]Fix mean teacher test

---

docs/en/2_new_data_model.md
docs/en/3_exist_data_new_model.md
docs/en/tutorials/customize_models.md
docs/en/tutorials/customize_runtime.md
docs/zh_cn/2_new_data_model.md
docs/zh_cn/3_exist_data_new_model.md
docs/zh_cn/tutorials/customize_models.md
docs/zh_cn/tutorials/customize_runtime.md

update: 2_new_data_model.md, 3_exist_data_new_model.md, customize_models.md, customize_runtime.md  
If this PR introduces a new feature, it is better to list some use cases here, and update …

[Fix] Fix docs: new_data_model, exist_data_new_model, customize_models, customize_runtime

---

docs/en/user_guides/config.md
docs/en/user_guides/dataset_prepare.md
docs/en/user_guides/inference.md
docs/en/user_guides/test.md
docs/en/user_guides/train.md

[Fix] Fix the doc

---

docs/en/advanced_guides/customize_models.md
docs/en/advanced_guides/customize_runtime.md
docs/en/advanced_guides/how_to.md
docs/zh_cn/advanced_guides/customize_models.md
docs/zh_cn/advanced_guides/customize_runtime.md
docs/zh_cn/advanced_guides/how_to.md

[Docs] Refine customize_models/customize_runtime/customize_models/how_to

---

README.md
README_zh-CN.md
docs/en/overview.md

update 3.x readme

---

docs/en/user_guides/init_cfg.md
docs/zh_cn/user_guides/init_cfg.md

[Docs] fix init_cfg.md

---

README.md
README_zh-CN.md

introduce 3.x in 2.x readme

---

mmdet/datasets/transforms/transforms.py
tools/analysis_tools/browse_dataset.py

[Fix] Fix bugs of pipelines and browse_dataset.py

---

requirements.txt

[Fix]: remove test requirements from all

---

docs/en/tutorials/config.md
docs/zh_cn/tutorials/config.md

To better use MMDetection functionality.
It's a few lines modified to add more logger hooks to docs.

[Docs] Update Config Doc to Add WandB Hook

---

mmdet/models/detectors/semi_base.py
mmdet/models/detectors/soft_teacher.py
mmdet/models/utils/__init__.py
mmdet/models/utils/misc.py
tests/test_models/test_utils/test_misc.py

[Refactor] Refactor SemiBaseDetector and SoftTeacher

---

docs/en/get_started.md
docs/zh_cn/get_started.md

Iwant to achieve through this PR.
The Code error occurred in strp 2 of verify the installation in MMdetection 3.x get_started.md.
Fix the Code of yolov3_mobilenetv2_8xb24-ms-416-300e_coco.py to yolov3_mobilenetv2_8xb24-320-300e_coco.py.
3. If the modification has potential influence on downstream projects, this PR should be tested with …

[get_started.md] Fix typos in MMDetection 3.x

---

mmdet/datasets/transforms/augment_wrappers.py

RandAugment uses `np.random.choice` to choice random transform from aug_space.
`np.random.choice` may choose the same transform several times, which I think may be inappropriate.
If this PR introduces a new feature, it is …

[Fix] Maybe a bug of `RandAugment`.

---

mmdet/models/dense_heads/__init__.py
mmdet/models/dense_heads/rtmdet_head.py
mmdet/models/detectors/__init__.py
mmdet/models/detectors/rtmdet.py
mmdet/models/layers/__init__.py
mmdet/models/layers/activations.py
mmdet/models/task_modules/assigners/__init__.py
mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py

Add RTMDet detector and head.
Add SiLU.
Add DynamicSoftLabelAssigner.

[Feature] Add RTMDet and DynamicSoftLabelAssigner.

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/transforms.py
mmdet/engine/hooks/__init__.py
mmdet/engine/hooks/pipeline_switch_hook.py

Add cached mosaic and cached mixup augmentation.

[Feature] Add cached mosaic, cached mixup, and pipeline switch hook.

---

configs/rtmdet/README.md
configs/rtmdet/metafile.yml
configs/rtmdet/rtmdet_l_8xb32-300e_coco.py
configs/rtmdet/rtmdet_m_8xb32-300e_coco.py
configs/rtmdet/rtmdet_s_8xb32-300e_coco.py
configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py
configs/rtmdet/rtmdet_x_8xb32-300e_coco.py
mmdet/models/dense_heads/rtmdet_head.py
model-index.yml

Add RTMDet series.
|  Backbone   | size | box AP | TRT-FP16-Latency(ms) | 
| :---------: | :--: | :----: | :------------------: | 
| RTMDet-tiny | 640  |  40.9  |         0.98         | 
|  RTMDet-s   | 640  |  44.5  |         1.22         | 
|  RTMDet-m   | 640  |  49.1  |         1.62         | 
|  RTMDet-l   | 640  |  51.3  |         2.44         | 
|  RTMDet-x   | 640  |  52.6  |         3.10         |

[Feature] Release RTMDet models and configs.

---

configs/rtmdet/README.md
configs/rtmdet/metafile.yml
configs/rtmdet/rtmdet_l_8xb32-300e_coco.py
configs/rtmdet/rtmdet_m_8xb32-300e_coco.py
configs/rtmdet/rtmdet_s_8xb32-300e_coco.py
configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py
configs/rtmdet/rtmdet_x_8xb32-300e_coco.py
mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/transforms.py
mmdet/engine/hooks/__init__.py
mmdet/engine/hooks/pipeline_switch_hook.py
mmdet/models/backbones/__init__.py
mmdet/models/backbones/cspnext.py
mmdet/models/dense_heads/__init__.py
mmdet/models/dense_heads/rtmdet_head.py
mmdet/models/detectors/__init__.py
mmdet/models/detectors/rtmdet.py
mmdet/models/layers/__init__.py
mmdet/models/layers/activations.py
mmdet/models/layers/csp_layer.py
mmdet/models/layers/se_layer.py
mmdet/models/necks/__init__.py
mmdet/models/necks/cspnext_pafpn.py
mmdet/models/task_modules/assigners/__init__.py
mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py
model-index.yml

Release RTMDet

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmdet/version.py
model-index.yml

Bump version to 3.0.0rc1

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/transforms.py
tests/test_datasets/test_transforms/test_transforms.py

[Feature]: support keep ratio resize

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/transforms.py

remove Normalize, use mmcv.Normalize instead.

remove Normalize

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

fix issue template

---

.pre-commit-config.yaml
configs/lad/README.md
docs/en/changelog.md
docs/en/tutorials/data_pipeline.md
mmdet/core/bbox/samplers/sampling_result.py
mmdet/models/losses/focal_loss.py
mmdet/models/losses/mse_loss.py
setup.cfg

The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade some versions of pre-commit hooks in dev-3.x.
No …

Upgrade pre commit hooks in master

---

mmdet/visualization/__init__.py
mmdet/visualization/local_visualizer.py
mmdet/visualization/palette.py
tests/test_visualization/test_palette.py

Jitter the mask color in order to better distinguish instances with the same class.
add a jitter_color fucntion
2. The modification is covered by complete unit tests. If not, please add more unit test to …

[Enhance] Jitter instance color.

---

mmdet/structures/mask/structures.py
tests/test_structures/test_mask/test_mask_structures.py

Support mask concatenate.
add `cat` classmethod to MaskStructure
2. The modification is …

[Feature] Support mask concatenate.

---

docs/en/get_started.md

Wrong image linked on line 93.
Changed the image name.
No
If this PR introduces a new feature, it is better to list some use …

Wrong image linked on line 93

---

tools/misc/print_config.py

update print config

---

mmdet/datasets/coco.py
mmdet/datasets/custom.py

use seg_suffix to resolve the https://github.com/open-mmlab/mmdetection/pull/6490

fix jpg->png

---

mmdet/datasets/transforms/transforms.py
tests/test_datasets/test_transforms/test_transforms.py

Fix bug of albumentations may return np.array or list on different versions
1. Pre-commit or other linting tools …

Fix bug of albumentations may return np.array or list on different versions

---

README.md
README_zh-CN.md

Add MMYOLO projects link

---

mmdet/evaluation/metrics/coco_metric.py

Log copypaste message.
Add log info.
```
2022/10/13 11:29:44 - mmengine - INFO - Epoch(test) [50/100]    eta: 0:00:03  time: 0.0669  data_time: 0.0053  memory: 116  
2022/10/13 11:29:46 - mmengine - INFO - Epoch(test) [100/100]    eta: 0:00:00  time: 0.0414  data_time: 0.0008  memory: 116  
2022/10/13 11:29:47 - mmengine - INFO - Evaluating bbox...
2022/10/13 11:29:52 - mmengine - INFO - bbox_mAP_copypaste: 0.519 0.672 0.561 0.321 0.551 0.718
2022/10/13 11:29:53 - mmengine - INFO - Epoch(test) [100/100]  coco/bbox_mAP: 0.5190 …
```

[Enhance] Log coco metric copypaste.

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmdet/version.py

Add changelog with 3.0.0rc2

---

mmdet/datasets/base_det_dataset.py
mmdet/datasets/coco.py

migrate https://github.com/open-mmlab/mmdetection/pull/9078 to dev-3.x

fix jpg->png in dev-3.x

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-new-model.yml
.github/ISSUE_TEMPLATE/4-documentation.yml
.github/ISSUE_TEMPLATE/5-reimplementation.yml

Refer to https://github.com/open-mmlab/mmediting/pull/1286
1. Pre-commit or other linting tools are used to fix …

[Enhancement] improve issue template

---

tools/analysis_tools/eval_metric.py

Support the latest version of MMEngine.

[Bug]Update eval_metric.py

---

mmdet/models/detectors/rpn.py

[Fix] Fix RPN visualization

---

docs/zh_cn/tutorials/how_to.md

Delete redundant Chinese characters in config

---

configs/detr/detr_r18_8xb2-500e_coco.py

fix detr_r18_config

---

configs/simple_copy_paste/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-270k_coco.py
configs/simple_copy_paste/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-scp-270k_coco.py
configs/strong_baselines/mask-rcnn_r50-caffe_fpn_rpn-2conv_4conv1fc_syncbn-all_lsj-100e_coco.py
configs/strong_baselines/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_lsj-100e_coco.py

renamed the package names mmcv-full to mmcv …

fix mmcv-full

---

mmdet/utils/__init__.py
mmdet/utils/misc.py
tools/analysis_tools/test_robustness.py
tools/test.py

Fix incorrect hard code of adding DumpResults in config.
Directly add the DumpResults objects to the runner's evaluator.
resolve #9237

[Fix] Fix dump results.

---

mmdet/apis/inference.py
mmdet/datasets/transforms/loading.py

linked: https://github.com/open-mmlab/mmyolo/issues/230
1. Pre-commit or other linting tools are used to fix the …

Fix module unregistered error when MMYOLO calls inference_detector

---

mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py

Fix UT error of dynamic_soft_label_assigner

---

mmdet/models/roi_heads/bbox_heads/multi_instance_bbox_head.py

[Fix] Fix CI

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md

Fix some format issues in changelog

[Doc]: update changelog

---

configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco.py
configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-3x_coco.py

[Fix] Fix configs of faster rcnn with caffe backbone

---

mmdet/apis/inference.py
mmdet/utils/__init__.py
mmdet/utils/misc.py

infereence_detector cannot get the test pipeline when using a dataset wrapper.
1. Pre-commit or other linting …

[Enhance] Handle dataset wrapper in inference_detector

---

docs/en/user_guides/deploy.md
docs/en/user_guides/index.rst
docs/zh_cn/user_guides/deploy.md
docs/zh_cn/user_guides/index.rst

Update mmdet 3.x deployment guide
add `mmdeploy.md` to both `en` and `cn_zh` docs

update guide about model deployment

---

projects/example_project/README.md
projects/example_project/configs/faster-rcnn_dummy-resnet_fpn_1x_coco.py
projects/example_project/dummy/__init__.py
projects/example_project/dummy/dummy_resnet.py

Introducing new models and features into OpenMMLab's algorithm libraries has long been complained to be troublesome due to the rigorous requirements on code quality, which could hinder the fast iteration of SOTA models and might discourage potential contributors from sharing their latest outcome here.
This PR adds a new projects/ folder, which will be a place for some experimental models/features. Implementations inside might be not quite perfect but already fine to produce some exciting results. We hope that this PR can help us better embrace the contribution from our community. We also add the first example project to illustrate what we expect a good project to have.

[Community] Add 'Projects/' folder, and the first example project.

---

mmdet/models/roi_heads/bbox_heads/bbox_head.py

[Fix] Fix bbox refine bug with sigmoid activation.

---

configs/retinanet/retinanet_r50_fpn_fp16_1x_coco.py
configs/ssd/ssd512_fp16_coco.py
docs/en/device/npu.md
docs/en/index.rst

add NPU results.
add docs/en/device/npu.md and configs that accompanies the submission results.

[Feature] add docs with NPU backend 

---

tools/misc/print_config.py

Save config file in type of '.py', '.json', or '.yml' to modify or view whole config.

[Feature] save config file in print_config.py 

---

mmdet/models/detectors/condinst.py

Relative Issue: https://github.com/open-mmlab/mmdetection/issues/9375

[Fix] Fix mmdet.utils.typing error in CondInst

---

projects/SparseInst/README.md
projects/SparseInst/configs/sparseinst_r50_iam_8xb8-ms-270k_coco.py
projects/SparseInst/sparseinst/__init__.py
projects/SparseInst/sparseinst/decoder.py
projects/SparseInst/sparseinst/encoder.py
projects/SparseInst/sparseinst/loss.py
projects/SparseInst/sparseinst/sparseinst.py

Add an example project. It is an implementation of [SparseInst](https://github.com/hustvl/SparseInst) based on [MMDetection](https://github.com/open-mmlab/mmdetection/tree/3.x), [MMCV](https://github.com/open-mmlab/mmcv), and [MMEngine](https://github.com/open-mmlab/mmengine).
| Backbone |  Style  | Lr schd | Mem (GB) | FPS  | mask AP val2017 |                           Config                            | 
| :------: | :-----: | :-----: | :------: | :--: | :-------------: | :---------------------------------------------------------: | 
|   R-50   | PyTorch |  270k   |   8.7    | 44.3 |      32.9 (official 32.8)      | [config](./configs/sparseinst_r50_iam_8xb8-ms-270k_coco.py) | 
This project follows the official version's code architecture, and can easily use OpenMMLab's backbones, …

[Projects] Add SparseInst project.

---

README.md
README_zh-CN.md
docker/serve/Dockerfile
docs/en/notes/changelog.md
docs/en/notes/faq.md
docs/zh_cn/notes/faq.md
mmdet/version.py

Add changelog and bump version to 3.0.0rc4

Bump version to 3.0.0rc4

---

.pre-commit-config-zh-cn.yaml

…talling pre-commit
According to mmcv's instructions to install pre-commit, we need  .pre-commit-config-zh-cn.yaml. And mmdetection doesn't have provide this file yet. So i borrow this file from mmyolo to fix it.
This .pre-commit-config-zh-cn.yaml file is borrowed from mmyolo, and i only modified line 54 - line 56 to fit into mmdetection.
If so, please describe how it breaks the compatibility and how the downstream projects …

[Fix] add .pre-commit-config-zh-cn.yaml file

---

tools/analysis_tools/analyze_results.py

fix analyze_results

---

setup.cfg

[Refactor] Refactor `setup.cfg`

---

mmdet/models/necks/pafpn.py

Backward pass error when using inplace operation with ReLU.
For example, if `act_cfg=dict(type='ReLU')`, training would raise errors.
Don't do inplace operations.
1. …

[Fix] Fix backward inplace error with pafpn

---

docs/zh_cn/user_guides/useful_hooks.md
docs/zh_cn/user_guides/useful_tools.md

超级视客营-MMDetection-34
更新代码库中useful_tools.md and useful_hooks.md的中文部分
2. The modification is …

CodeCamp #34 [Doc] update the zh_cn user_guides of useful_tools.md and useful_hooks.md

---

mmdet/models/dense_heads/deformable_detr_head.py

Fix 'DeformableDETRHead' object has no attribute 'loss_single' 

---

.circleci/test.yml

Add torch1.13 checking in CI

---

docs/en/api.rst
docs/zh_cn/api.rst
requirements/readthedocs.txt

Fix the error that Readthedocs API cannot be displayed

---

mmdet/models/task_modules/prior_generators/anchor_generator.py
mmdet/models/task_modules/prior_generators/point_generator.py
mmdet/models/task_modules/prior_generators/utils.py

CodeCamp #33

---

configs/common/ms-poly_3x_coco-instance.py

Add segm evaluator in ms-poly_3x_coco_insatnce config
configs/common/ms-poly_3x_coco-instance.py …

[Fix]: Add segm evaluator in ms-poly_3x_coco_insatnce config

---

docs/en/user_guides/deploy.md
docs/zh_cn/user_guides/deploy.md

Introduce how to use mmdeploy's API to convert model and perform model inference.
1. Pre-commit or other linting …

[Enhance] update deployment guide

---

mmdet/apis/inference.py

Fix compatibility of dataset meta before 3.0.0rc5
convert all meta keys to lowercase
2. The …

[Fix] Fix dataset meta compatibility.

---

mmdet/datasets/transforms/transforms.py

When using albu augmentations with masks, post_process function don't deal with masks.

[Fix] albu augmentation post process with masks

---

.pre-commit-config-zh-cn.yaml

[pre-commit] Replace `github` with `gitee`

---

.github/workflows/build.yml
docs/en/get_started.md
docs/zh_cn/get_started.md
setup.py

[Fix] Adjust the minimum supported python version to 3.7

---

mmdet/models/dense_heads/rtmdet_head.py
mmdet/models/necks/cspnext_pafpn.py

[Fix] Fix use_depthwise in RTMDet.

---

docs/en/user_guides/dataset_prepare.md
docs/en/user_guides/useful_tools.md
docs/zh_cn/user_guides/dataset_prepare.md
docs/zh_cn/user_guides/useful_tools.md

add opendatalab download link in dataset_prepare docs, including:
- docs/en/user_guides/dataset_prepare.md
- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/dataset_prepare.md
- docs/zh_cn/user_guides/useful_tools.md

[Doc] add opendatalab download link

---

README.md
README_zh-CN.md
docker/serve/Dockerfile
docs/en/changelog.md
docs/en/faq.md
mmdet/version.py

Bump version to v2.28.0

---

.pre-commit-config-zh-cn.yaml
.pre-commit-config.yaml

Fix isort ci
2. The modification …

Fix isort ci

---

mmdet/models/detectors/yolof.py

Can't init yolof detector
Add init_cfg to yolof like other detectors

add yolof init_cfg

---

.pre-commit-config-zh-cn.yaml
.pre-commit-config.yaml

Link https://github.com/open-mmlab/mmeval/pull/86.

dev-3.x: Use official isort

---

mmdet/datasets/transforms/loading.py
tests/test_datasets/test_transforms/test_loading.py

fix PR #8715 ci_test_bugs
2. The …

【Fix】fix ci test bug

---

.readthedocs.yml
requirements/readthedocs.txt

fix scipy requirements
update to python3.8 since 3.7 is deprecated by many packages

fix readthedoc

---

requirements/optional.txt

The 'sklearn' PyPI package is deprecated, use 'scikit-learn'  rather than 'sklearn' for pip commands.
1. …

deprecate sklearn

---

configs/wider_face/ssd300_wider_face.py

SSD300 requires grad clip to avoid exploding gradients.
Resolve #9542
Add grad_clip in config. …

[Fix] Fix WIDERFace SSD loss NAN.

---

mmdet/models/data_preprocessors/data_preprocessor.py

Support to modify `non_blocking` parameters

---

mmdet/datasets/dataset_wrappers.py

[Fix] Fix potential bug in `MultiImageMixDataset`

---

configs/centernet/centernet_tta.py
configs/retinanet/retinanet_tta.py
configs/yolox/yolox_tta.py
mmdet/models/test_time_augs/det_tta.py

Fix the error when there is no prediction results and support vis

---

.dev_scripts/benchmark_valid_flops.py
configs/simple_copy_paste/metafile.yml
mmdet/models/detectors/single_stage_instance_seg.py
mmdet/models/roi_heads/sparse_roi_head.py
tools/analysis_tools/get_flops.py

[Fix] Fix compute flops problems

---

configs/deformable_detr/metafile.yml
configs/detr/metafile.yml
configs/mask2former/metafile.yml

Fix metafile error

---

mmdet/datasets/transforms/transforms.py

Fix albu augmentation with the mask shape.
Since the masks may be downsampled in the pipeline,  we use the mask shape instead of the img shape in albu augmentation.

[Fix] albu augmentation with mask shape

---

mmdet/apis/test.py

support mlu device for multi_gpu_test api
Use get_device() instead of ’cuda’ in mmdet/apis/test.py
If this PR introduces a new feature, it is better to list some use cases here, and update …

[Feature] support multi test for mlu

---

configs/albu_example/metafile.yml
configs/boxinst/README.md
configs/boxinst/metafile.yml
configs/centernet/metafile.yml
configs/lvis/metafile.yml
configs/rpn/metafile.yml
configs/soft_teacher/metafile.yml
configs/strong_baselines/metafile.yml
model-index.yml

[Fix] Fix metafile.

---

mmdet/datasets/transforms/__init__.py
mmdet/datasets/transforms/formatting.py
mmdet/datasets/transforms/frame_sampling.py
mmdet/datasets/transforms/loading.py
mmdet/datasets/transforms/transforms.py
tests/test_datasets/test_transforms/test_formatting.py
tests/test_datasets/test_transforms/test_frame_sampling.py
tests/test_datasets/test_transforms/test_loading.py
tests/test_datasets/test_transforms/test_transforms.py

This PR should not be merged until the PR https://github.com/open-mmlab/mmdetection/pull/9897 is merged.
Add LoadTrackAnnotations, UniformSample, PackTrackInputs
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the …

[Feature] Add common tracking transforms

---

mmdet/models/dense_heads/rtmdet_ins_head.py

[Fix] Fix RTMDetIns prior generator device.

---

configs/boxinst/boxinst_r101_fpn_ms-90k_coco.py

[Fix] add boxinst r101 config

---

mmdet/datasets/transforms/transforms.py
mmdet/structures/det_data_sample.py
tests/test_datasets/test_transforms/test_transforms.py

img_shape should be (h, w)
TODO:

[Fix] Fix img_shape.

---

tests/test_utils/test_benchmark.py

[Fix] Fix inference benchmark ut.

---

.circleci/test.yml
mmdet/evaluation/functional/cityscapes_utils.py
mmdet/evaluation/metrics/cityscapes_metric.py

[FIX] Fix cityscapes import error

---

mmdet/models/dense_heads/yolo_head.py

Resolve https://github.com/open-mmlab/mmdetection/issues/9962

[Fix] Fix YOLOv3 TTA

---

docs/zh_cn/user_guides/dataset_prepare.md

refine data_prepare docs

---

docs/en/notes/faq.md
docs/zh_cn/notes/faq.md

update zh_cn doc error
update zh_cn doc error
If this PR introduces a new feature, it is better to list some use cases here, and …

[Docs] update zh_cn doc error

---

.circleci/test.yml
configs/_base_/datasets/mot_challenge.py
mmdet/datasets/transforms/loading.py
mmdet/evaluation/metrics/__init__.py
mmdet/evaluation/metrics/base_video_metric.py
mmdet/evaluation/metrics/coco_video_metric.py
mmdet/evaluation/metrics/mot_challenge_metric.py
tests/test_datasets/test_transforms/test_loading.py
tests/test_evaluation/test_metrics/test_coco_video_metric.py
tests/test_evaluation/test_metrics/test_mot_challenge_metrics.py

This PR should not be merged until the PR https://github.com/open-mmlab/mmdetection/pull/9897 and https://github.com/open-mmlab/mmdetection/pull/9906 is merged.
This PR should not be merged until the PR #9897 and #9906 is merged.
2. The modification is covered by complete unit tests. If not, please add more unit …

[Feature] Add tracking evaluation

---

mmdet/models/dense_heads/solov2_head.py

When the solov2 model runs on the NPU, there will be a precision problem. 
It is due to the precision problem of the max_pool2d operator on NPU when the dtype of inputs is float32.
This problem is currently circumvented by converting the input of max_pool2d to float16, and we will fix the precision problem of max_pool2d operator in Q2 of 2023.
Not involved.
Not involved.

[Fix] Fix the precision problem of solov2 model on NPU.

---

README.md
README_zh-CN.md

Add more social networking links(dev-3.x).
Add more social networking links(dev-3.x).
2. The …

[Doc]: Add more social networking links(dev-3.x)

---

README.md
README_zh-CN.md

Add more social networking links.
Add more social networking links.
2. The modification is …

[Doc]: Add more social networking links

---

configs/solov2/solov2_r50_fpn_ms-3x_coco.py

fix conflict bug in train_cfg

---

configs/rtmdet/README.md

Modifyed the readme.md of rtmdet
Add rtmder config introduce in readme.md
2. The modification …

[Docs] Add rtmder config introduce

---

docs/en/user_guides/visualization.md

Reference from https://github.com/open-mmlab/mmocr/blob/1.x/docs/en/user_guides/visualization.md

Add visualization docs

---

tools/test.py
tools/train.py

Fix accepting an unexpected argument local-rank in PyTorch 2.0

---

docs/en/notes/faq.md
docs/zh_cn/notes/faq.md
mmdet/utils/__init__.py
mmdet/utils/setup_env.py
tools/test.py
tools/train.py

Support setting the `cache_size_limit` parameter of dynamo in PyTorch 2.0

---

mmdet/models/dense_heads/reppoints_head.py

The input parameter value is missing the device setting, so an error was reported when running on the npu.

【fix】 fix reppoints head device bug

---

tools/analysis_tools/get_flops.py

【Fix】fix compute flops error

---

docs/zh_cn/user_guides/visualization.md

Translating visualization documents into English

---

model-index.yml

Fix metainfo of softteacher

---

docs/en/get_started.md
docs/en/notes/faq.md
docs/en/user_guides/label_studio.md
docs/zh_cn/get_started.md
docs/zh_cn/notes/faq.md
docs/zh_cn/user_guides/label_studio.md

Update version and README

---

configs/rtmdet/README.md

When I run the written code, an error occurs saying that the pth file cannot be found.
Update pre-trained rtmdet-ins pth file path.
1. Pre-commit or other linting tools are …

[Doc] Update pre-trained rtmdet-ins pth file's path in README.md

---

README_zh-CN.md

MMClassification has been renamed as MMPretrain
MMClassification to MMPretrain
2. The …

[Doc]: Update README_zh-CN.md(dev-3.x)

---

configs/_base_/datasets/coco_panoptic.py

solve issue #10199
3. If the modification has potential influence on downstream projects, …

[Fix]  fix mask2former config

---

README.md
README_zh-CN.md

update readme of projects

---

mmdet/core/visualization/image.py

[Fix]fix empty stats error in show mask

---

configs/faster_rcnn/faster-rcnn_r50-caffe-c4_ms-1x_coco.py
configs/faster_rcnn/faster-rcnn_r50-caffe-dc5_ms-1x_coco.py
configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco.py
configs/fcos/fcos_r101-caffe_fpn_gn-head_ms-640-800-2x_coco.py
configs/fcos/fcos_r50-caffe_fpn_gn-head_ms-640-800-2x_coco.py
configs/fcos/fcos_x101-64x4d_fpn_gn-head_ms-640-800-2x_coco.py
configs/retinanet/retinanet_r50-caffe_fpn_ms-1x_coco.py

Minor bugfix. RandomChoiceResize should get scales instead of scale.
I changed the RandomChoiceResize scale into scales in all the training pipelines.
No.
None.
4. The documentation has been …

minor bugfix. RandomChoiceResize should get scales instead of scale.

---

configs/_base_/datasets/coco_panoptic.py
requirements/readthedocs.txt

[Fix] Fix doc ci error and file backend error

---

tools/misc/download_dataset.py

Update MMDet_Tutorial.ipynb of 3.x
- `demo/MMDet_Tutorial.ipynb`
- `tools/misc/download_dataset.py`

[Docs] Update MMDet_Tutorial.ipynb of 3.x

---

mmdet/models/reid/base_reid.py
mmdet/models/trackers/ocsort_tracker.py
mmdet/models/trackers/sort_tracker.py
mmdet/models/trackers/strongsort_tracker.py

[Fix] fix downstream repo ci error

---

mmdet/visualization/local_visualizer.py

[Fix] fix seaborn import error

---

.dev_scripts/gather_models.py
configs/centernet/README.md
configs/centernet/metafile.yml

Add `centernet-update_r50-caffe_fpn_ms-1x_coco` weights

---

docs/en/migration/config_migration.md

…ple.
The version information of the first block of code is wrong
Change version information from 2.x to 3.x
1. Pre-commit or other linting tools are used to fix the …

Update information about `config_migration.md`

---

configs/rtmdet/rtmdet_l_8xb32-300e_coco.py
configs/rtmdet/rtmdet_tta.py

Fix RTMDet miss `LoadAnnotations` bug in test_pipeline

---

configs/maskformer/metafile.yml

Fix maskformer metafile link

---

docs/en/user_guides/new_model.md
docs/zh_cn/user_guides/new_model.md

The params of Rotate and TranslateX in the current doc are outdated,
this PR will update them to the newest param.
https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/mmdet/datasets/transforms/geometric.py#L462-L465

[Docs] Adapt to new AutoAugment params in user_guides/new_model.md

---

mmdet/models/utils/vlfuse_helper.py

Fix GLIP dependence

---

mmdet/models/detectors/glip.py

Fix NLTK download link

---

docs/en/user_guides/train.md
docs/zh_cn/user_guides/train.md

update docs/zh_cn/user_guides/train.md and its English version
update docs/zh_cn/user_guides/train.md and its English version

[Docs]bjzhb666/update docs/zh_cn/user_guides/train.md

---

configs/_base_/datasets/coco_caption.py
mmdet/datasets/__init__.py
mmdet/datasets/coco_caption.py
mmdet/evaluation/metrics/__init__.py
mmdet/evaluation/metrics/coco_caption_metric.py
tools/misc/download_dataset.py

Add coco caption dataset

---

configs/_base_/datasets/refcoco+.py
configs/_base_/datasets/refcoco.py
configs/_base_/datasets/refcocog.py
docs/en/user_guides/dataset_prepare.md
mmdet/datasets/__init__.py
mmdet/datasets/refcoco.py
tools/misc/download_dataset.py

Add Refcoco, Refcoco+ and Refcocog datasets.

[Feature] Support refcoco datasets

---

mmdet/datasets/ade20k.py

[FIx] Fix ade20k dataset wrong return typing

---

configs/_base_/datasets/ade20k_semseg.py
mmdet/datasets/transforms/loading.py
mmdet/evaluation/metrics/semseg_metric.py
projects/XDecoder/configs/xdecoder-tiny_zeroshot_open-vocab-semseg_ade20k.py
projects/XDecoder/xdecoder/unified_head.py

Fix semseg eval

---

configs/_base_/datasets/coco_semantic.py
demo/image_demo.py
mmdet/apis/det_inferencer.py
mmdet/datasets/base_semseg_dataset.py
mmdet/datasets/coco_panoptic.py
projects/XDecoder/xdecoder/inference/image_caption.py
projects/gradio_demo/README.md
projects/gradio_demo/launch.py

Add some docstring

---

docs/en/user_guides/dataset_prepare.md
mmdet/datasets/ade20k.py
mmdet/visualization/local_visualizer.py
projects/XDecoder/README.md
projects/XDecoder/configs/xdecoder-tiny_zeroshot_open-vocab-panoptic_ade20k.py
tools/dataset_converters/ade20k2coco.py
tools/misc/download_dataset.py

fix ade panoptic

---

docs/en/user_guides/dataset_prepare.md
docs/zh_cn/user_guides/dataset_prepare.md
projects/XDecoder/README.md
tests/test_datasets/test_transforms/test_loading.py
tests/test_datasets/test_transforms/test_transforms.py

Add unittest

---

mmdet/datasets/transforms/transforms.py

Image size after mosaic should be twice the input size

[Docs] Fix wrong doc in Mosaic and CachedMosaic

---

mmdet/models/losses/focal_loss.py

Enhance the code to make it more easily comprehensible. As in the paper, pt denotes the probability, and the coefficient of Focal Loss is ``\alpha * (1 - pt) ** \gamma``
Modified the computation method of the Focal Loss coefficient.

Update focal_loss.py to consist with the original formula.

---

mmdet/models/detectors/glip.py

Add docstring to glip.py from `mmdet/model/detectors/glip.py`.
Add more docstring to help users get familiar with the code.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …

[Docs] Add docstring.

---

projects/VISION-Datasets/README.md
projects/VISION-Datasets/README_zh-CN.md

Add VISION dataset

---

.circleci/test.yml
.dev_scripts/benchmark_options.py
.github/pull_request_template.md
configs/convnext/README.md
configs/convnext/cascade-mask-rcnn_convnext-s-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py
configs/convnext/cascade-mask-rcnn_convnext-t-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py
configs/convnext/mask-rcnn_convnext-t-p4-w7_fpn_amp-ms-crop-3x_coco.py
configs/deepsort/deepsort_faster-rcnn_r50_fpn_8xb2-4e_mot17halftrain_test-mot17halfval.py
configs/reid/README.md
configs/reid/reid_r50_8xb32-6e_mot17train80_test-mot17val20.py
configs/rtmdet/classification/README.md
configs/rtmdet/classification/cspnext-s_8xb256-rsb-a1-600e_in1k.py
configs/strongsort/strongsort_yolox_x_8xb4-80e_crowdhuman-mot17halftrain_test-mot17halfval.py
configs/timm_example/README.md
configs/timm_example/retinanet_timm-efficientnet-b1_fpn_1x_coco.py
configs/timm_example/retinanet_timm-tv-resnet50_fpn_1x_coco.py
docs/en/advanced_guides/how_to.md
docs/en/user_guides/deploy.md
docs/zh_cn/advanced_guides/how_to.md
docs/zh_cn/user_guides/deploy.md
mmdet/models/backbones/efficientnet.py
mmdet/models/backbones/pvt.py
mmdet/models/data_preprocessors/reid_data_preprocessor.py
mmdet/models/reid/base_reid.py
mmdet/models/reid/linear_reid_head.py
projects/ConvNeXt-V2/README.md
projects/ConvNeXt-V2/configs/mask-rcnn_convnext-v2-b_fpn_lsj-3x-fcmae_coco.py
requirements/tracking.txt
tests/test_models/test_reid/test_linear_reid_head.py

replace mmcls with mmpretrain

---

.dev_scripts/benchmark_full_models.txt
configs/mask2former_vis/metafile.yml
model-index.yml

Fix some metafile.yml files

---

demo/video_gpuaccel_demo.py

> Please describe the motivation of this PR and the goal you want to achieve through this PR.
This goal is fixing #10534
> Please briefly describe what modification is made in this PR.
This bug causes `data` variable passed to `model.test_step`. So, I modified it.

Fix  `demo/video_gpuaccel_demo.py` scripts

---

docs/en/get_started.md

Fix typo on readme.
Removed duplicate `for`. From `for for` to `for`.
No
n/a
1.[n/a] Pre-commit or other linting tools are used to fix the potential lint issues. 
2. [n/a] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. [n/a] If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or …

Fix grammar/typo

---

mmdet/datasets/transforms/transforms.py
mmdet/models/test_time_augs/merge_augs.py

Fix https://github.com/open-mmlab/mmdetection/issues/10718
'filp' -> 'flip'

[Fix] misspelling of 'flip'

---

tools/deployment/mmdet2torchserve.py

torch2serve is not working from scratch. You have to add manually the parameter `config_file`. The `model_file` does exist but if I change it to config_file it breaks elsewhere.
I added a parameter config_file in order to be able to run the script

fixed export to torcheserve

---

mmdet/configs/detr/detr_r101_8xb2_500e_coco.py
mmdet/configs/detr/detr_r18_8xb2_500e_coco.py
mmdet/configs/detr/detr_r50_8xb2_150e_coco.py
mmdet/configs/detr/detr_r50_8xb2_500e_coco.py

DETR algorithm config files are added to adapt new version of config.
Based on https://github.com/open-mmlab/OpenMMLabCamp/discussions/604
- Add 4 DETR config python files in mmdet/configs/detr/

[CodeCamp2023-604] Add new configuration files for DETR algorithm in mmdetection

---

mmdet/models/dense_heads/mask2former_head.py
mmdet/models/dense_heads/maskformer_head.py
mmdet/models/layers/msdeformattn_pixel_decoder.py

Refactor  to support torch2onnx for maskformer series
None

Support torch2onnx for maskformer series

---

configs/ddq/README.md
model-index.yml

Refine DDQ README

---

mmdet/models/dense_heads/detr_head.py
mmdet/models/losses/iou_loss.py
mmdet/models/task_modules/assigners/match_cost.py

Support AMP of DINO 

---

demo/inference_demo.ipynb
mmdet/apis/det_inferencer.py
mmdet/configs/rtmdet/rtmdet_ins_l_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_ins_m_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_ins_s_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_ins_tiny_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_ins_x_8xb16_300e_coco.py
mmdet/configs/rtmdet/rtmdet_m_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_tiny_8xb32_300e_coco.py
mmdet/configs/rtmdet/rtmdet_x_8xb32_300e_coco.py

Add new configs of RTMDet
1. Add new configs of RTMDet
2. Modify `DetInferencer` to support the new config
3. Fix a wrong link in `inference_demo.ipynb`

[CodeCamp2023-xxx] Add new configs of RTMDet

---

mmdet/models/layers/__init__.py
mmdet/models/layers/brick_wrappers.py

Add FrozenBN

---

docs/zh_cn/user_guides/tracking_analysis_tools.md
docs/zh_cn/user_guides/tracking_dataset_prepare.md

Translation into Chinese of an English document.
Add `tracking_analysis_tools.md` and `tracking_dataset_prepare.md` under zh_cn\user_guides folder.

[CodeCamp2023-497] Translation into Chinese of an English document.

---

mmdet/models/utils/vlfuse_helper.py

Refine docstring and typehint of `vlfuse_helper.py`
`vlfuse_helper.py`

[CodeCamp2023-499] Refine the docstring and typehint of `vlfuse_helper.py`

---

demo/video_demo.py

Otherwise running it with mmyolo models triggers error, trying to find that module undery mmyolo scope

Setting scope for image reader in video_demo

---

mmdet/models/detectors/deformable_detr.py
mmdet/models/detectors/detr.py
mmdet/models/layers/positional_encoding.py

Update to support torch2onnx for DETR series models

---

README.md
README_zh-CN.md

Add OpenXLab Badge to share official applications, community applications and ecological applications based on MMDetection in the OpenXLab platform.
Added OpenXLab Badge in ReadME（English & Chinese）
If this PR introduces a new feature, it is better to list some use cases here, and …

Add OpenXLab Badge 

---

mmdet/models/layers/transformer/deformable_detr_layers.py
mmdet/models/layers/transformer/detr_layers.py
mmdet/models/layers/transformer/grounding_dino_layers.py

Support checkpoint_wrapper

---

mmdet/models/data_preprocessors/data_preprocessor.py
mmdet/models/data_preprocessors/track_data_preprocessor.py
tests/test_models/test_data_preprocessors/test_data_preprocessor.py

#10722 
Fix the bug and add test

Fix Pad Shape

---

mmdet/configs/maskformer/maskformer_r50_ms_16xb1_75e_coco.py
mmdet/configs/maskformer/maskformer_swin_l_p4_w12_64xb1_ms_300e_coco.py

CodeCamp2023 task 603 transfer old configuration files of MaskFormer to new type.
Add new configs which supports trainning and testing in mmdet/configs/maskformer.

[CodeCamp2023-603]Add new configuration files for MaskFormer algorithm in mmdetection

---

configs/grounding_dino/README.md
configs/grounding_dino/grounding_dino_swin-t_finetune_8xb2_20e_cat.py

Add custom dataset of grounding dino

---

mmdet/models/losses/triplet_loss.py

fix docstring for dimension of targets argument

---

configs/odinw/glip_atss_swin-t_a_fpn_dyhead_pretrain_odinw13.py
configs/odinw/glip_atss_swin-t_a_fpn_dyhead_pretrain_odinw35.py
configs/odinw/override_category.py
docs/zh_cn/user_guides/dataset_prepare.md
mmdet/datasets/base_det_dataset.py
mmdet/datasets/coco.py
mmdet/datasets/dataset_wrappers.py
mmdet/evaluation/__init__.py
mmdet/evaluation/evaluator/__init__.py
mmdet/evaluation/evaluator/multi_datasets_evaluator.py
mmdet/models/detectors/glip.py

Support ODinW and evaluate

---

configs/panoptic_fpn/panoptic-fpn_r50_fpn_1x_coco.py
mmdet/configs/panoptic_fpn/panoptic_fpn_r101_fpn_1x_coco.py
mmdet/configs/panoptic_fpn/panoptic_fpn_r101_fpn_ms_3x_coco.py
mmdet/configs/panoptic_fpn/panoptic_fpn_r50_fpn_ms_3x_coco.py

[MMSIG#357] Add new configs for panoptic_fpn

---

configs/mm_grounding_dino/dataset_prepare.md
configs/mm_grounding_dino/dataset_prepare_zh-CN.md
configs/mm_grounding_dino/usage.md
tools/dataset_converters/grit_processing.py

update English version of md

---

demo/video_demo.py

The video demo doesn't work because of the progress bar bug. It is already a known issue(#11353) so I fixed some code and it works.
`track_iter_progress` requires `tasks` and it needs to be `Sequence`. So I made it `Sequence`.
If so, please describe how it breaks the …

[Bug Fix] video_demo bug fixed for issue#11353

---

mmdet/models/layers/ema.py

use `lerp` in ema

---

mmdet/datasets/transforms/text_transformers.py

mm_grounding_dino 的预训练代码中RandomSamplingNegPos可能存在问题，valid_negative_indexes中元素类型是str，而positive_label_list中类型是int，这可能导致在加入负样本词汇时，将正样本词汇重复添加
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …

fix:grounding_pretrain_text_trans_negative_label
