open-mmlab/mmdetection

- mmdet/datasets/coco.py
The `loadImgs` and `getAnnIds` in `pycocotools` expect a list of ids or single int id. They will treat single string id as list of ids. Always passing a list will work.
> Add support for string ids for COCO dataset

- INSTALL.md
- mmdet/core/loss/losses.py
- mmdet/ops/roi_align/functions/roi_align.py
- mmdet/ops/roi_align/src/roi_align_cuda.cpp
- mmdet/ops/roi_align/src/roi_align_kernel.cu
- mmdet/ops/roi_pool/functions/roi_pool.py
- mmdet/ops/roi_pool/src/roi_pool_cuda.cpp
- mmdet/ops/roi_pool/src/roi_pool_kernel.cu
This PR solves #155. In fact, this repo can support PyTorch 1.0 without any changes. Only some minor changes are needed for [mmcv](https://github.com/open-mmlab/mmcv).
We made some minor updates though.
- Support half tensors (fp16) for roi_align and roi_pooling.
- Remove some legacy code.
You need to use the pytorch-1.0 branch of mmcv with this PR. After the branch being merged, mmcv will be updated to v0.2.2.
The results are shown in the below table.
|                    | PyTorch 0.4.1 | PyTorch 1.0.0 |
|--------------------|---------------|---------------|
| RPN                | 57.1          | 57.0          |
| Faster R-CNN       | 36.4          | 36.5          |
| Mask R-CNN         | 37.3 / 34.2     | 37.3 / 34.2     |
| RetinaNet          | 35.6          | 35.7          |
| …
> Upgrade to PyTorch 1.0

- mmdet/core/bbox/assigners/max_iou_assigner.py
This PR leads to about 0.02s speedup per iteration.
> transpose the IoU matrix for speedup

- mmdet/datasets/transforms.py
In the original [BboxTransform](https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/mmdet/datasets/transforms.py#L79), the bbox is clipped to `[0, w]` and `[0, h]` instead of `[0, w-1]` and `[0, h-1]`. if the ground truth bbox is annotated incorrectly with `w` and `h` in the coordinates which I occur in a text detection dataset, there is the case that the generated proposal is on the border of image with `x=w` or `y=h`, this can cause error when get target mask in [this line](https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/mmdet/core/mask/mask_target.py#L29) for Mask RCNN。
> modify the range of bbox in BboxTransform

- mmdet/datasets/custom.py
- `value`: randomly select a scale from [a, b, ...]
- `range`: randomly generate a scale between [a, b]
> allow specifying multi-scale random mode

- README.md
- mmdet/apis/inference.py
I find it's the best way to modify `mmdet/apis/inference.py`, to add the existing mask visualization part into it. Also, since I am using remote servers to run my model, I think most of us do in this way, so I set the `show = False` and add an interface `out_file`.
I'm not sure if it's appropriate to directly pull a request, and sorry to post two boring issues to talk about these. Or maybe you can adopt these changes by next time commit.
> Added mask visualization part to inference part and add out_file interface.

- mmdet/models/necks/fpn.py
If `extra_convs_on_inputs` is True (by default), then P6 is built upon C5, which is the same as the official implementation, otherwise P6 is built upon P5, as in FCOS.
> Add an argument in FPN to support building P6 from either C5 or P5

- compile.sh
- mmdet/core/anchor/anchor_target.py
- mmdet/core/loss/__init__.py
- mmdet/core/loss/losses.py
- mmdet/models/anchor_heads/anchor_head.py
- mmdet/ops/__init__.py
- mmdet/ops/sigmoid_focal_loss/__init__.py
- mmdet/ops/sigmoid_focal_loss/functions/sigmoid_focal_loss.py
- mmdet/ops/sigmoid_focal_loss/modules/sigmoid_focal_loss.py
- mmdet/ops/sigmoid_focal_loss/setup.py
- mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss.cpp
- mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu
The cpp_sigmoid_focal_loss extension is modified from maskrcnn-benchmark and adapt to mmdetection. Compared with original python implementation, speed is faster and memory usage is lower.
| Retinanet R50 FPN     | Mem (GB) | Time (iter/s) |
|-----------------------|----------|---------------|
| Python implementation | 5.0      | 0.374         |
| Cpp implementation    | 3.6      | 0.356         |
> add cpp sigmoid focal loss

- mmdet/ops/dcn/src/deform_conv_cuda.cpp
Pytorch-nightly is faster than pytorch-1.0.1
| Model                             | Mem (GB) | Time (iter/s) |
|-----------------------------------|----------|---------------|
| Mask R50 FPN pytorch-1.0.1        | 4.0      | 0.542         |
| Mask R50 FPN pytorch-nightly      | 3.9      | 0.520         |
| Retinanet R50 FPN pytorch-1.0.1   | 5.0      | 0.374         |
| Retinanet R50 FPN pytorch-nightly | 4.8      | 0.328         |
> fix dcn to support pytorch-nightly

- mmdet/core/bbox/bbox_target.py
- mmdet/models/bbox_heads/bbox_head.py
| Model            | Mem (GB) | Time (iter/s) |
|------------------|----------|---------------|
| Mask R50 FPN ori | 4.0      | 0.542         |
| Mask R50 FPN new | 4.0      | 0.468         |
> remove expand loop in bbox head to speed up

- mmdet/ops/dcn/modules/deform_conv.py
Fixed error `TypeError: super(type, obj): obj must be an instance or subtype of type `
> Fix error at `DeformConvPack` module

- README.md
- configs/gn+ws/README.md
- configs/gn+ws/faster_rcnn_r50_fpn_gn_ws_1x.py
- configs/gn+ws/mask_rcnn_r50_fpn_gn_ws_20_23_24e.py
- configs/gn+ws/mask_rcnn_r50_fpn_gn_ws_2x.py
- configs/gn+ws/mask_rcnn_x101_32x4d_fpn_gn_ws_2x.py
- mmdet/models/backbones/resnet.py
- mmdet/models/backbones/resnext.py
- mmdet/models/bbox_heads/convfc_bbox_head.py
- mmdet/models/mask_heads/fcn_mask_head.py
- mmdet/models/mask_heads/fused_semantic_head.py
- mmdet/models/mask_heads/htc_mask_head.py
- mmdet/models/necks/fpn.py
- mmdet/models/utils/__init__.py
- mmdet/models/utils/conv_module.py
- mmdet/models/utils/conv_ws.py
| model              | backbone | norm     | lr schd | box AP | mask AP |
|---------------|-----------|---------|--------|--------|----------|
| Faster R-CNN | R-50         | GN         | 1x         | 37.8      |                 |
| Faster R-CNN | R-50         | GN+WS | 1x         | 38.9      |                 |
| Faster R-CNN | R-101        | GN         | 1x         | 39.8      |                 |
| Faster R-CNN | R-101        | GN+WS | 1x         | 41.4      |                 |
| Faster R-CNN | X-50-32x4d | GN         | 1x         | 36.5     |                 |
| Faster R-CNN | X-50-32x4d | GN+WS | 1x         | 39.9     |                 |
| Faster R-CNN | X-101-32x4d | GN         | 1x         | 33.2     |                 |
| Faster R-CNN | X-101-32x4d | GN+WS | 1x         | 41.8     | …
> Add support for weight standardization

- mmdet/models/backbones/resnet.py
If BN is not fixed and `froze_stages` is not -1, BN layers in the first stages will run in the training mode.
> Bug fix for freezing BN parameters

- MODEL_ZOO.md
- mmdet/models/anchor_heads/retina_head.py
- tools/upgrade_model_version.py
This is a breaking change for RetinaNet, and previously trained models are not compatible with latest codes. Thus we provide an upgrading tool to convert old models to the latest version.
> Support normalization layers in RetinaHead

- GETTING_STARTED.md
- mmdet/datasets/loader/build_loader.py
- mmdet/datasets/loader/sampler.py
- tools/dist_test.sh
- tools/slurm_test.sh
- tools/test.py
Difference from the implementation of `mmcv.runner.parallel_test`:
- The new implementation uses mmddp, and there can only be one process on each gpu, while `parallel_test` supports multiple processes per gpu.
- The speed and gpu usage is much higher than `parallel_test`.
This PR is also related to #577. SyncBN cannot work with original `parallel_test` but should work well with mmddp.
> Rewrite multigpu testing with mmddp

- configs/cascade_mask_rcnn_r50_c4_1x.py
- configs/cascade_rcnn_r50_c4_1x.py
- configs/fast_rcnn_r50_c4_1x.py
- configs/faster_rcnn_r50_c4_1x.py
- configs/gn+ws/faster_rcnn_r50_fpn_gn_ws_1x.py
- configs/gn+ws/mask_rcnn_r50_fpn_gn_ws_20_23_24e.py
- configs/gn+ws/mask_rcnn_r50_fpn_gn_ws_2x.py
- configs/gn+ws/mask_rcnn_x101_32x4d_fpn_gn_ws_2x.py
- configs/gn/mask_rcnn_r101_fpn_gn_2x.py
- configs/gn/mask_rcnn_r50_fpn_gn_2x.py
- configs/gn/mask_rcnn_r50_fpn_gn_contrib_2x.py
- configs/mask_rcnn_r50_c4_1x.py
- configs/rpn_r50_c4_1x.py
- mmdet/models/anchor_heads/retina_head.py
- mmdet/models/backbones/resnet.py
- mmdet/models/backbones/resnext.py
- mmdet/models/bbox_heads/convfc_bbox_head.py
- mmdet/models/mask_heads/fcn_mask_head.py
- mmdet/models/mask_heads/fused_semantic_head.py
- mmdet/models/mask_heads/htc_mask_head.py
- mmdet/models/necks/fpn.py
- mmdet/models/shared_heads/res_layer.py
- mmdet/models/utils/conv_module.py
To be consistent with `conv_cfg`, just rename `normalize` to `norm_cfg`.
> Rename normalize to norm_cfg

- mmdet/models/backbones/resnet.py
With the latest code, resuming from a checkpoint trained before #637 (yesterday) will leads to a shape mismatch because the order of parameters are changed. I just change it back for backward compatibility.
> Bug fix for backward compatibility of parameter order

- mmdet/models/anchor_heads/guided_anchor_head.py
`multi_apply` is applicable when the method has multiple return values, i.e., returns a tuple. `loss_loc_single` and `loss_shape_single` only return a single value, using `multi_apply` will lead to a bug. Currently the returned loss is 1-d instead of 0-d, so that the bug is not triggered, but the behavior is dangerous.
> Potential bug fix for GuidedAnchorHead

- tools/test.py
It will waste a lot time to inference but do nothing if we didn't assign an operation
I did several times :joy:
> Require an operation(Save or Show the results) when testing

- mmdet/core/evaluation/eval_hooks.py
There will be errors occur when validating if the output gives zero detection bounding boxes. This PR simply add exceptions handling to avoid errors.
> Add exceptions handling while validating

- tools/train.py
Add an option to use the linear scaling rule to automatically scale the learning rate when more or less than 8 gpus are used.
Results [box AP] on coco val2017:
1 GPU: 36.3
2 GPUs: 36.5
4 GPUs: 36.5
8 GPUs: 36.4
> Add option to use linear scaling rule

- mmdet/apis/train.py
- mmdet/core/evaluation/eval_hooks.py
- mmdet/datasets/builder.py
This is to use the registry for preparing the validation datasets instead of the mmdet.datasets module directly. Fixes #1057
> Added Registry use for validation datasets (distributed)

- mmdet/core/anchor/anchor_target.py
``Bool`` type has been separated from ``Byte`` in pytorch. ``valid_flags`` is in ``Byte`` type but arithmetic comparisons return ``Bool``, which causes error under current pytorch version.
To keep compatible across pytorch versions, we have to manually add the type promotion.
(pytorch has always been conservative in automatic type conversion, even if there is an issue [there](https://github.com/pytorch/pytorch/issues/23758), I believe they will not add the type promotion)
> manually add type promotion

- mmdet/datasets/builder.py
Solve above situations:
1. using different type of dataset for training
```
data = dict(
train=(
dict(
type='XxDataset',
params=...,
),
dict(
type='YyDataset',
params=...,
)))
```
2、same type of dataset, but different parameters
```
data = dict(
train=(
dict(
type='XxDataset',
params=P1,
),
dict(
type='XxDataset',
params=P2,
)))
```
> Support different type of dataset for training

- mmdet/apis/train.py
- tools/train.py
This is to allow the use of more than one dataset in the train api so that validation sets can be used to track validation loss. 
Relevant issues:
#171
#364
#271
> Allowing validation dataset for computing validation loss

- tools/voc_eval.py
Fix for issue #1236. If list `gt_ignore` was empty, it should become `None` after the following if statement:
```
if not gt_ignore:
gt_ignore = gt_ignore
```
otherwise, the `eval_map` function throws an `AssertionError`.
Changed it to `gt_ignore = None`.
> Fix for gt_ignore

- docker/Dockerfile
Hi! Here is my suggestion about optimizing Dockerfile. Some tarballs and other cache files may not be re-used so that we could choose to clean them up during image building process. I hope that these suggestion could assist in reducing the image size as you may add more commands here in the future.
*Reference:*
* https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
* https://docs.conda.io/projects/conda/en/latest/commands/clean.html
* https://pip.pypa.io/en/stable/reference/pip_install/
* https://stackoverflow.com/questions/45594707/what-is-pips-no-cache-dir-good-for/45594808
> Optimize Dockerfile

- mmdet/ops/dcn/src/deform_conv_cuda.cpp
- mmdet/ops/dcn/src/deform_pool_cuda.cpp
Currently, deform_conv only works for `cuda:0`
```python
from ops.dcn.deform_conv import DeformConv, deform_conv
device = "cuda:0"
out = deform_conv(x, offset, weight, 1, [1, 1], 1, 2, 2)
print(out.mean(), out.var())
device = "cuda:1"
out = deform_conv(x, offset, weight, 1, [1, 1], 1, 2, 2)
print(out.mean(), out.var())
```
The patch aims to fix the issue.
> [DeformConv] Fix zero outputs when not running on cuda:0

- mmdet/models/detectors/cascade_rcnn.py
- mmdet/models/detectors/htc.py
|    Backbone     |  Test method  | Lr schd | Mem (GB) | Train time (s/iter) | Inf time (fps) | box AP | mask AP |                                                            Download                                                             |
| :-------------: | :-----: | :-----: | :------: | :-----------------: | :------------: | :----: | :-----: | :-----------------------------------------------------------------------------------------------------------------------------: |
|    R-50-FPN     | Orign repo |   1x    |   5.3    |        0.683        |      7.4       |  41.2  |  35.7   |     [model](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/cascade_mask_rcnn_r50_fpn_1x_20181123-88b170c9.pth)  
|   R-50-FPN    | TTA(hflip)        |   |   |   |   | 41.9 | 36.2 | …
> Add tta to HTC and Cascade RCNN

- mmdet/core/evaluation/coco_utils.py
Commit 8d010d7de9c2643e715aaf6033ff7fd5c60ebdc2 added a change where seg would be checked to have a length of 2 (denoting it was a different detector result). When a dataset has two classes this breaks, so this PR simply adds an additional check to ensure in the event the dataset has two classes the script doesn't break. Also ensures the segms counts has the decode method.
> Fixed coco_eval bug where seg length check could be wrong (#1376)

- tools/test_robustness.py
The way it was set up the `main` function in `test_robustness.py` would not use the copy of the config into which the corruption was inserted but the original config without the corruption. This should fix it.
> Fix robustness data pipeline

- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/guided_anchor_head.py
When using CascadeRNN on the CPU, running forward with `return_loss=False` was raising an error in `anchor_head.AnchorHead.get_bboxes` because AnchorGenerator `grid_anchors` defaults to a cuda device. 
I modified the code to pass whichever device the features were currently using to the relevant functions. 
Unlike my other PRs, this one is standalone, so it should be easy to review.
> FIX: Pass device to grid_anchors and valid_flags

- .travis.yml
- mmdet/models/bbox_heads/convfc_bbox_head.py
- mmdet/models/bbox_heads/double_bbox_head.py
- mmdet/models/losses/utils.py
- mmdet/models/mask_heads/fused_semantic_head.py
- pytest.ini
- setup.py
- tests/requirements.txt
This PR enables doctests in in pytest. Instead of using the builtin doctest module I used xdoctest, which has pytest integration by default. I also mentioned [xdoctest](https://github.com/Erotemic/xdoctest)  in #1474.
The main benefit of xdoctest over buildin-doctest is you can prefix normal code with `>>> ` and the doctest will just work. In the old-style you would have to prefix certain lines with `>>> ` and other lines with `... `. Hopefully this helps the maintainers write more doctests, which can be both illustrative for newcomers to this library and practical for ensuring the integrity of the library. 
You may have noticed that the doctest in `mmdetection/mmdet/models/losses/utils.py` wasn't working. This is because the builtin doctest module has a very restrictive syntax (which …
> Enable doctests in CI with xdoctest

- mmdet/models/backbones/resnet.py
- mmdet/models/backbones/resnext.py
When I'm trying to learn a library it helps to be able to get into the code and start stepping through it.  Doctest examples help with this a lot. 
As a side note: you may want to consider using [xdoctest](https://github.com/Erotemic/xdoctest) instead of Python's builtin doctest module in CI testing. Full disclosure: I wrote xdoctest, so I may be biased, but I do believe it offers a better features and syntax and makes it easier to write and debug doctests in general.
> Add two doctest examples for resnet and resnext

- mmdet/models/backbones/hrnet.py
- mmdet/models/backbones/resnet.py
- mmdet/models/backbones/resnext.py
- mmdet/models/backbones/ssd_vgg.py
I added `in_channels` argument to the backbones. Previously they were hard coded to 3, which makes sense for most RGB problems. However, this makes it a pain to use when your input is grayscale or 4 channel RGBA. Adding this as an option makes mmdet a bit more usable in these situations. 
Of course the pretrained weights don't quite fit, but fortunately the existing system handles this well and simply outputs a warning message that a particular layer doesn't fit right (:tada: thanks for implementing that nicely!). 
I've added documentation in the `Args` block for each  case. I also added a docstring example because the HRNet backbone was unclear about how it should be used from the module itself (I think its nice when modules are self-documenting).  
Note, that I was only able to add …
> Add in_channels kwarg to backbones. 

- mmdet/core/anchor/anchor_generator.py
- mmdet/core/bbox/transforms.py
- mmdet/core/post_processing/bbox_nms.py
- mmdet/models/anchor_heads/anchor_head.py
Adding more doctests as I continue to learn more about the code. 
My main effort here was to learn about how the background class is handled in detectors. I discovered that num_classes must include the background class, but the network itself only represents the background class if softmax is used. If sigmoid is used, the number of output channels is actually one less than the background class. Something that I found weird is that when the background class actually receives a score from the network it is the first output channel, not the last. This means that there has to be logic that pads the network scores when sigmoid is used and then 1 has to be subtracted from the class indices after the max is found in order to be consistent. I guess this makes some sense when adding new classes …
> Doctests for AnchorHead and related code

- mmdet/core/post_processing/merge_augs.py
- mmdet/datasets/pipelines/formating.py
- mmdet/models/detectors/base.py
- mmdet/models/detectors/cascade_rcnn.py
- mmdet/models/detectors/single_stage.py
- mmdet/models/detectors/two_stage.py
I'm attempting to learn how to use the infrastructure of this module independent of its training loop and configuration logic. While I'm sure they are nice for internal research, as an external researcher, I really want to be able to construct raw instances of these classes and use them in my own training / inference / configuration system.  Fortunately, this library has a well thought out architecture that makes this possible, but the docs are a bit lacking. 
As I'm understanding more about what each network expects I'm adding documentation as best as I can. Hopefully this will be beneficial to both the maintainers and other researchers who use this library. 
Note that even though this is mostly a documentation PR, this does contain one small bugfix. In cascade_rcnn.py simple_test, the …
> Expand docstring docs

- mmdet/models/detectors/cascade_rcnn.py
- mmdet/models/detectors/two_stage.py
This PR switches the remaining instances of B,C,H,W to N,C,H,W to standardize batch shape notation as discussed in #1491.
> Use standard NCHW instead of BCHW

- .travis.yml
freeze PyTorch version 1.2 since compilation with the 1.3 on Travis CI fails with following error:
```
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:50
```
see https://travis-ci.org/Borda/mmdetection/jobs/596941932
> Travis: build freeze PyTorch 1.2

- mmdet/models/plugins/non_local.py
According to [the original implementation of non-local](https://github.com/facebookresearch/video-nonlocal-net/blob/c253ed5eb004fa2cae0490ed46f5018a3c3b060f/lib/models/nonlocal_helper.py#L86), the correct formula of "Scaled Dot-Product Attention" should be
> fix a scale bug according to the Non-local papaer

- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/guided_anchor_head.py
- tests/test_config.py
Based on the conversation in #1491 
While AnchorHead and GuidedAnchorHead are base classes, the meaning of the `in_channels` and `feat_channels` parameters were confusing. This PR makes `in_channels` and `feat_channels` consistent with the rest of the code base. `in_channels` now marks the number of input channels to the nn.module as expected, and `feat_channels` is documented as the number of hidden channels. 
As a check to make sure this change didn't break anything I added a test that loads all configs from the config directory and attempts to call `build_detector`. This test is a bit slow (it takes about 2 minutes), but it guarantees that changes like this don't break the `__init__` for any detector component. It might be a good idea to just pick a subset of configs to test because …
> Fix AnchorHead in_channels

- mmdet/datasets/custom.py
- mmdet/datasets/pipelines/loading.py
CustomDataset sets this img_prefix variable to None unless set. Without this fix, when using CustomDataset with it's defaults I get the below error. An alternative fix would be to, in the CustomDataset init function,  set the default value to empty string '' instead of None
what():  TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/run/media/matt/Storage/Dev/viame/build/install/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/run/media/matt/Storage/Dev/viame/build/install/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File …
> Fix issues with default 'img_prefix' value set to None when training

- docker/Dockerfile
Issue https://github.com/open-mmlab/mmdetection/issues/1591
1. Dockefile updated to Pytorch 1.3 and cuda 10.1
2. CUDNN downgraded from 7 to 7.5. There is no pytorch docker image for pytorch 1.3 and cudnn 7.5
3. Extra lines with environmental variables added. Without them the build breaks.
> Dockerfile updated to Pytorch 1.3

- mmdet/datasets/loader/sampler.py
When `num_extra < len(indice)`, `len(indice[:num_extra]) != num_extra`, 
```
assert len(indices) == self.num_samples  # line 70
```
will arise error.
So , I modified as follows.
```
indice = np.concatenate([indice, indice[:num_extra]])
```
to 
```
indice = np.concatenate([indice, np.random.choice(indice,num_extra)])
```
> Fix Sampler bug: index out of range when num_extra < len(indice)

- mmdet/ops/nms/nms_wrapper.py
- mmdet/ops/nms/src/nms_kernel.cu
- tests/test_nms.py
I added doctests and unit tests for non-max suppression code. These tests were written to debug an error I'm experiencing. Unfortunately they will not manifest on TravisCI because reproducing the issue requires having at least 2 GPUs. 
The issue is that I get `RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at mmdet/ops/nms/src/nms_kernel.cu:103` when I try to run NMS with a Tensor on any device except CPU or 0. The error happens on this line: 
```c++
THCudaCheck(cudaMemcpy(&mask_host[0],
mask_dev,
sizeof(unsigned long long) * boxes_num * col_blocks,
cudaMemcpyDeviceToHost));
```
But I believe the issue is actually here: 
```c++
THCState *state = at::globalContext().lazyInitCUDA(); // TODO replace with getTHCState
unsigned long long* mask_dev = NULL; …
```
> Add tests for NMS / Issue with NMS on GPU 1. 

- mmdet/models/detectors/base.py
- mmdet/models/detectors/fast_rcnn.py
- tests/test_forward.py
As discussed in #1477, there is an issue with the way `forward_test` calls `simple_test` when num_augs is 1. Previously the line was  `self.simple_test(imgs[0], img_metas[0], **kwargs)`, which passes img_metas in as a `dict` and not a `list[dict]`. It results in this error:
```python
~/code/mmdetection/mmdet/models/detectors/base.py in forward_test(self, imgs, img_metas, **kwargs)
92         if num_augs == 1:
93             # return self.simple_test(imgs[0], img_metas[0:1], **kwargs)
---> 94             return self.simple_test(imgs[0], img_metas[0], **kwargs)
95         else:
96             return self.aug_test(imgs, img_metas, **kwargs)
~/code/mmdetection/mmdet/models/detectors/rpn.py in simple_test(self, img, img_meta, rescale)
62     def simple_test(self, img, img_meta, rescale=False): …
```
> Pass img_meta as list to simple_test

- mmdet/core/evaluation/coco_utils.py
This PR related to #1672 that the mAP w.r.t. object scales has been changed after some code refactoring. I think it is important, especially for publications since reviewers may ask about abnormal performance changes.
|      Model     | AP   | AP50 | AP75 | APS  | APM  | APL  |
|:--------------:|------|------|------|------|------|------|
| HTC from paper | 38.0 | 59.4 | 40.7 | 20.3 | 40.9 | 52.3 |
| Before fix     | 38.1 | 59.4 | 41.0 | 17.9 | 40.7 | 56.6 |
| After fix      | 38.1 | 59.4 | 41.0 | 20.3 | 41.1 | 52.8 |
The bug stems from commit [#976629](https://github.com/open-mmlab/mmdetection/commit/976629d4e604f07280eb621b8fc7e6023fc94a90) which separates the results into independent files for ``bbox`` and ``segm``. However, the segmentation results do not have ``bbox`` field which …
> fix mAP w.r.t. object scales

- mmdet/datasets/loader/build_loader.py
shuffle=True is now a function argument. when passed as kwargs, it was crashing function in the non distributed case. so now shuffle does what we want, if True we use the different group sampler, if False (should not be used for training, only for debugging purposes), the data is always fed in the same order. 
reference issue: https://github.com/open-mmlab/mmdetection/issues/1649
> shuffle passed as function argument instead of kwargs

- mmdet/ops/dcn/src/deform_conv_cuda_kernel.cu
Change pad_d to pad_w at line 821 in deform_conv_cuda_kernel.cu, which is a typo.
> Fix a typo in deform_conv_cuda_kernel.cu

- mmdet/models/bbox_heads/bbox_head.py
- mmdet/models/detectors/test_mixins.py
- mmdet/models/mask_heads/fcn_mask_head.py
Fix https://github.com/open-mmlab/mmdetection/issues/1673,
Using the mask r50 from [model zoo](https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md) and setting `keep_ratio=False` could obtain 34.3 mask mAP.
> fix scale factor bug

- mmdet/datasets/pipelines/loading.py
Since proposals of an image should be a [k, 4] or [k, 5] tensor, the dummy proposals ought to have the same number of dimensions as well.
> Fix loader for images with no proposals

- docs/GETTING_STARTED.md
- mmdet/apis/__init__.py
- mmdet/apis/inference.py
- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/rpn_head.py
- mmdet/models/bbox_heads/bbox_head.py
- mmdet/models/detectors/base.py
- mmdet/models/detectors/test_mixins.py
- mmdet/models/detectors/two_stage.py
- mmdet/ops/dcn/src/deform_conv_cuda_kernel.cu
- mmdet/ops/dcn/src/deform_pool_cuda_kernel.cu
- mmdet/ops/masked_conv/src/masked_conv2d_kernel.cu
- mmdet/ops/nms/src/nms_kernel.cu
- mmdet/ops/roi_align/src/roi_align_cuda.cpp
- mmdet/ops/roi_align/src/roi_align_kernel.cu
- mmdet/ops/roi_pool/src/roi_pool_kernel.cu
- mmdet/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu
- mmdet/utils/contextmanagers.py
- mmdet/utils/profiling.py
- setup.py
- tests/async_benchmark.py
- tests/requirements.txt
- tests/test_async.py
This PR adds async inference interface implemented for two stage detector with RPN head.
Concurrency is supported by two async context managers:
1. `completed` allows to switch execution context during GPU bound computations like convolutions. CUDA stream is restored when the context is switched back.
2. `concurrent` makes it possible to execute block of code concurrently in a dedicated pool of CUDA streams. The pool is constructed and passed via `asyncio.Queue`. It's an alternative to tensor-level batch inference.
I've tested this implementation on my current project that uses single thread for inference. Async variant has ~30% higher throughput than blocking one but the GPU is still underutilized and there is a room for improvement.
Concurrency can be increased by using …
> Async inference interface

- .travis.yml
- mmdet/core/bbox/demodata.py
- mmdet/models/bbox_heads/bbox_head.py
- tests/requirements.txt
- tests/test_heads.py
The `BBoxHead.refine_boxes` function was failing in cases where there is only a single roi in an image. When this happened the `squeeze` function removed all dimensions of the tensor and it became a scalar. This caused issues when trying to index into the `rois` tensor because it did not keep its two dimensional shape and that cause an assertion to fail in `regress_by_class`. 
This issue is fixed by specifying that we are squeezing over dimension 1. This prevents the 0-th dimension from collapsing and guarantees that `rois` keeps its 2d shape. 
Also while I was in this function I noticed the assertion: 
```python
img_ids = rois[:, 0].long().unique(sorted=True)
assert img_ids.numel() == len(img_metas)
``` 
this will fail if in the corner case where an image doesn't have an roi. Changing …
> Fix issue in refine_bboxes and add doctest

- mmdet/apis/train.py
fix a bug for distributed training in windows platform
in windows, pytorch 1.2, the dist.is_available() is False, it means the distributed training is not support in pytorch 1.2, so dist.is_initialized() could not be called
> bug for distributed training

- mmdet/utils/registry.py
modified:   mmdet/utils/registry.py
Add ability to replace existing module with a new one.
The aim is to facilitate ad-hoc testing of new modules and use of external modules.
> Add ability to overwite existing module in Registry

- mmdet/datasets/pipelines/formating.py
- mmdet/datasets/pipelines/loading.py
- mmdet/datasets/pipelines/transforms.py
- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/guided_anchor_head.py
- mmdet/models/anchor_heads/reppoints_head.py
Hi, 
Thank you for great project. This pull request adds ability to load images that are not 3 channel color images. Since opencv treats 'grayscale' images as 2D matrices an empty third dimension have to be added before converting them to tensors.
> Non color images

- .travis.yml
- docs/INSTALL.md
- mmdet/datasets/pipelines/transforms.py
- requirements.txt
- requirements/build.txt
- requirements/optional.txt
- requirements/runtime.txt
- requirements/tests.txt
- setup.py
The albumentations requires an old version of the `imgaug` library, which is incompatible with a lot of other software stacks (namely the one I'm using) which uses the latest `imgaug` library. 
It looks like `albumentations` is not tightly coupled with the system and mmdet can work just fine if it isn't installed. Therefore I'd like to propose to make it an optional requirement instead of a forced requirement. 
This PR does that and also reorganizes the requirements into a format that should be easier to use. Namely, requirements are broken down by what they are required for (e.g. runtime, tests, build, and options) and they all live in a `requirements` folder now. The base requirements.txt file uses the `-r` syntax to refer to each of those files, so `pip install -r requirements.txt` …
> Reorganize requirements, make albumentations optional

- mmdet/core/bbox/assigners/assign_result.py
- mmdet/core/bbox/samplers/base_sampler.py
- mmdet/core/bbox/samplers/random_sampler.py
- mmdet/core/bbox/samplers/sampling_result.py
- mmdet/utils/util_mixins.py
- tests/test_assigner.py
- tests/test_sampler.py
These allow for the simple creation of "demo data" that can be use for testing, debugging, and potentially more (although I don't think these are as useful as random boxes might be). 
I've been hitting issues where sometimes `gt_bboxes` looks like its had its dimensions squashed. This causes an error when doing the index selection. Adding two checks fixes it. 
To ensure that the new random methods could be seeded to consistently reproduce an issue if needed, I had to ensure that the `RandomSampler` class could be seeded. I used `ensure_rng`, which I added in a previous PR to accomplish this simplify. 
I also added a `to` function to `SamplingResult`, where it moves the data onto a different device. I wrote this to test something that turned out not to be an issue, but I figure its a nice …
> Enhance AssignResult and SamplingResult

- mmdet/models/mask_heads/fcn_mask_head.py
This PR adds two more options for test config (see the example bellow).
```
test_cfg = dict(
rpn=dict(
...
),
rcnn=dict(
score_thr=0.05,
nms=dict(type="nms", iou_thr=0.5),
max_per_img=100,
mask_thr_binary=0.5,
no_test_rle=True, # (1)
box_rel_masks=True, # (2)
),
)
```
1. Allows one to disable costly RLE when you need raw binary masks for some postprocessing tricks
2. Since `no_test_rle` is applied you'll recieve N(=number of boxes) binary masks in fullres. In order to decrease memory usage option `box_rel_masks` allows you to get mask with the position inside an appropriate bbox.
Both are optional and disabled by default.
> options for FCNMaskHead during testtime

- .travis.yml
- docs/INSTALL.md
- requirements/runtime.txt
```python
np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
```
will raise a TypeError.
> Fix the incompatibility of the latest numpy and pycocotools

- configs/hrnet/htc_hrnetv2p_w32_20e.py
- configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py
- configs/htc/htc_r101_fpn_20e.py
- configs/htc/htc_r50_fpn_1x.py
- configs/htc/htc_r50_fpn_20e.py
- configs/htc/htc_without_semantic_r50_fpn_1x.py
- configs/htc/htc_x101_32x4d_fpn_20e_16gpu.py
- configs/htc/htc_x101_64x4d_fpn_20e_16gpu.py
- mmdet/apis/train.py
- mmdet/core/utils/dist_utils.py
- mmdet/models/anchor_heads/atss_head.py
- mmdet/models/detectors/htc.py
- mmdet/models/mask_heads/htc_mask_head.py
- requirements/runtime.txt
Re-implement MMDDP with official DDP, which can speed up the training with little extra memory.
https://github.com/open-mmlab/mmcv/pull/184
| Model            | DDP | Mem (MB) | Train time (s/iter) | AP |
| ---------------- | --- | -------- | ------------------- | -- |
| Faster R-CNN R50 | Ori | 3793        |  0.379                   |  36.4  |
| Faster R-CNN R50 | New |  3951     | 0.354                    | 36.4   |
> Use official DDP to implement MMDDP

- mmdet/core/bbox/samplers/random_sampler.py
This pr reimplements `random_choice` with `torch.randperm`. 
It speeds up [libra faster r50](https://github.com/open-mmlab/mmdetection/blob/master/configs/libra_rcnn/libra_faster_rcnn_r50_fpn_1x.py) by around 0.02s\iter on TITAN XP.
> Speed up sampler

- tools/train.py
When use workflow [(train, 1), (val, 1)], cfg.data.val will use test_pipeline, it will raise a error. So we change the pipeline manually.
> fix workflow problem

- mmdet/core/evaluation/mean_ap.py
Fix https://github.com/open-mmlab/mmdetection/issues/2115.
> Fix (get_cls_results): use np.empty for empty bbox rather than np.arrary

- mmdet/datasets/custom.py
modified:   mmdet/datasets/custom.py
> Fix issue with list of metrics in CustomDataset.evaluate

- mmdet/core/bbox/assigners/approx_max_iou_assigner.py
- mmdet/core/bbox/assigners/max_iou_assigner.py
- tests/test_assigner.py
When ignore_of_thr is enabled and there are no predicted bboxes, the `.max` function fails because the `ignore_overlaps` tensor is empty. The error is as follows:
```
~/code/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py in assign(self, bboxes, gt_bboxes, gt_bboxes_ignore, gt_labels)
104                 ignore_overlaps = bbox_overlaps(
105                     bboxes, gt_bboxes_ignore, mode='iof')
--> 106                 ignore_max_overlaps, _ = ignore_overlaps.max(dim=1)
107             else:
108                 ignore_overlaps = bbox_overlaps(
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```
This can be fixed by simply checking that bboxes isn't empty before running the code. I've added this fix …
> Fix IOU assigners when ignore_of_thr > 0 and no pred boxes

- docs/GETTING_STARTED.md
Need to specify --format-only rather than --out in order to actually get .json output
> Fix a documentation error in GETTING_STARTED.md

- mmdet/datasets/builder.py
Tools such as `tools/train.py` that rely on the dataset builder may fail if the Dataset doesn't require an `ann_file` argument. This can be the case with newly defined Dataset types.
> Fix datasets builder

- mmdet/models/necks/fpn.py
Currently the FPN module is broken for certain input sizes due to the assumption that each previous scale will always be 2x as large as the current scale. This is not always the case. In a cascade rcnn model I'm working with the size of each layer in the feature pyramid is: 
```
laterals[0].shape = torch.Size([1, 256, 256, 340])
laterals[1].shape = torch.Size([1, 256, 128, 170])
laterals[2].shape = torch.Size([1, 256, 64, 85])
laterals[3].shape = torch.Size([1, 256, 32, 43])
```
The key difference is that 43 * 2 is not equal to 85. This causes an error:
```python
~/code/mmdetection/mmdet/models/necks/fpn.py in forward(self, inputs)
112         used_backbone_levels = len(laterals)
113         for i in range(used_backbone_levels - 1, 0, -1):
--> 114             laterals[i - 1] += …
```
> Fix FPN upscale

- .isort.cfg
- mmdet/ops/grid_sampler/__init__.py
- mmdet/ops/grid_sampler/grid_sampler.py
- mmdet/ops/grid_sampler/src/cpu/grid_sampler_cpu.cpp
- mmdet/ops/grid_sampler/src/cpu/grid_sampler_cpu.h
- mmdet/ops/grid_sampler/src/cuda/grid_sampler_cuda.cu
- mmdet/ops/grid_sampler/src/cuda/grid_sampler_cuda.cuh
- mmdet/ops/grid_sampler/src/cudnn/grid_sampler_cudnn.cpp
- mmdet/ops/grid_sampler/src/grid_sampler.cpp
- setup.py
This PR adds grid_sampler as an extension operator. 
Specifically, provides `grid_sample(align_corners=False`) when PyTorch version < 1.3.
> add grid sampler

- mmdet/core/fp16/hooks.py
For pip installed pytorch, the version looks like `1.3.1+cu100`.
#2151
> Fix the version comparison for pytorch installed with pip

- mmdet/datasets/loader/build_loader.py
`resource.setrlimit` soft limit cannot exceed hard limit.
See https://docs.python.org/3/library/resource.html#resource.setrlimit
On my system the master branch raises a `ValueError` as the hard limit is lower than 4096.
> Bug fix: Soft limit cannot exceed hard limit

- mmdet/datasets/cityscapes.py
This PR moves `import cityscapesscripts` into functions to avoid unnecessary install.
> fixed cityscapes import

- mmdet/apis/train.py
Allow `find_unused_parameters` to be set in the configuration file. If not present it defaults to the pytorch default of `False`.
This comes in handy when the underlying reason for the unused parameters is hard to find or not resolved well by pytorch. Current way to overcome this is to change `apis/train.py` in a user maintained fork which is not ideal.
This would also be useful for users affected by https://github.com/open-mmlab/mmdetection/issues/2153
> Allow find_unused_parameters to be set in config

- mmdet/apis/inference.py
I notice your comment on the ‘out_file‘ parameter of the show_result function in inference.py: If out_file is specified, the visualization result will be written to the out file instead of shown in a window,  but actually it is shown in windows. (and because I run my python in no gui environment,  even though i specify the out_file, it shows cannot connect to X server, which may be confused to somebody new to this)
So, I add a if statement before show image.
> save file instead of show image in windows

- mmdet/core/post_processing/bbox_nms.py
Reimplement multiclass_nms in a batched fashion.
| Model              | Original Inf time (s/iter) | New Inf time (s/iter) |
|--------------------|----------------------------|-----------------------|
| Faster R-CNN R-50  | 13.7                       | 16.0                  |
| Mask R-CNN R-50    | 9.9                        | 10.9                  |
| Cascade R-CNN R-50 | 11.7                       | 13.7                  |
| Retinanet R-50     | 12.2                       | 16                    |
| FCOS GN R-50       | 13                         | 19.1                  |
| Mask Scoring R-50  | 9.8                        | 10.8                  |
> Add batched nms

- .pre-commit-config.yaml
In the .pre-commit-config.yaml, the path for flake8 could cause 404 error in some machines, add `.git` could avoid this bug.
> Add .git to avoid 404 error

- mmdet/datasets/pipelines/transforms.py
- tests/test_config.py
Fix https://github.com/open-mmlab/mmdetection/issues/2192, https://github.com/open-mmlab/mmdetection/issues/2171.
This PR fixes the bugs in the transformation when the GT box is empty.
A test function `test_config_data_pipeline` is also added to test the cases when GT is empty and test the correct implementation of the data pipeline.
**Notice**: For now, only augmentation used by SSD and mask RCNN is covered, which are two of the most common augmentation pipelines used in the codebase. For pipelines using `albumentations`, the pipeline will throw None if the GT box is empty. We will try to fix this in a new PR.
> Fix (transforms): fix bugs in transforms when the gt is empty

- mmdet/datasets/pipelines/loading.py
The aim of this change is to simplify use of pipelines that do not require image
scaling, normalization, flipping or padding
On branch set_default_metakeys
modified:   mmdet/datasets/pipelines/loading.py
> Set initial values for default meta keys when loading images

- mmdet/datasets/pipelines/loading.py
This class will be usefull for loading a multi-channel image from a list of separate images. This
is often necessary for medical and scientific images, since OpenCV or PIL do not handle correctly
many specialized medical or scientific file formats.
On branch load_multichannel
modified:   mmdet/datasets/pipelines/loading.py
> Add class to load multi-channel images from a list of files

- mmdet/datasets/pipelines/formating.py
This class is useful to create an evaluation pipeline that does not rely on 
MultiScaleFlipAugmentation 
On branch wrap_into_lists
modified:   mmdet/datasets/pipelines/formating.py
> Add class to wrap result fields into lists for evaluation

- mmdet/datasets/pipelines/loading.py
PR https://github.com/open-mmlab/mmdetection/commit/b47348691f87e27e22f24196ecaa7bc3da63351f introduces a bug with random flip augmentation. 
In the implementation of random flip as indicated [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L236), it will only set flip to either True or False when the key `flip` is not in the `result` dictionary. Therefore, after setting `flip=False` in results during the loading process, `flip` in `results` will not be reset according to the flip probability and always be False, and the flip augmentation will never be executed.
**Notice**: since this bug will cause the random flip augmentation ineffective, the performance of models trained after PR …
> Fix (flip): not setting default values of flip during loading

- tests/test_config.py
Rename `_check_roihead` to `_check_roi_head`, `_check_bboxhead` to `_check_bbox_head`, and `_check_maskhead` to `_check_mask_head`.
> Refactor (test_config): rename function names in test_config

- docs/GETTING_STARTED.md
- mmdet/apis/train.py
- mmdet/core/evaluation/__init__.py
- mmdet/core/evaluation/eval_hooks.py
This PR adds support for doing evaluation during single-gpu training, by adding an `EvalHook` and slightly modifying `DistEvalHook` for reusing the code.
> Add support for evaluation in non-dist training

- mmdet/models/backbones/resnet.py
This PR removes the unnecessary initialization of DCN since the conv_offset and weight has been initialized in the DCN modules.
> Refactor (resnet.py): remove unnecessary initialization of dcn

- mmdet/core/optimizer/__init__.py
- mmdet/core/optimizer/builder.py
- mmdet/core/optimizer/default_constructor.py
- mmdet/core/optimizer/registry.py
- tests/test_optimizer.py
This PR allows users to define their own optimizer constructors. Sometimes users want to set different learning rate or and weight decay for different parameters, but the build-in `build_optimizer()` cannot achieve the goal.
> Add optimizer constructor

- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/atss_head.py
- mmdet/models/anchor_heads/fcos_head.py
- mmdet/models/anchor_heads/fovea_head.py
- mmdet/models/anchor_heads/free_anchor_retina_head.py
- mmdet/models/anchor_heads/ga_rpn_head.py
- mmdet/models/anchor_heads/guided_anchor_head.py
- mmdet/models/anchor_heads/reppoints_head.py
- mmdet/models/anchor_heads/rpn_head.py
- mmdet/models/anchor_heads/ssd_head.py
- mmdet/models/detectors/rpn.py
- mmdet/models/detectors/single_stage.py
- mmdet/models/detectors/two_stage.py
- tests/test_heads.py
This PR added `train_cfg` and `test_cfg` as class members in all anchor heads. And it also removed `cfg` in `loss` function.
> Add train_cfg/test_cfg in AnchorHead

- .isort.cfg
- docs/GETTING_STARTED.md
- mmdet/datasets/custom.py
- tests/test_datasets.py
*Changes:*
With the changes stated in this PR, we added the possibility to specify a custom set of classes in the config file and use a dataset format which has already been defined, e.g., Coco dataset format.
In order to make use of these changes, we have to specify the parameter `classes` in the config file (as we have explained in the updated documentation). If `classes` is not specified, then the data loader will use the categories specified in the `self.CLASSES` by default.
*Justification:*
Using this repository, we have run into the need of using our own datasets with custom classes, but we need to use it as a dependency installed in an environment, i.e., access to source code is not feasible.
We also believe that these changes can facilitate the use of custom classes (instead of …
> Support for custom classes

- mmdet/apis/train.py
- tools/train.py
The motivation for this pull request is to simultaneously train different models on the multi-gpu system
with each model trained on separate device (or devices).
modified:   mmdet/apis/train.py
modified:   tools/train.py
> Add ability to specify device ids for non-distributed training

- docs/GETTING_STARTED.md
- tools/analyze_logs.py
- tools/coco_error_analysis.py
- tools/convert_datasets/cityscapes.py
- tools/publish_model.py
- tools/test.py
- tools/train.py
- tools/upgrade_model_version.py
This PR refactors command options in `tools`. It changes the option style from `--xx_xx` to `--xx-xx` for more natural usage.
> Refactor (tools): use '-' rather than '_' for command option

- mmdet/datasets/custom.py
- tests/test_dataset.py
The changes introduced in #2408 were invalidated by the assertion introduced in #2340:
```python
assert set(class_names).issubset(set(cls.CLASSES))
```
This P.R. removes this assertion and adds a test, bringing back the original intention of #2408; which was to allow overriding `CLASSES` in configs, with `CLASSES` being one of:
a)  A subset of default `cls.CLASSES ` 
b) Some classes of a custom dataset annotated in `COCO `format).
> Support custom classes

- mmdet/apis/train.py
I think that the `_dist_train` and `_non_dist_train` functions can be merged in order to reduce duplicate code and avoid potential divergences between the 2 modes.
It might be another reason that I'm not aware of to keep both functions separated  but after #2324 being merged I can't find one.
> Merge non dist and dist train

- configs/_base_/default_runtime.py
- tools/test.py
- tools/train.py
This PR fixed `local_rank` typo and remove `dist_params.port` from `default_runtime.py`
> Fix dist_train

- docs/GETTING_STARTED.md
- mmdet/datasets/coco.py
Showing class-wise mAP could helps users better analyze the model and there are indeed some need according to https://github.com/open-mmlab/mmdetection/issues/2325, https://github.com/open-mmlab/mmdetection/issues/1903, https://github.com/open-mmlab/mmdetection/issues/1526, etc.
This PR adds the class-wise mAP evaluation on the COCO dataset back to the v2.0 branch after the https://github.com/open-mmlab/mmdetection/pull/2042. To use this API, add `--options "classwise=True"` when using the test script or add `classwise=True` in the evaluation config for training-time evaluation.
An example of testing Faster RCNN R50 is as the following picture.
> V2.0 classwise

- mmdet/core/bbox/samplers/ohem_sampler.py
- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/atss_head.py
- mmdet/models/anchor_heads/guided_anchor_head.py
- mmdet/models/anchor_heads/ssd_head.py
- mmdet/models/bbox_heads/bbox_head.py
- mmdet/models/losses/iou_loss.py
- mmdet/models/roi_heads/cascade_roi_head.py
- mmdet/models/roi_heads/htc_roi_head.py
- mmdet/models/roi_heads/standard_roi_head.py
- tests/test_heads.py
This PR unified the regression loss in `bbox_head`. 
Attribute `reg_delta_target = True` indicates the regression target is the delta between prediction and target, otherwise regression target is the ground truth bounding box.
Fixed https://github.com/open-mmlab/mmdetection/issues/2143 so that `IoULoss` could be applied directly in `bbox_head`.
> Unify regression loss

- mmdet/core/optimizer/default_constructor.py
While probably 90+ % of the PyTorch optimizers have `lr` rate as field some exceptions exist.
I for example am often using the "Learned Optimizer List" optimizer (https://github.com/google-research/google-research/tree/master/opt_list), which does not have `lr`as field.
(I'm already preparing my code base for an upgrade to v2.0 and this is one of the things that work in v1.x but not in v2)
> Make 'lr' optional parameter

- mmdet/datasets/xml_style.py
During the training process, I found that some xml files may not have a size field, but the remaining content in these files is complete, so I think it is beneficial to consummate this file
> consummating xml_style.py

- mmdet/core/bbox/assigners/approx_max_iou_assigner.py
- mmdet/core/bbox/assigners/max_iou_assigner.py
- mmdet/core/bbox/iou_calculators/iou2d_calculator.py
This PR removes the boxes[:,:4] in the max_iou_assigner, which makes the assigned box agnostic.
> rm bboxes[:,:4]

- mmdet/core/anchor/anchor_generator.py
- mmdet/core/anchor/point_generator.py
- mmdet/core/anchor/utils.py
- mmdet/models/anchor_heads/anchor_head.py
- mmdet/models/anchor_heads/atss_head.py
This PR changes to use `torch.bool` during index selection with flags.
The original implementation needs to be also available for PyTorch 1.1, whose support for `torch.bool` is limited. Since MMDet V2.0 do not support PyTorch 1.1 anymore, some codes can be simplified.
> Use torch.bool rather than torch.uint8 after deprecate pytorch < 1.3

- mmdet/apis/train.py
Enable self-defined OptimizerHook by inheriting it from mmcv, if do this, you should give the **type** of OptimizerHook in config file.
> enable self-defined OptimizerHook

- mmdet/models/anchor_heads/atss_head.py
Using `dist.reduce_op.SUM` causes warning when using pytorch 1.3, so change to use `dist.ReduceOp.SUM`.
> Fix ATSS warning

- mmdet/datasets/cityscapes.py
This PR fixed cityscapes evaluation. 
Since Cityscapes classes are not total contained by COCO classes, so subclasses could not be used. We reload annotations instead.
> Fix cityscapes eval

- .isort.cfg
- mmdet/models/anchor_heads/fovea_head.py
During multi-GPU training, when num_pos == 0 on line 216 in fovea_head.py, it causes loss_bbox to be a tensor vector of shape [1] while when num_pos > 0, it causes loss_bbox to be a scalar of shape [], causing the gather function to fail. 
This pull request fixes this bug by unsqueezing loss_bbox when num_pos > 0.
> Fix loss_bbox in fovea_head.py when num_pos=0

- mmdet/core/evaluation/mean_ap.py
- mmdet/core/evaluation/recall.py
- mmdet/datasets/cityscapes.py
- mmdet/datasets/coco.py
- mmdet/models/detectors/base.py
- mmdet/ops/dcn/deform_conv.py
- mmdet/utils/__init__.py
- mmdet/utils/logger.py
This PR removed `mmdet.utils.get_root_logger` and `mmdet.utils.print_log`, `mmcv.utils.get_logger` and `mmcv.utils.print_log` are used instead.
> Migrate to mmcv get_logger and print_log

- mmdet/models/dense_heads/fsaf_head.py
Changed the default num_pos to num_neg when num_pos = 0. Otherwise, the loss would be very high when gt is absent in the batch.
> Make FSAF loss more robust to no gt

- mmcv
- mmdet/apis/test.py
- mmdet/datasets/pipelines/transforms.py
- mmdet/models/dense_heads/fsaf_head.py
- mmdet/models/roi_heads/mask_heads/fcn_mask_head.py
- tools/analyze_logs.py
- tools/benchmark.py
The original inference time includes the time of data loading, model forward and post-processing. For the models of instance segmentation, the post-processing time also includes the time of RLE encoding. This PR excludes the time of data loading and RLE encoding to compute the pure inference time.
> compute pure inference time instead

- mmdet/datasets/pipelines/transforms.py
Added an assert in RandomCrop to make sure the given crop size is valid
If 0 area crop size is encounted in MinIouRandomCrop, then continue.
> Avoided the possibility that a patch with 0 area is cropped.

- mmdet/apis/train.py
This PR adds warnings on `imgs_per_gpu`.
Due to API changes, the `imgs_per_gpu` used in the original dataset is no longer used and the alternative is `samples_per_gpu`. To help users migrate the changes, this PR adds the warning if the config still uses `imgs_per_gpu`.
> Add warnings about imgs_per_gpu

- docker/Dockerfile
Without explicitly installing cython the image creation silently creates errors.
```
gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -I../common -I/opt/conda/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
gcc: error: pycocotools/_mask.c: No such file or directory
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for pycocotools
Running setup.py clean for pycocotools
Failed to build pycocotools
```
See also https://github.com/cocodataset/cocoapi/issues/172
> added missing cython to docker file

- mmdet/ops/nms/src/cpu/nms_cpu.cpp
- tests/test_nms.py
The cpu implementation does not return the suppressed detection in order of confidence.
That means that when  `multiclass_nms` has a limit on `max_num` it will not necessarily keep the detections with the highest score.
I have changed the `nms_test`, and committed this first to show how the previous behaviour fails and version in this PR fixes this.
> Fix bug in nms cpu implementation

- mmdet/datasets/pipelines/loading.py
- mmdet/datasets/pipelines/transforms.py
- tests/test_config.py
- tests/test_pipelines/test_transform.py
This PR adds `img_fields` in loading during transform, which enables the similar transformation for multiple images.
> Support Img fields during transform

- mmdet/datasets/pipelines/transforms.py
The PR fix the potential bug in transform.py, where use `img_fields` during transformation.
> Add 'img' as default for back compatibility

- docs/install.md
Since there are some shared objects in `mmdet` directory, we probably need to remove them to get a build that is the latest.
> Add procedure to remove compiled shared objects

- mmdet/models/backbones/regnet.py
Fix the bug of regnet configs, the `base_channels` of stem layer should be 32 rather than 64.
The wrong base_channels will create a different stem layer that does not match the checkpoints, which will degrade the performance.
> Fix base_channels of regnet

- mmdet/models/detectors/base.py
This PR mainly solves a bug of logger in the base detector. In the init_weights function of base detector, if pretrained is not none, a new 'root' logger will be generated to record log information. This PR changes the 'root' logger to the default 'mmdet' logger.
> fix a bug of logger in base detector

- mmdet/apis/train.py
- mmdet/core/utils/dist_utils.py
DistOptimizerHook is deprecated as its methods are all the same with its base class
> Deprecate DistOptimizerHook

- mmdet/datasets/pipelines/loading.py
- mmdet/datasets/pipelines/transforms.py
1. Add numpy array.copy() in loading for both bboxes and labels. 
2. Add protection to avoid in-place modification of results in transforms.py
> prevent possible bugs in loading and transforms caused by shallow copy

- mmdet/datasets/pipelines/test_time_aug.py
``self.transforms`` is a object ``Compose`` which is not iterable.
It can be solved by changing ``self.transforms`` -> ``self.transforms.transform`` but I think checking the transform type is cleaner.
> fix flip test check

- mmdet/models/dense_heads/anchor_head.py
If I am not wrong, it would be a bug when RPN is using (``background_label = 0``), leading to all samples are positive.
Not sure that RPN in model zoo is benchmarked with this bug or not.
> fix anchor target label

- mmdet/models/losses/pisa_loss.py
If some images in one batch images have no gts, there might be a bug in line 53 of pisa loss (can not perform `gt_i.max()` ). This PR has already been discussed with yuhang.
> fix a bug of pisa loss, when some images in one batch images have no gts.

- mmdet/datasets/coco.py
There may exist out-of-frame annotations in custom datasets. These abnormal annotations will cause nan loss. For example, such cases exist in the object365 datasets, and I found both Libra RCNN and Cascade RCNN diverged due to nan loss. After filtering these abnormal cases, these detectors converged. Even though this should be avoided by dataset annotators, it can be more robust of mmdetection to filter out-of-frame annotations.
> Fixed nan loss by filtering out-of-frame gt_bboxes in coco.py

- docs/tutorials/finetune.md
`target_means` and `target_stds` should be in bbox_coder according to
https://github.com/open-mmlab/mmdetection/blob/2b6f6616f804beaca3dbf071fa398c586243db13/configs/_base_/models/mask_rcnn_r50_fpn.py#L48
> fix config bug in docs/tutorials/finetune.md

- mmdet/apis/test.py
This PR fixes a legacy issue of `img_metas` in apis/test.py. Since `img_meta` has bee deprecated and `img_metas` always exists, use `img_metas` to indicate the batch size is a more stable and general manner.
The PR has been tested on mask rcnn models, which could produce similar results.
> Use img_metas to indicate batch

- mmdet/models/dense_heads/rpn_head.py
When use softmax in rpn head，the original implementation has two problems，
https://github.com/open-mmlab/mmdetection/blob/bf9638a7c78f45948c4b812c4e206b4b65841f02/mmdet/models/dense_heads/rpn_head.py#L82
[:,:-1] will keep dimension and this line
https://github.com/open-mmlab/mmdetection/blob/bf9638a7c78f45948c4b812c4e206b4b65841f02/mmdet/models/dense_heads/rpn_head.py#L88
would sort final dimension.
Beside it, we can find we still use fg label as 1 in rpn head
https://github.com/open-mmlab/mmdetection/blob/bf9638a7c78f45948c4b812c4e206b4b65841f02/mmdet/models/dense_heads/anchor_head.py#L221
> fix rpn softmax bug

- docs/tutorials/new_modules.md
- mmdet/models/necks/nasfcos_fpn.py
- mmdet/models/roi_heads/roi_extractors/groie.py
This PR cleans the deprecated usage of `register_module` introduced in recent PRs.
> Clean legacy deprecated usage of register_module

- tools/publish_model.py
`rstrip('.pth')` removes all characters in {'.', 'p', 't', 'h'} at the right. For example, if `out_file="imagenet.pth"`, then `out_file.rstrip('.pth')` is `"imagene"` where "t" is also removed.
> Fix a bug in tools/publish_model.py

- mmdet/models/dense_heads/free_anchor_retina_head.py
fix two bug of `freeanchor` when no gt bboxes in images.
1 
When a single image no gt,  
https://github.com/open-mmlab/mmdetection/blob/84fbb2c6ee7346ea722cea3a4fa16d73e11fcafd/mmdet/models/dense_heads/free_anchor_retina_head.py#L112
max operation would case error,
2
when no any gt in a batch, the regression subnet has no grad after backward, the code would block.
> fix a bug in Freeanchor when no gt

- mmdet/models/dense_heads/anchor_head.py
- mmdet/models/dense_heads/atss_head.py
- mmdet/models/dense_heads/gfl_head.py
When `inside_flags.any()` is `None`,  the return value is abnormal.
> fix bug in dense head

- mmdet/datasets/pipelines/transforms.py
1. Add allow_negative_crop in RandomCrop
2. Resolve a TODO: check whether we can keep the image regardless of the crop.
3. Find out the reason of a sudden boost of nas-fpn performance using the RandomCrop in #2810. In #2810, the allow_negative_crop was implicitly set to True when there is `gt_bboxes_ignore` flag and `gt_bboxes_ignore` is an empty tensor. 
I will keep `gt_bboxes_ignore=False` in this version and provide the performance with  `gt_bboxes_ignore=True` in the nas-fpn README. 
The performance is very close for coco dataset with `gt_bbox_ignore=True` or `gt_bbox_ignore=False`. Both of these are higher than that reported in the model zoo
| | before #2810  | #2810   | `gt_bbox_ignore=True`   |  `gt_bbox_ignore=False` | 
|---|---|---|---|---|
| retinanet_fpn_crop640  | 37.4  | 37.9 …
> Add allow_negative_crop in RandomCrop

- mmdet/datasets/pipelines/test_time_aug.py
- tests/test_data/test_models_aug_test.py
The original class `MultiScaleFlipAug` adds samples without flip augmentations several times when we use `flip_direction=['horizontal', 'vertical']`. This MR fixes this bug and adds test.
For example, if we use the next config:
```python
transform = dict(
type='MultiScaleFlipAug',
transforms=<transforms>,
img_scale=[(1333, 800), (800, 600), (640, 480)],
flip=True,
flip_direction=['horizontal', 'vertical'])
``` 
The original `MultiScaleFlipAug` returns results with length = `len([(1333, 800), (800, 600), (640, 480)]) * len(['horizontal', 'vertical']) * len(['True', 'False']) = 12`.
The fixed `MultiScaleFlipAug` returns results with length = `len([(1333, 800), (800, 600), (640, 480)]) * len(['original', 'horizontal', 'vertical']) = 9`.
> fix bug in MultiScaleFlipAug

- mmdet/core/bbox/assigners/atss_assigner.py
If `self.topk` is larger than `bboxes_per_level`, `distances_per_level.topk()` causes the error below.
```
File "/home/shinya/work/mmdetection/mmdet/core/bbox/assigners/atss_assigner.py", line 123, in assign
self.topk, dim=0, largest=False)
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1587428398394/work/aten/src/THC/generic/THCTensorTopK.cu:23
```
I encountered this error when I trained a model on COCO by multi-scale training (`img_scale=[(1333, 480), (1333, 960)]`).
This error can be reproduced by training on small inputs like `img_scale=(1333, 128)`.
> Fix topk bug in ATSSAssigner

- mmdet/datasets/coco.py
connect `iou_thrs` argument in evaluate with cocoEval
> Connect iou_thrs in coco.py

- .dev_scripts/linter.sh
- mmdet/ops/__init__.py
This PR adds `mmdet.ops` back for back compatibility. In `mmdet.ops`, wrappers of `mmcv.ops` are added thus the projects dependent on mmdet do not need to change the origin codes.
> Add ops warpper

- mmdet/datasets/coco.py
This PR added `metric_items` option for COCO evaluation. 
It also fixed #3468
> Add metric items for COCO

- docs/install.md
This patch fixes the link to mmcv and language choice for 2 code blocks.
The problem with link was pointed out in issue #3490. However, the prebuit still awaits, so I wouldn't want to close the issue yet. @hellock 
I hope this would be helpful.
> typo fix for install.md

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
- docs/common_issue.md
- docs/index.rst
- docs/install.md
- docs/trouble_shooting.md
This PR split the common issues into a single page and add links in issue template.
> Refactor common issues in documentation

- configs/cornernet/README.md
Due to the bug in #3543, the current codebase cannot reproduce the benchmark.
> remove cornernet's benchmark

- mmdet/datasets/voc.py
> Fixed VOC2012 evaluate

- mmdet/models/detectors/base.py
> Fix (base.py): fix with_xxx_attributes in base detector

- mmdet/models/roi_heads/bbox_heads/bbox_head.py
Before this fix, an attempt to rescale an empty tensor of bounding boxes (i.e. of shape `(0,4)` ) results in the following error:
```
RuntimeError: Cannot reshape tensor of 0 elements into shape [0, -1, -4] because the unspecified dimension size -1 can be any value and is ambiguous.
```
> Do not rescale boxes when their number is 0

- configs/cornernet/cornernet_hourglass104_mstest_10x5_210e_coco.py
- configs/cornernet/cornernet_hourglass104_mstest_32x3_210e_coco.py
- configs/cornernet/cornernet_hourglass104_mstest_8x6_210e_coco.py
- mmdet/models/dense_heads/corner_head.py
- mmdet/models/utils/gaussian_target.py
- tests/test_models/test_heads.py
1.  Fixed the bug in `gen_gaussian_target` while multiple gts in one class but only got one peak in the heat map.
2. Expand to 3 gt_bboxes in `test_corner_head_encode_and_decode_heatmap` and two of them are the same class.
3. Replace `expand` with `repeat` in `corner_head.py` to avoid shallow-copy cases, which may generate unexpected results in `2.`
| codebase | batchsize | mAP |
| :-: | :-: | :-: |
| Current | 16 x 6 | 41.2 |
| Current | 10 x 5 | still running |
| Last benchmark | 16 x 6 | 41.1 |
| Last benchmark | 10 x 5 | 41.3 |
| Paper | 10 x 5 | 40.5 |
> fix bug of gaussian_target, update unittest of heatmap

- configs/atss/README.md
- configs/atss/atss_r101_fpn_1x_coco.py
I add the checkpoint and corresponding log file of ATSS with Resnet101.
> add atss 101

- docs/tutorials/new_modules.md
- tools/benchmark.py
- tools/get_flops.py
- tools/pytorch2onnx.py
- tools/test.py
- tools/test_robustness.py
- tools/train.py
Allow manually importing modules specified in the config files instead of modifying the `__init__.py` file.
> Custom imports

- mmdet/core/bbox/samplers/ohem_sampler.py
- mmdet/models/roi_heads/cascade_roi_head.py
I got the error(TypeError: forward() missing 1 required positional argument: 'x_reg') when i used the OHEMSampler in the DoublehandRCNN, so I checkd the ohem_sampler.py and double_roi_head.py. 
line 27(double_roi_head.py) :
cls_score, bbox_pred = self.bbox_head(bbox_cls_feats, bbox_reg_feats)
line 37(ohem_sampler.py):
cls_score, _ = self.bbox_head(bbox_feats)
the arguments are different.
in the meantime, self.with_shared_head is in the double_roi_head.py but not in the ohem_sampler.py
so I did some fixes
> Is there a bug in the OHEMSampler?

- mmdet/models/backbones/res2net.py
I rewrite init_weights in the res2net.py to fix the test bug(AttributeError: 'Bottle2neck' object has no attribute 'conv2')
> fix res2net+dcn test bug

- mmdet/core/post_processing/merge_augs.py
- mmdet/models/detectors/base.py
fix typo in the comment:
my also contain -> may also contain
> [fix] typo

- mmdet/models/dense_heads/atss_head.py
Fixed two bug in the ATSS model, each occurred when a single image did not contain any gt boxe and the total batch did not contain any gt  boxe respectively
> fix atss no gt

- mmdet/models/dense_heads/rpn_test_mixin.py
> Fix self.rpn_head in rpn head

- .dev_scripts/batch_test.py
- mmdet/core/__init__.py
- mmdet/core/fp16/__init__.py
- mmdet/core/fp16/deprecated_fp16_utils.py
- tools/benchmark.py
- tools/test.py
- tools/test_robustness.py
This PR:
- Fix bc break of fp16
- Added warning for importing deprecated mmdet version of fp16 utils
- refactored some import of fp16 utils now that mmcv 1.1.3 is up(and required by mmdet)
> Fix bc break of fp16

- mmdet/models/detectors/two_stage.py
- mmdet/models/roi_heads/standard_roi_head.py
- mmdet/models/roi_heads/test_mixins.py
The comments like `# recompute feats to save memory` are so confusing.
What does `recompute feats` mean?
Old codes before the commit below recompute feats by calling `self.extract_feats(imgs)` 2-3 times.
https://github.com/open-mmlab/mmdetection/commit/c29a789c46014cc1ae181f1bbb2e8ec01c44a01c#diff-37358d90bcb60a9f015ed7c0ffcf6dd1
> Clean outdated comments

- mmdet/models/dense_heads/reppoints_head.py
> fix bug when RepPoints run in a specific gpu instead of cuda:0

- docs/install.md
HTTP will be ignored as it is not a trusted or secure host.
> Modify http to https when installing mmcv-full

- mmdet/models/roi_heads/test_mixins.py
> fix sabl validating bug

- tools/upgrade_model_version.py
I think rpn has no relation to num_classes in two stage networks.
the origin code will cause the size mismatch for rpn_head.rpn_reg.weight/bias between the old model and new model
> fix rpn transforming bug in two stage networks

- mmdet/core/post_processing/bbox_nms.py
Fix https://github.com/open-mmlab/mmdetection/issues/3865 and https://github.com/open-mmlab/mmdetection/issues/3467
The warning can be ignored, and will [disappear in PyTorch 1.7.0](https://github.com/pytorch/pytorch/pull/45413).
However, the `nonzero` in `multiclass_nms` makes ProgressBar ugly and weird in testing.
```
[                                                  ] 0/5000, elapsed: 0s, ETA:/home/shinya7y/work/mmdetection/mmdet/core/post_processing/bbox_nms.py:54: UserWarning: This overload of nonzero is deprecated:
nonzero()
Consider using one of the following signatures instead:
nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/python_arg_parser.cpp:766.)
labels = valid_mask.nonzero()[:, 1] …
```
> Fix nonzero in NMS for PyTorch 1.6.0

- configs/yolo/yolov3_d53_mstrain-608_273e_coco.py
- mmdet/models/dense_heads/atss_head.py
- mmdet/models/dense_heads/dense_test_mixins.py
- mmdet/models/dense_heads/fcos_head.py
- mmdet/models/dense_heads/yolo_head.py
This PR enables `dense_test_mixins.py` to process `score_factors` for NMS.
ATSS ([model](http://download.openmmlab.com/mmdetection/v2.0/atss/atss_r50_fpn_1x_coco/atss_r50_fpn_1x_coco_20200209-985f7bd0.pth))
```
0.394 0.576 0.428 0.236 0.429 0.503  # img_scale=(1333, 800),
0.391 0.575 0.424 0.258 0.426 0.471  # img_scale=(1600, 960),
0.404 0.583 0.440 0.260 0.438 0.499  # img_scale=[(1333, 800), (1600, 960)],
0.398 0.580 0.433 0.247 0.435 0.510  # img_scale=(1333, 800), flip=True,
```
FCOS ([model](http://download.openmmlab.com/mmdetection/v2.0/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_coco/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_coco_20200603-67b3859f.pth))
```
0.386 0.572 0.417 0.224 0.424 0.502  # img_scale=(1333, 800),
0.389 …
```
> Support TTA of ATSS, FCOS, YOLOv3

- mmdet/models/detectors/base.py
The mask returned by YOLACT has dtype 'uint8', which will extremely slow down the speed when using the mask as image's index.
``` bash
python tools/test.py configs/yolact/yolact_r101_1x8_coco.py checkpoints/yolact_r101_1x8_coco_20200908-4cbe9101.pth --show-dir ./result/
[                                                  ] 4/5000, 0.1 task/s, elapsed: 72s, ETA: 90141s
```
Requesting all models to return masks with dtype 'bool' is another way to solve this problem, but this PR is the easiest way to fix it, and gives more robustness to BaseDetector.show_result().
> [Enhance]: Convert mask to bool before using it as img's index for robustness and speedup

- docker/Dockerfile
When I train a faster_rcnn network with the current docker script I get the following error:
```
Traceback (most recent call last):
File "tools/train.py", line 8, in <module>
import mmcv
File "/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
from .fileio import *
File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
from .io import dump, load, register_handler
File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/io.py", line 4, in <module>
from ..utils import is_list_of, is_str
File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 29, in <module>
from .env import collect_env
File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/env.py", line 8, in <module>
import cv2
File …
```
> [Docker] fix cv2 import error of ligGL.so.1

- mmdet/models/utils/__init__.py
- mmdet/models/utils/builder.py
- mmdet/models/utils/transformer.py
This PR reformat the merged version of DETR transformer.
> Reformat DETR transformer.

- docs/getting_started.md
- docs/tutorials/customize_models.md
- docs/tutorials/finetune.md
This pr update docs `from ..registry import` -> `from ..builder import` (#3846) and fix broken urls in docs.
> [doc] update docs and fix broken urls

- mmdet/apis/inference.py
Since RoIAlign in mmcv.ops is supported with aligned=False in CPU mode, there's no need to use the op from torchvision in CPU mode.
> [enhance]: Use RoIAlign implemented in MMCV for inference in CPU mode

- mmdet/apis/train.py
Modify to support  batch_size > 1 in validation mode.
Resolves #3852
> [enhance]: Support batch_size > 1 in validation (#3852)

- docs/trouble_shooting.md
Resolves https://github.com/open-mmlab/mmdetection/issues/3379
> Update trouble shooting

- tools/test_robustness.py
Minor fixes of  #4000
- Don't raise AssertionError if `show-dir` is specified.
- Fix TypeError when joining `show_dir` with `corruption_severity` (int)
> Fix show dir test robustness

- mmdet/datasets/pipelines/transforms.py
ref: https://github.com/numpy/numpy/issues/13001
```python
%%timeit
a = np.full((4000, 2000, 3), [0.0, 0.0, 0.0], np.float32)
76.9 ms ± 346 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%%timeit
a = np.full((4000, 2000, 3), [0, 0, 0], np.float32)
71.4 ms ± 516 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%%timeit
a = np.full((4000, 2000, 3), 0.0, np.float32)
47.2 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%%timeit
a = np.full((4000, 2000, 3), 0, np.float32)
47 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%%timeit
a = np.empty((4000, 2000, 3), np.float32)
a.fill(0.0)
46.3 ms ± 278 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%%timeit
a = np.empty((4000, 2000, 3), np.float32)
a.fill(0)
46.3 ms ± 184 µs per loop (mean …
```
> Speedup expand when meets large image

- mmdet/models/dense_heads/free_anchor_retina_head.py
This PR tries to resolve the training instability of FreeAnchor when the probabilities are very close to 1 or 0.
> Clamp neg probability in freeanchor

- mmdet/datasets/pipelines/transforms.py
https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/composition.py#L223
"data" is List
> masks from (n,h,w) to [(h,w),...,(h,w)]

- mmdet/datasets/pipelines/transforms.py
- tests/test_data/test_transform.py
This PR re-implements RandomCrop to support more crop_type following the official Detectron2.
The original implementation of RandomCrop is a special case when crop_type='absolute'.
> Re-implements RandomCrop to support different crop_type

- tools/train.py
This PR fix the incorrect gpu_id shown in the training log, in the case of distributed training mode.
> Fix incorrect gpu_id with distributed training mode

- mmdet/models/necks/pafpn.py
PAFPN has no attribute extra_convs_on_inputs
retinanet-like detectors can use PAFPN
> fix bug: PAFPN has no attribute extra_convs_on_inputs

- mmdet/models/dense_heads/yolo_head.py
Hi,
Change `flatten`  to `squeeze`  in `yolo_head`.  
`flatten` would create a Reshape op with constant shape values while exporting to ONNX with Pytorch==1.6.0, which results in an incorrect ONNX model and would raise Runtime Error when doing inference in ONNX Runtime.
Root causes are unknown.
Normally, `flatten` and `squeeze` are functionally equal, but the tracing may be different in Pytorch.
> [Fix]: reshape error of yolov3 in onnxruntime

- configs/detr/README.md
- configs/detr/detr_r50_8x2_150e_coco.py
- tests/test_models/test_forward.py
This PR changes the default config of DETR from 4 images per GPU to 2 images per GPU for higher performance and match the log and checkpoints.
> Fix detr config for higher performance

- mmdet/core/bbox/iou_calculators/iou2d_calculator.py
Add missing mode "giou" in comment of `mmdet/core/bbox/iou_calculators/iou2d_calculator.py`. It made me a little confusing that I thought "giou" was not supported, hope this helps  : )
> add missing mode "giou" in comments for iou2d_calculator.py

- docs/tutorials/index.rst
- docs/tutorials/pytorch2onnx.md
- docs/useful_tools.md
- tools/pytorch2onnx.py
Hi,
Add a document for the usage and the list of supported models of `pytorch2onnx` .
> [doc]: add doc for pytorch2onnx

- .github/CONTRIBUTING.md
`echo 'source $HOME/.bash_profile' >> ~/.bashrc` may cause an infinite loop.
Flowchart examples:
https://www.solipsys.co.uk/images/BashStartupFiles1.png
https://cdn-ak.f.st-hatena.com/images/fotolife/N/Naotsugu/20191110/20191110015450.png
> Fix script to install ruby

- mmdet/models/dense_heads/atss_head.py
The same fix as GFL. https://github.com/open-mmlab/mmdetection/pull/4210
I haven't checked AP difference caused by eliminating rounding error.
> Update ATSS for PyTorch 1.6+

- mmdet/models/dense_heads/corner_head.py
Fix TypeError: can't convert cuda device type tensor to numpy
> Fix TypeError: can't convert cuda device type tensor to numpy

- docs/get_started.md
It did not contain the checkpoint download step.
> Corrected the get_started.md example inference

- mmdet/datasets/pipelines/loading.py
- mmdet/datasets/pipelines/test_time_aug.py
- mmdet/datasets/pipelines/transforms.py
previous __repr__ produces something like
```python
LoadAnnotations(with_bbox=True, with_label=True, with_mask=False, with_seg=False)poly2mask=True)poly2mask={'backend': 'disk'})
```
However the parenthesis is not paired, and this happens in multiple classes.
> fix: repr formats

- docs/tutorials/config.md
Update documentation about the modification of train_cfg/test_cfg
resolve #4470
> Update documentation about the modification of train_cfg/test_cfg

- mmdet/core/post_processing/bbox_nms.py
Fixed #4322 
Before #4087, `score_thr` is applied before multiply `score_factor`. 
However, in #4087, the order is switched, which led to the degenerated performance for YOLOv3 and FCOS.
> [Bug fix] Fix order of nms score_factor

- docs/tutorials/pytorch2onnx.md
- tools/pytorch2onnx.py
This PR simply add `simplify` option to pytorch2onnx tool. Users could use this feature to simplify the exported onnx models.
> add onnx simplify option to pytorch2onnx tool

- mmdet/core/mask/structures.py
- tests/test_masks.py
mmcv takes `(w, h)` as input `size`, while `mmdet.core.structures.BitmapMasks` passes in `(h, w)`. The mistake did not trigger pytest errors, since all the relevant tests let `w == h`. 
A typical resized mask looks like
The bug is fixed and two more test cases are supplied in the pull request.
> Fix: mask resize

- mmdet/datasets/__init__.py
According to the code specification of MMDetection, I add an obvious `import` for `NumClassCheckHook`, although this is not necessary
> add a abvious import

- tools/model_converters/upgrade_model_version.py
Comment the first line of meta_info['config'] to avoid syntax error.
[#3122](https://github.com/open-mmlab/mmdetection/issues/3122)
> fix syntax error when upgrading model version

- mmdet/core/evaluation/eval_hooks.py
I modified the eval_hook.py to support broadcast the buffer of batch_norm in rank 0 to other ranks , so as to ensure that the test results in the log can be consistent with individual test results with the saved checkpoint.
> add bn buffer sync in eval_hook

- tools/analysis_tools/benchmark.py
- tools/analysis_tools/get_flops.py
- tools/analysis_tools/test_robustness.py
This code removed is redundant because `mmcv.Config.fromfile` method has called `import_modules_from_strings` method for `custom_imports`. This PR is removing all the redundant code. Some code look like redundant in `tools/train.py` and so on. But calling `cfg.merge_from_dict` method maybe changes `cfg_dict.custom_imports` config, so it is necessary to call `import_modules_from_strings` method again.
> remove redundant code calling import_modules_from_strings

- mmdet/datasets/pipelines/transforms.py
I fix a bug when using Albumentations and  specific workflow as `workflow = [('train', 1), ('Val', 1)]`, 
https://github.com/open-mmlab/mmdetection/blob/16fffcc72e316dc11d510701c1c4ba5e3e2c81a5/mmdet/datasets/pipelines/transforms.py#L1253
modify the origin args and cause the error in the Val epoch.
close #4599 and close #4586
> fix modify args

- mmdet/models/dense_heads/gfl_head.py
Resolves https://github.com/open-mmlab/mmdetection/issues/4623
The real cause of the crash mentioned in #4623 is that the 0 tensor is created by `torch.tensor(0).cuda()`. This is undesirable as it will not only create an integer tensor but also may put the tensor to GPU:0.
> [Enhance]: Avoid crash in empty gt training of GFL

- mmdet/datasets/utils.py
- tests/test_data/test_utils.py
Original code:
```python
loading_pipeline_cfg = []
for cfg in pipeline:
if cfg['type'].startswith('Load'):
loading_pipeline_cfg.append(cfg)
```
It is not suitable for getting loading pipeline to use `startswith` method. It is possible to exist a pipeline whose string start with 'Load' but which isn't a loading pipeline. It is also possible to exist a pipeline inherited from `LoadImageFromFile` class or `LoadAnnotations` class whose string is not start with 'Load', such as `AnimalLoadImageFromFile`.
New code:
```python
loading_pipeline_cfg = []
for cfg in pipeline:
obj_cls = PIPELINES.get(cfg['type'])
if obj_cls is not None and isinstance(obj_cls, (LoadImageFromFile, LoadAnnotations)):
loading_pipeline_cfg.append(cfg)
```
> use isinstance method to get loading pipeline

- .dev_scripts/gather_benchmark_metric.py
Support automatic statistics metrics to excel and fix total_epochs.
Because the file format will be disrupted after excel is written, so the original file is not overwritten
> [Enhance]: Support automatic statistics metrics to excel and fix total_epochs

- mmdet/apis/inference.py
- mmdet/core/visualization/image.py
- mmdet/models/detectors/base.py
- tools/test.py
Deprecated warning and fix 'meta' error
> [Refactor]: Clean deprecated warning and fix 'meta' error

- mmdet/core/anchor/anchor_generator.py
- mmdet/models/dense_heads/anchor_head.py
This PR modified `AnchorHead` to support dynamic shape for `grid_anchor` when exporting to ONNX.
> [Feature]: support dynamic shape for grid_anchor

- mmdet/core/export/pytorch2onnx.py
- tools/analysis_tools/benchmark.py
- tools/analysis_tools/eval_metric.py
- tools/analysis_tools/get_flops.py
- tools/analysis_tools/test_robustness.py
- tools/deployment/pytorch2onnx.py
- tools/misc/browse_dataset.py
- tools/misc/print_config.py
It is necessary to override some settings in the used config. But I find it is not containing parser argument 'cfg-options' in some tools. So I add it.
> Add parser argument 'cfg-options' for some tools

- mmdet/models/dense_heads/anchor_head.py
This PR fix `RuntimeError` due to two tensor are not on the same device.
test scripts:
```
python demo/image_demo.py demo/demo.jpg configs/retinanet/retinanet_r50_fpn_1x_coco.py checkpoints/retinanet/retinanet_r50_fpn_1x_coco.pth
```
Trace info :
```
Traceback (most recent call last):
File "demo/image_demo.py", line 26, in <module>
main()
File "demo/image_demo.py", line 20, in main
result = inference_detector(model, args.img)
File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmdetection/mmdet/apis/inference.py", line 141, in inference_detector
results = model(return_loss=False, rescale=True, **data)
File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File …
```
> fix `RuntimeError` due to two tensor are not on the same device

- mmdet/core/visualization/image.py
> [Fix]: Fix float image show error

- mmdet/models/dense_heads/rpn_head.py
- mmdet/models/detectors/single_stage.py
- mmdet/models/detectors/two_stage.py
- mmdet/models/roi_heads/test_mixins.py
this pr was useful for exported onnx model support dynamic input shapes, there are four changes in total:
1. rpn_head.py, modify topk's attribute K, which was used to keep topk op for dynamic K in onnx model, use                           
```python
nms_pre = torch.where(scores_shape[0] < cfg.nms_pre, scores_shape[0], cfg.nms_pre)
```
to replace                                                          
```python
if scores.shape[0] > cfg.nms_pre: 
nms_pre = scores.shape[0] 
else:
nms_pre = cfg.nms_pre
```
2. two_stage.py, add code
```python
if torch.onnx.is_in_onnx_export():
img_shape = torch._shape_as_tensor(img)[2:]
img_metas[0]['img_shape_for_onnx'] = img_shape
```
keep the original input shape for Post-processing which was related to calculation of dynamic shapes
3. single_stage.py, …
> [Feature]:add dynamic shape support for two_stage func

- mmdet/models/dense_heads/embedding_rpn_head.py
- mmdet/models/detectors/cascade_rcnn.py
- mmdet/models/detectors/rpn.py
> Fix RPN show_result error

- mmdet/datasets/xml_style.py
Some public datasets such as DIOR (https://arxiv.org/abs/1909.00133) use the VOC style annotations but do not contain the 'difficult' tag in their xml files, thus `obj.find('difficult')` may return `None` and raise an error.
> Fix parse error in XMLDataset

- docs/1_exist_data_model.md
tiny PR... found a typo when going through examples
> doc(quickrun): minor syntax typo fix

- mmdet/models/roi_heads/test_mixins.py
@hhaAndroid Thanks for your contributions on batch inference. I suggest changing the `5` to `proposal.size(1)` in case that sometimes proposals do not have scores (an N * 4 tensor) if they are loaded from files.
> Fix supplement size in simple_test_bboxes

- mmdet/datasets/coco.py
Only check when it is used - this helps with #4565.
The rest of mmdet can still work with official pycocotools.
> move mmpycocotools version check to when it is used

- mmdet/models/dense_heads/anchor_head.py
fix the docstring of `get_bboxes` in anchor_head.py.
> fix docstr of anchor head

- mmdet/core/export/onnx_helper.py
Hi
This PR use `Tensor.clamp(0, 1)` instead of `torch.where` to fix the conversion error on two-stage detection models such as Faster-RCNN.
> Fix dynamic clip error in box coder for TensorRT

- mmdet/core/bbox/iou_calculators/iou2d_calculator.py
In GPU and CPU environments with limited hardware resources, bbox_overlaps often has CUDA memory allocation errors (there are a large number of anchor boxes when calculating IOU). To do this, we added bbox_overlaps on FP16 to save memory and keep speed at the same time. 
TO DO: 
all IOU calculation on fp16 including NMS.
> add bbox_overlaps for fp16 to save memory and keep speed

- mmdet/models/dense_heads/fcos_head.py
- mmdet/models/dense_heads/vfnet_head.py
resolved: #4724 
After modification and training, the mAP is as follows：
| model                                                        | modification | bbox_mAP | bbox_mAP_50 | bbox_mAP_75 |
| ------------------------------------------------------------ | ------------ | -------- | ----------- | ----------- |
| [FCOS](https://github.com/open-mmlab/mmdetection/tree/master/configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_1x_coco.py) | before       | 42.3     | 61.1        | 45.4        |
|                                                              | after        | 42.4     | 61.3        | 45.7        |
| [VFNet](https://github.com/open-mmlab/mmdetection/blob/master/configs/vfnet_r50_fpn_1x_coco.py) | before       | 41.6     | 59.5        | 45          |
| …
> Fix vfnet and fcos reduce_mean

- configs/lvis/README.md
- docs/compatibility.md
- mmdet/datasets/api_wrappers/__init__.py
- mmdet/datasets/api_wrappers/coco_api.py
- mmdet/datasets/coco.py
- mmdet/datasets/lvis.py
- requirements/optional.txt
- requirements/runtime.txt
`mmpycocotools` and official `pycocotool` have the same package name. Users install `pycocotools` first fail to run MMDetection. 
As the `pycocotool` is maintained by the official team now, we decide to deprecate the `mmpycocotool`. To make official `pycocotools` works with MMDetection, we add some function aliases for `pycocotools.coco.COCO`. 
Besides, this PR makes users able to install MMDetection and Detectron2 under the same environment. 
Fixed #4565
> [Refactor] Use pycocotools instead of mmpycocotools

- mmdet/models/roi_heads/__init__.py
Expose some inner classes in `bbox_heads` and `roi_extractors` to `roi_heads`.
> Fix imports in roi_heads

- mmdet/models/dense_heads/vfnet_head.py
resolve: #5009
Precision alignment after modification.
> Fix dead lock of vfnet

- mmdet/datasets/utils.py
fixes https://github.com/open-mmlab/mmdetection/issues/4971
> fix training with single class dataset

- mmdet/core/bbox/samplers/random_sampler.py
```
2021-04-19 16:53:29,111 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
- GCC 7.3
- C++ Version: 201402
- Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- NNPACK is enabled
- CPU capability usage: AVX2
- CUDA Runtime 11.1
- NVCC architecture …
```
> Fix torch.randperm

- docs/tutorials/pytorch2onnx.md
This PR adds table format of pytorch2onnx for online doc: [https://mmdetection.readthedocs.io/](https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html#results-and-models)
> [Doc]: add table format of pytorch2onnx

- mmdet/models/roi_heads/test_mixins.py
Fix the bug when calculating supplement_mask.
Although the risk is low, the last number of a box has chances to be zero.
It may lead to inconsistent numbers of bbox_results and segm_results. And the evaluation process fails at
`File "/mnt/mmdet-dev/mmdetection/mmdet/datasets/coco.py", line 259, in _segm2json`
`if isinstance(segms[i]['counts'], bytes): `
`IndexError: list index out of range`.
> fix supplement_mask

- mmdet/models/roi_heads/test_mixins.py
Enable roi_head test empty rois.
> [Fix] Enable roi_head test empty rois

- docs/compatibility.md
- mmdet/datasets/coco.py
This PR delete the key `bbox` in the prediction results when calculating the mask AP of predictions.
When calculating `segm AP`, if key `bbox` is in the prediction, the area of instance will be calculated by the box area rather than the mask area, which will not affect the overall mask AP but will lead to a different mask APs of small/medium/large instances. A comparison is as below
|model|modification|mask AP|AP50|AP75|APs|APm|APl|
|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|[Mask R-CNN ms3x](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco.py) ([ckpt](http://download.openmmlab.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x …
> [Fix]: fix mask AP of small/medium/large

- mmdet/models/dense_heads/cascade_rpn_head.py
- mmdet/models/dense_heads/ga_rpn_head.py
- mmdet/models/dense_heads/rpn_head.py
As described in #5005, sometimes anchor heads may produce proposals with `area == 0`, which brings errors during mask prediction (masks can not be predicted when the areas of bboxes are 0). A possible solution is setting `min_bbox_size` to a value larger than 0, but I suggest simply discarding all the proposals with `area == min_bbox_size` in anchor heads directly.
> [Fix] Discard bboxes with sizes equals to min_bbox_size

- .dev_scripts/gather_models.py
- tools/model_converters/publish_model.py
when using PyTorch version>=1.6 to publish models, errors occur when loading weights from URL. Please refer to https://github.com/open-mmlab/mmediting/pull/291
resolve: https://github.com/open-mmlab/mmdetection/issues/4309
> Fix error in publish_model.py for pt>=1.6.

- mmdet/datasets/voc.py
Variable name typo error in RPN recall evaluation code on VOC dataset.
resolve: https://github.com/open-mmlab/mmdetection/issues/5186
replace iou_thr with iou_thrs.
> fix voc recall iou_thr name error

- mmdet/models/dense_heads/rpn_head.py
- tools/deployment/pytorch2onnx.py
In the current version of mmdetection, the quality of the Faster R-CNN model in ONNX Runtime has dropped.
This PR will fix it and return the quality as in the [table](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#results-and-models).
To get the results I used `tools/deployment/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py --eval bbox`:
|   | master | fix_faster_rcnn |
|---|:------:|:---------------:|
| Average Precision  (AP) @[ IoU=0.50:0.95 , area=   all , maxDets=100 ]  | 0.370 | 0.374 |
| Average Precision  (AP) @[ IoU=0.75      , area=   all , maxDets=1000 ] | 0.575 | 0.582 |
| Average Precision  (AP) @[ IoU=0.50:0.95 , area= small , maxDets=1000 ] | 0.402 | 0.406 |
| Average Precision  (AP) @[ IoU=0.50      , area=   all , …
> [Fix] Faster R-CNN fix in ONNX Runtime 

- mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py
This PR speeds up roi extractor for onnx.
> [Enhancement]: Speed up roi extractor for onnx

- mmdet/models/dense_heads/detr_head.py
In python3.8, changing the key of a dictionary during iteration is forbidden.
None
> fix py3.8 dict changed during iteration

- mmdet/models/roi_heads/cascade_roi_head.py
In the original implementation, when do the AugTest of `cascade_mask`,   
https://github.com/open-mmlab/mmdetection/blob/68c2c1192a3e16987c8100d2d75abd15d7c39ea2/mmdet/models/roi_heads/cascade_roi_head.py#L462
The outermost `[]`  which means the `num_img`  should be deleted.
None
resolve #5110
> Fix AugTest  of Cascade_MaskRCNN when len(det_bboxes) is 0

- configs/yolo/README.md
- configs/yolo/metafile.yml
- configs/yolo/yolov3_d53_fp16_mstrain-608_273e_coco.py
Update yolov3_d53_mstrain-608_273e_coco result after #5181 and add a model using fp16 training.
Pre-trained weights and logs have been added.
> Update YOLOv3 models

- mmdet/datasets/api_wrappers/coco_api.py
- mmdet/datasets/coco.py
- tests/test_data/test_datasets/test_coco_dataset.py
In pycocotools, 
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/coco.py#L173
The `ids`  can be not consistent with the order of `catNms` which is we do not expect,
this can results in a wrong visualization result when you specify a list of classes that is not consistent with the order of inner  `cats`.
None
> Make `cat_ids` be consistent with the order of `CLASSES`

- mmdet/datasets/api_wrappers/coco_api.py
- tests/test_data/test_datasets/test_coco_dataset.py
In https://github.com/open-mmlab/mmdetection/pull/5227/ , the modification about the `get_cat_ids` would  make the return `keep_order_cat_ids`  contains duplicate categories.
We have to pass a tuple of string instead of string， otherwise the function would return the same id for some categories such as 'bear' and 'teddy bear' 
None
> fix `get_cat_ids` of coco_api

- mmdet/models/roi_heads/mask_heads/fcn_mask_head.py
```
------------------------------------------------------------
sys.platform: win32
Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Not Available
GCC: n/a
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
- C++ Version: 199711
- MSVC 192829913
- Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
- OpenMP 2019
- CPU capability usage: AVX2
- CUDA Runtime 11.1
- NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=s …
```
> Fix torch.chunk int32 overflow

- docs/get_started.md
The origin `getting_start` markdown file is not clear at installing conda environment. 
Especially, `pip install mmdet` is not clear. So we clarify the way how to install conda environment. 
We remove 0.`pip install mmdet`, and create conda env first.
In step 5, we give two options to install mmdet.
```shell
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
```
Or, you can simply install mmdetection with the following commands:
```shell
pip install mmdet
```
relevant issue: #5029
> [Docs] clarify installation document

- mmdet/models/utils/transformer.py
In https://github.com/open-mmlab/mmcv/pull/978, `MultiScaleDeformableAttention` has been moved to `mmcv/ops/multi_scale_deform_attn.py`. We have to fix the import path of  `MultiScaleDeformableAttention`.
None
> fix the import path of msda

- docs/faq.md
Sometimes COCO will get a result of  -1 in the evaluation. We explained this phenomenon.
According to [cocotools evaluate code](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py) line 452
If there are no small or medium objects, the value will be set to -1.
Resolves #4494
> [Docs] Add FAQ about COCO AP or AR =-1 

- mmdet/models/backbones/darknet.py
- mmdet/models/backbones/hrnet.py
- mmdet/models/backbones/mobilenet_v2.py
- mmdet/models/backbones/regnet.py
- mmdet/models/backbones/resnet.py
- mmdet/models/backbones/ssd_vgg.py
- mmdet/models/detectors/rpn.py
- mmdet/models/detectors/single_stage.py
- mmdet/models/detectors/two_stage.py
Currently, there is still some code setting `backbone.pretrained = pretrained` even when it is not used. This will cause unable to use mmcls backbones since there is no `pretrained` kwarg in mmcls.
This PR fixes this problem.
> [Fix] Not use deprecated pretrained kwarg when it is None

- mmdet/models/necks/yolo_neck.py
- tests/test_models/test_necks.py
At the moment, YOLOV3Neck only allows to create neck architectures that have `out_channels[0] == in_channels[1]` and `out_channels[1] == i_channels[2]`. This is due to this line of code:
```
for i in range(1, self.num_scales):
in_c, out_c = self.in_channels[i], self.out_channels[i]
self.add_module(f'conv{i}', ConvModule(in_c, out_c, 1, **cfg)) <<<---
self.add_module(f'detect{i+1}',
DetectionBlock(in_c + out_c, out_c, **cfg))
```
It can be easily fixed to allow more flexible architectures without any backward compatibility issues.
It is convenient when you assemble YOLO-like architecture using some pretrained backbone, e.g. mobilenetv2_100 that has [320, 96, 32] channels in output feature maps. Current implementation enforces you to use very tight neck with [96, 32, X] channels. Less …
> Make YOLOv3 neck more flexible

- mmdet/models/dense_heads/autoassign_head.py
I am viewing source code of auto-assign. When I read the function "_get_target_single(self, gt_bboxes, points)", I find that there is a small mistake in the function annotation. 
See the changes, below. Just small modification.
> fix shape error in code annotation of auto-assign

- mmdet/models/backbones/ssd_vgg.py
Fix SSD-VGG backbone bug,
`elif pretrained is None` need follow `if instance(Pretrained, str)`
> [Fix] fix ssd_vgg backbone bug

- mmdet/core/export/pytorch2onnx.py
The default type of `scale_factor` in `one_meta` (Line 123 in pytorch2onnx.py) is double. That leads to the type error when exporting Mask R-CNN to ONNX.
Change the default type to float32.
RuntimeError: expected scalar type Float but found Double.
> [Fix] fix default type of scale_factor during onnx export

- mmdet/core/__init__.py
- mmdet/core/anchor/__init__.py
- mmdet/core/anchor/anchor_generator.py
- mmdet/core/anchor/builder.py
- mmdet/core/anchor/point_generator.py
- mmdet/models/dense_heads/reppoints_head.py
- tests/test_utils/test_anchor.py
As an essential step of unifying the `get_bboxes` of `anchor_head` and `anchor_free_head`, we need to design a more unified interface for the generation of anchors and points.
1. Rename the ``ANCHOR_GENERATORS`` to  ``PROIRS_GENERATORS``.
2. Add  `MlvlPointGenerator` which follow the logic of `AnchorGenerator`.
3. Add `spares_priors` to all `AnchorGenerator` and `PointGenerator` 
4. Rename `grid_anchors` and `grid_points` to `grid_priors`.
5. Add a more unified function as `single_level_grid_priors` to `AnchorGenerator` which follow the original implementation as `single_level_grid_anchors`, but we remove the `base_anchors` and `strides` from dataflow and add `level_idx` to be consistent with `MlvlPointGenerator`
None.
I retain all the original interfaces and add deprecated warnings.
> Refactor anchor_generator and point_generator

- mmdet/core/post_processing/merge_augs.py
- mmdet/datasets/pipelines/test_time_aug.py
- tests/test_data/test_pipelines/test_transform/test_models_aug_test.py
Add support for mask diagonal flip in `mmdet/core/post_processing/merge_augs.py` for test-time augmentation.
> [Feature] Add support for mask diagonal flip in TTA

- mmdet/models/roi_heads/htc_roi_head.py
Originally the HTC algorithm it is intended to be used for Instance Segmentation. Nevertheless it is one of the best SOTA algorithms for Object Detection which is living in the mmdetection framework. The HTC algorithm has an interleaved execution of bbox_heads and mask_heads. For Object Detection only the bbox_heads are needed. The design of the HTC algorithms allows to remove the mask_head while the bbox_head keeps working.
To get the above mentioned feature working, only the assert for the mask_head has to be removed. This allows to use config files with no mask_head configured, while still being able to use the bbox_head parts of the algorithm. Also all other configurations will still work. Please advice me if I have missed situations where the assert is really needed and therefore …
> allow to configure out the mask_head of the HTC algorithm

- mmdet/models/roi_heads/bbox_heads/bbox_head.py
In the `onnx_export` of `bbox_head.py`, when the `self.reg_class_agnostic` is True, the shape of `bboxes`  can not match the shape of `scores` and `labels`.
https://github.com/open-mmlab/mmdetection/blob/ff649bd870190567d6c60aed4286909d5370da7b/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L547
the shape would mismatch when `reg_class_agnostic` is True.
> fix onnx_export of bbox_head when reg_class_agnostic

- mmdet/models/losses/mse_loss.py
- tests/test_models/test_loss.py
Add reduction_override in MSELoss.
When using MSELoss replace L1Loss in Faster R-CNN or Mask R-CNN, may get a bug, this PR adds reduction_override Args in MSELoss.
> [Refactor] Add reduction_override in MSELoss

- mmdet/models/detectors/base.py
val_step() missing 1 required positional argument: 'optimizer'
Reslove: https://github.com/open-mmlab/mmcv/issues/1107
add the default value.
> fix val_step() optimizer parameter error in IterBasedRunner.

- docs/tutorials/index.rst
- docs/tutorials/init_cfg.md
MMCV has updated the init layer method, it is still unclear how to use init_cfg in mmdet.
Meanwhile, `backbone.pretrained` needs to be modified into `init_cfg=dict(**)` to avoid warnings.
Resolves #5209
> [Docs] add init_cfg docs

- mmdet/models/dense_heads/autoassign_head.py
Hello, I am viewing autoassign source code. I am confused about some code lines in file mmdet/models/dense_heads/autoassign_head.py. Code at line 472 ~ line 479 is puzzling, because that I think  concat_lvl_bbox_targets is just same as bbox_targets_list. right ?
See my pr, please.
> remove unnecessary code in autoassign

- tools/misc/browse_dataset.py
When using dataset wrappers, there is no `pipeline` key in `cfg.data.train`. This will cause an error when running  browse_dataset.py. This PR fixes this bug.
> Fix browse_dataset bug when using dataset wrappers

- mmdet/models/dense_heads/anchor_head.py
https://github.com/open-mmlab/mmdetection/issues/5551
There is a typo error in anchor_head.py. It causes error when use AnchorHead with default init_cfg.
Fix that typo.
> fix typo error in anchor_head.py

- configs/fast_rcnn/fast_rcnn_r101_caffe_fpn_1x_coco.py
- tests/test_models/test_forward.py
The unit test for the pretrain configuration is wrong.
model.backbone.init_cfg = None
> Fix unittest error of pretrain cfg

- mmdet/models/dense_heads/cascade_rpn_head.py
- mmdet/models/dense_heads/ga_rpn_head.py
- mmdet/models/dense_heads/rpn_head.py
There is an error in the rpn filtering minimum bbox logic.
1. Fix rpn and cascade rpn head errors of filtering minimum bbox logic
2. Modify ga rpn head to unify the writing of filtering minimum bbox logic
> Fix valid_mask logic error of rpn_head

- docs_zh-CN/get_started.md
Modify the translation of 'Docker Image'.
From `Docker 图片` to `Docker 镜像`.
> [Fix] Modify the translation of 'Docker Image'

- mmdet/models/losses/ghm_loss.py
- setup.cfg
- tests/test_models/test_loss.py
- tests/test_models/test_loss_compatibility.py
Firstly, I used `weight_reduce_loss` to rewrite the forward function and, added `reduction` key in `__init__`, the reduction defaults to mean. Meanwhile, I refactored the GHMC, GHMR forward function in `ghm_loss.py`, which make the loss function can support the key `reduction_override `.
Then I supplemented the losses test unit, to ensure that the losses of the same task can be replaced.
I have confirmed the results of GHMC and GHMR are the same as before the modification.
> [Refactor] refactor losses function, support key `reduction_override`

- configs/ssd/README.md
- configs/ssd/metafile.yml
- configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py
- mmdet/core/anchor/anchor_generator.py
- tests/test_utils/test_anchor.py
1. Support setting anchor size manually in SSDAnchorGenerator
2. Add MobileNetV2 SSD-Lite config
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.213
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.354
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.218
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.016
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.209
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.413
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.322
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.322
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | …
```
> [Feature] MobileNetV2 SSD-Lite

- mmdet/core/post_processing/bbox_nms.py
This PR improves the codes for multi_class bbox NMS by returning the global indice.
Currently [multiclass_nms](https://github.com/open-mmlab/mmdetection/blob/b9dedfdc8b660804bb31ae031a251e86a4905ade/mmdet/core/post_processing/bbox_nms.py#L7-L94) returns the local indices after batched_nms:
<https://github.com/open-mmlab/mmdetection/blob/b9dedfdc8b660804bb31ae031a251e86a4905ade/mmdet/core/post_processing/bbox_nms.py#L85-L92>
The returned indices is useless outside the function unless it's a global indice w.r.t the inputs.
The modification is quite slight: change <https://github.com/open-mmlab/mmdetection/blob/b9dedfdc8b660804bb31ae031a251e86a4905ade/mmdet/core/post_processing/bbox_nms.py#L92>
to `return dets, labels[keep], inds[keep]`
> The `multiclass_nms` should return the global indices.

- tests/test_runtime/test_config.py
When `Numclasshook` is not used in the config, the unit test for this config still runs `_check_numclasscheckhook`.
I fix it by adding checking.
> [Fix] Fix unittest for Numclasshook when it is not used.

- mmdet/datasets/pipelines/instaboost.py
add annotations for instaboost, referencing https://github.com/GothicAi/InstaBoost-pypi#instaboostconfig
```
Args:
action_candidate (tuple): action candidates. "normal", "horizontal", \
"vertical", "skip" are supported.
action_prob (tuple): corresponding action probabilities. Should be the \
same length as action_candidate.
scale (tuple): (min scale, max scale)
dx (int): the maximum x-axis shift will be (instance width) / dx
dy (int): the maximum y-axis shift will be (instance height) / dy
theta (tuple): (min rotation degree, max rotation degree)
color_prob (float): probability of images for color augmentation
heatmap_flag (bool): whether to use heatmap guided
aug_ratio (float): probability of applying this transformation
```
> add annotations for instaboost

- .dev_scripts/test_init_backbone.py
- configs/mask_rcnn/mask_rcnn_r101_caffe_fpn_mstrain-poly_3x_coco.py
- configs/mask_rcnn/mask_rcnn_r101_fpn_mstrain-poly_3x_coco.py
- configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_poly_1x_coco_v1.py
- configs/mask_rcnn/mask_rcnn_x101_32x4d_fpn_mstrain-poly_3x_coco.py
- configs/mask_rcnn/mask_rcnn_x101_64x4d_fpn_mstrain-poly_3x_coco.py
- configs/regnet/mask_rcnn_regnetx-1.6GF_fpn_mstrain-poly_3x_coco.py
- configs/regnet/mask_rcnn_regnetx-400MF_fpn_mstrain-poly_3x_coco.py
- configs/regnet/mask_rcnn_regnetx-4GF_fpn_mstrain-poly_3x_coco.py
- configs/regnet/mask_rcnn_regnetx-800MF_fpn_mstrain-poly_3x_coco.py
Due to moving the `model.pretrained` into `model.backbone.init_cfg`, this is a large-scale changes in config file. We add a test unit to check whether the backbone is successfully loaded the pretrained checkpoint. Now, we support check `ResNet, ResNext, VGG, Darknet` .etc.
We traversed all potential config files under the `config` directory. we ignore the folder  `'_base_', 'common'` because it does not contain the model. Meanwhile, we ignore the folder `legacy_1.x` due to it does not belong to mmdet 2.X. 
First, using `mmcv._load_checkpoint` to load the checkpoint without loading models.
Then, using `build_detector` to build models, and using `model.init_weights()` to initialize the parameters.
Finally, assert weights and bias of each layer loaded from pretrained checkpoint are equal to …
> [Fix] Fix some backbone init from pretrained checkpoint error in config file

- mmdet/core/post_processing/bbox_nms.py
The device of labels in multicalss_nms is CPU while other variables are on GPU.
Now put it on GPU.
> [Fix] Fix the device of label in multiclass_nms

- .gitignore
- MANIFEST.in
- README.md
- README_zh-CN.md
- setup.py
- add MIM introduction in README
- modify setup.py to support mim as mmdet entry point
> Support MIM

- configs/yolox/yolox_s.py
- mmdet/models/dense_heads/yolox_head.py
YOLOX uses PyTorch's default Kaiming uniform init, but in mmdet, the default weight init function of Conv module is Kaiming normal.
This PR fixes this.
> [Fix]: Change YOLOX init weights to PyTorch default.

- mmdet/models/losses/cross_entropy_loss.py
- tests/test_models/test_loss.py
The `CrossEntropyLoss` has no interface `ignore_index`, which makes it inconvenient to complete the segmentation task.
> [Enhance] Add ignore_index to CrossEntropyLoss

- mmdet/models/utils/__init__.py
- mmdet/models/utils/conv_upsample.py
- tests/test_models/test_utils/test_conv_upsample.py
Convupsample performs 2x upsampling after Conv.
There are several `ConvModule` layers. In the first few layers, upsampling will be applied after each layer of convolution. The number of upsampling must be no more than the number of ConvModule layers.
`num_layer` means the number of convolutional layers.  
`num_upsample` means the number of upsampling, it must be no more than `num_layers`.
> [Feature] Add ConvUpsample module and its unit test

- .github/workflows/build.yml
- docs/get_started.md
- docs_zh-CN/get_started.md
- requirements/runtime.txt
When publishing this package to PyPi, PyPi will reject this package because it includes the URL of `panopticapi` outside PyPi.
Remove `panopticapi` from the runtime.txt and add documentation to tell users to manually install panoptic API if they want to use it.
N/A
N/A
3. If the modification has potential influence on downstream …
> [Fix]: fix panoptic dependency issue when publishing to pypi

- mmdet/models/utils/__init__.py
- mmdet/models/utils/misc.py
- tests/test_models/test_utils/test_model_misc.py
Actually, this function can not only upsample the input Tensor but also downsample the input.
So we should rename it to reflect its real function.
> [Enhance] Rename the function `upsample_like` to `interpolate_as`

- mmdet/core/mask/structures.py
resolve #5106 
```
630                 for p in poly_per_obj:
631                     p = p.copy()
--> 632                     p[0::2] *= w_scale
633                     p[1::2] *= h_scale
634                     resized_poly.append(p)
UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```
Remove all in-place operation
> fix casting error

- configs/ssd/README.md
- configs/ssd/metafile.yml
The VGG SSD models were trained with a buggy version of mmdet which can cause label disordering. That bug was fixed after #5243 while the models were trained before that. 
Retrained models is in this PR
> [Fix]: Update correct SSD models.

- mmdet/datasets/pipelines/formating.py
In order to reduce the series of hidden dangers caused by discontinuous memory
When ONNX's detection model encounters discontinuous data, there will be abnormal performance, and the source is in this ImageToTensor tool. The transpose operation makes the memory discontinuous, which will not affect the operation of pytorch but will affect ONNX. In order to eliminate the risk, the function can directly output a continuous tensor.
make
results[key] = to_tensor(img.transpose(2, 0, 1))
to
results[key] = (to_tensor(img.transpose(2, 0, …
> make output result of ImageToTensor contiguous

- docs/conventions.md
- mmdet/models/roi_heads/bbox_heads/bbox_head.py
- mmdet/models/roi_heads/cascade_roi_head.py
- mmdet/models/roi_heads/htc_roi_head.py
- mmdet/models/roi_heads/scnet_roi_head.py
- mmdet/models/roi_heads/standard_roi_head.py
The bbox_label got an extra slice in `simple_test` in some roi_head files, so the shape of bbox_label passed to the function is incorrect and this function throw an error, so these models cannot proceed correctly. Details are described in #5817. 
Remove the extra slice of bbox_label. 
Closes #5817
> [Fix] Fix roi_head

- mmdet/datasets/utils.py
CLASSSES to CLASSES
Correct typo
I changed CLASSSES to CLASSES in a docstring of  NumClassCheckHook
> Fixed typo

- docs/tutorials/pytorch2onnx.md
- tools/deployment/pytorch2onnx.py
Many users ask for supporting export raw models without post-process. This is useful when they want to convert the onnx to other formats such as caffe and ncnn, and implement post-process by themselves.
When run `tools/deployment/pytorch2onnx.py`, add `--skip-postprocess`. For example:
```
python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py \
checkpoints/yolov3_mobilenetv2_mstrain-416_300e_coco_20210718_010823-f68a07b3.pth --output-file \
yolov3_mobilenetv2_no_post.onnx --shape 416 416 --skip-postprocess
```
Exporting models without post-process only works on some one-stage models.
> [Feature]: Support export onnx models without post process.

- configs/htc/htc_r50_fpn_1x_coco.py
- configs/scnet/scnet_r50_fpn_1x_coco.py
- mmdet/models/roi_heads/mask_heads/fused_semantic_head.py
Now we support `ignore_index` in `CrossEntropyLoss`.
We should refactor the loss function in HTC and SCNet to use our own CrossEntropyLoss instead of PyTorch.
> [Enhance] Refactor the loss function in HTC and SCNet

- mmdet/models/backbones/hrnet.py
- tests/test_models/test_backbones/test_hrnet.py
The interface `multiscale_output` is defined in `_make_stage` but never used.
HRNet should be allowed to output a one-level feature in stage 4.
So we should use `multiscale_output` while making stage 4 and add interface  `multiscale_output` in the initialization function of HRNet.
Add unit test for HRNet in this PR, too.
> [Fix] The interface `multiscale_output` is defined but not used 

- mmdet/models/roi_heads/point_rend_roi_head.py
- mmdet/models/roi_heads/test_mixins.py
Logger.warning() will report a warning message every time during inference.
We should fix it.
> [Fix] Use `warnings.warn` instead of `logger.warning`

- mmdet/models/dense_heads/yolox_head.py
This bug is triggered only when batch_size > 1. For example, given batch_size = 20,
the tensor on the left side has shape [20, x, 4], while the tensor on the right size
has shape [20, 4]
fix a yolox bug when applying bbox rescaling in test mode.
reshape a tensor so that the assignment can be carried on successfully. (code had been tested on both batch_size = 1 and batch_size > 1)
1. Pre-commit or other linting tools are used to fix the …
> [Fix] fix a yolox bug when applying bbox rescaling in test mode (reopened)

- mmdet/apis/train.py
If the priority of `EvalHook` is higher than `IterTimerHook`, it will cause `KeyError: 'data_time'` (https://github.com/open-mmlab/mmsegmentation/issues/758, https://github.com/open-mmlab/mmcv/issues/1261).
Since the time key will add to the output of `log_buffer` after `IterTimeHook`, the `TextLoggerHook` will print the time and `data_time` at the same time.
This PR is based on https://github.com/open-mmlab/mmsegmentation/pull/766.
This PR will be useful for models that uses `IterBasedRunner`, e.g., yolof.
Set the priority of `EvalHook` to `LOW`.
No
> [Fix] Fix the log error when `IterBasedRunner` is used

- mmdet/core/evaluation/bbox_overlaps.py
- mmdet/core/evaluation/mean_ap.py
- mmdet/core/evaluation/recall.py
- mmdet/datasets/voc.py
- tests/test_metrics/test_box_overlap.py
- tests/test_metrics/test_mean_ap.py
- tests/test_metrics/test_recall.py
In the official [metric implementation](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCdevkit_18-May-2011.tar) of VOC dataset, it adopts the  Legacy coordinate system in mmdet 1.x, which means h, w should be computed as `x2 - x1 + 1` and `y2 - y1 + 1`.
I add argument `Legacy_coordinate` to `eval_map`， `tpfp_default` and `tpfp_imagenet`，`bbox_overlaps`  to control whether to use legacy coordinate system when caculate the width and length.
None
<!DOCTYPE html><meta http-equiv="content-type" content="text/html; charset=utf-8">
before/after | faster
-- | --
mAP | 79.5/79.6
recall | 93.4/93.5
> Use legacy coordinate in metric of VOC

- mmdet/datasets/pipelines/transforms.py
Bug: dtype of bbox change to float64 after multiply by the affine matrix.
This PR fixes this.
resolve #5870
> [Fix]: Fix dtype of bbox in RandomAffine.

- tools/misc/browse_dataset.py
browse_dataset script is very useful to check your dataset, have a look to a few images and see if the pipeline seems to be ok. But not all datasets are supported, this PR is to make the script support concatenated datasets too.
One method in the script skips some pipeline steps. Now if the config is a list, it will skip them in the pipelines of its elements.
It's compatible with previous version.
Run browse dataset for a concatenated dataset configuration.
> Adapt browse_dataset for concatenated datasets.

- README.md
- README_zh-CN.md
‘ArXix’ in README is confusing
Fix ArXix to ArXiv in README
2. The modification is covered by …
> [Docs] Fix ArXix to ArXiv in README

- mmdet/models/utils/transformer.py
- tests/test_models/test_utils/test_transformer.py
`PatchEmbed` and `PatchMerging` are basic modules that would be used in many transformer methods, such as PVT and Swin
At the same time, `AdaptivePadding` is an essential feature to deal with the dynamic shape in detection. 
- Add `AdaptivePadding` to avoid lost pixel of input when doing the patchembed or patchmerge. 
- Add`PatchEmbed` and `PatchMerging`  to `/mmdet/models/utils/transformer.py` and add the corresponding unitests.
- Always apply adaptive padding first before doing the `PatchEmbed` and `PatchMerging` to deal with the dynamic shape in detection.
None
> [Feature]Add `PatchEmbed` and `PatchMerging` with `AdaptivePadding`

- mmdet/models/dense_heads/yolact_head.py
When `workflow = [('train',1),('val',1)]` is set, YOLACT will report an error.
Resolve:  https://github.com/open-mmlab/mmdetection/issues/5978
Resolve: https://github.com/open-mmlab/mmdetection/issues/5362
> YOLACT supports val workflow

- mmdet/models/dense_heads/centernet_head.py
Fix scores not contiguous in centernet_head.
Add nms_cfg in model to enable nms:
```py
model = dict(
type='CenterNet',
...
test_cfg=dict(
topk=1000, local_maximum_kernel=1, max_per_img=1000,
nms_cfg=dict(iou_threshold=0.01)))
```
Then run: `result = inference_detector(model, image_path)`
```
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
- GCC 7.3
- C++ Version: 201402
- Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v2.1.2 (Git …
```
> Fix scores not contiguous in centernet_head.

- mmdet/models/detectors/rpn.py
'**kwargs' parameters haven't passed to mmcv.imshow_bboxes() in show_result() of mmdetection/mmdet/models/detectors/rpn.py
close #6033
> Fix missing '**kwargs' parameters passing to imshow_bboxes()

- tools/analysis_tools/get_flops.py
Add a parameter named `size_divisor`, which will pad the input image can divisible by size_divisor, -1 means do not use size divisor to padding the input image. 
Can avoid some potential bugs such as in HRNet:
The size of input `h = 201`, using 2x downsample and get `h_down = 100`. Then using 2x upsample and get `h_up = 200`. 
**`h_up` cannot match `h`**.
Relate Issue:
#4536
> [Fix] Add size divisor in get flops to avoid some potential bug

- mmdet/datasets/pipelines/transforms.py
Fix two errors of Masaic.
1. self.img_scale denotes (h,w). The "self.img_scale[1]"  should be changed to "self.img_scale[0]" in the formula of "y2" at line 2134 and 2135 when " loc == 'bottom_left' ". 
```python
min(self.img_scale[0] * 2, center_position_xy[1] +
img_shape_wh[1])
```
2. To avoid NaN loss during training. The code should get rid of the mosaic_bboxes with small area (even zero area). In this submission, after line 2081, the bboxes with a short side smaller than 3 are abandoned.
```python
mosaic_filter = np.prod(mosaic_bboxes[:, 2:4] - \
mosaic_bboxes[:, 0:2] > 2,  axis=1) == 1
mosaic_bboxes = mosaic_bboxes[mosaic_filter]
mosaic_labels = mosaic_labels[mosaic_filter]
```
> [Enchance] Add filter rules of Mosaic transform

- tools/deployment/pytorch2onnx.py
The input order should be bs x c x h x w
Fix #6096 Simple change to the names of the dynamic shapes in onnx
The input order should be `bs x c x h x w` NOT `bs x c w x h`
> Change input order -- Fixing #6096

- docs_zh-CN/conventions.md
This PR is for chinese version of conventions.md
> [Docs] Add Chinese version of conventions

- configs/yolox/yolox_s_8x8_300e_coco.py
- configs/yolox/yolox_tiny_8x8_300e_coco.py
- mmdet/core/hook/sync_random_size_hook.py
- mmdet/datasets/dataset_wrappers.py
- tests/test_utils/test_hook.py
Fixed the dynamic shape bug of SyncRandomSizeHook following to https://github.com/open-mmlab/mmdetection/pull/5925. When dataloader is enabled for multiple processes, SyncRandomSizeHook cannot changing the size at a fixed iteration interval.
Modified to change the size of every fixed epoch interval.
> fix dynamic_shape bug of SyncRandomSizeHook

- mmdet/models/dense_heads/base_mask_head.py
- mmdet/models/detectors/single_stage_instance_seg.py
We need some general-enough BaseClasses for One-Stage Instance Segmentation, Such as `SingleStageInstanceSegmentor` compare to One-Stage detector and `BaseMaskHead` compare to `BaseDenseHead`
This base class will be used in the following methods  to prove its versatility
> [Feature]Add base one-stage segmentor

- mmdet/models/plugins/dropblock.py
Add `extra_repr` in DropBlock layer to get details in the model print.
```
print(model)
(dropblock1): DropBlock()
(dropblock1): DropBlock(drop_prob=0.1, block_size=7, warmup_iters=2000)
```
Add `extra_repr` in DropBlock layer
> extra_repr for DropBlock layer

- mmdet/apis/inference.py
In the multi-GPU environment, `init_detector()` may have potential memory leak or crash with a device error.
Assume we have a model whose weights was saved in `cuda:0` during training. And we want to load this model on a 2-GPU machine with the following code:
```python
from mmdet import apis
model = apis.init_detector(config, checkpoint, device='cuda:1')
```
See line 42, 43 in `mmdet/apis/inference.py`. `init_detector()` won't remap the location. So, the checkpoint will be loaded to `cuda:0` (The device where checkpoint was …
> Always map location to cpu when load checkpoint

- mmdet/models/backbones/pvt.py
- mmdet/models/backbones/swin.py
Implementation of SwinTransformer and PVT use trunc_normal_init incorrectly which may decrease the performance when training from scratch.
The use of trunc_normal_init of SwinTransformer and PVT
> [BugFixed] fix wrong trunc_normal_init use

- docs/useful_tools.md
- tools/analysis_tools/confusion_matrix.py
Many users ask for supporting confusion matrix calculation. This PR implemented this feature.
Add a script to calculate and draw confusion matrix.
First, run tools/test.py to save the .pkl detection results.
Then, run
```shell
python tools/analysis_tools/confusion_matrix.py ${CONFIG}  ${DETECTION_RESULTS}  ${SAVE_DIR} --show
```
will get this plot
If so, please describe how it breaks the compatibility and how the downstream …
> [Feature]: Support plot confusion matrix.

- mmdet/datasets/coco.py
In order to facilitate the analysis, we need to save coco summarize print information to the logger
Redirect output stream using context.
> Save coco summarize print information to logger

- README.md
- README_zh-CN.md
- docs/conf.py
- docs_zh-CN/conf.py
> Include mmflow in readme

- mmdet/core/export/pytorch2onnx.py
- tools/analysis_tools/analyze_results.py
- tools/analysis_tools/eval_metric.py
- tools/analysis_tools/get_flops.py
- tools/analysis_tools/test_robustness.py
- tools/misc/browse_dataset.py
- tools/misc/print_config.py
- tools/test.py
- tools/train.py
According to #6543, MMCV already supports custom_imports since PR open-mmlab/mmcv#606. There is no need to manually handle custom_imports after calling `Config.fromfile`. So the code like below should be cleaned.
```python
if cfg.get('custom_imports', None): 
from mmcv.utils import import_modules_from_strings 
import_modules_from_strings(**cfg['custom_imports']) 
```
1. Search all files with related code
List of files with related code:
- `mmdet/core/export/pytorch2onnx.py`
- `tools/analysis_tools/analyze_results.py`
- `tools/analysis_tools/eval_metric.py`
- `tools/analysis_tools/get_flops.py`
- `tools/analysis_tools/test_robustness.py`
- `tools/misc/browse_dataset.py`
- `tools/misc/print_config.py`
- `tools/test.py`
- `tools/train.py`
2. delete the code in the list.
> Clean unnecessary custom_imports in entrypoints

- mmdet/core/bbox/samplers/ohem_sampler.py
Since seesaw loss's return_dict does not contain the key `loss_cls`, `OHEMSampler` does not work with seesaw loss.
Make the key for return_dict to be controllable.
By making default key for return_dict be `loss_cls`, users only need to change the key for return_dict for some specific losses like seesaw loss.
Specify the key for loss's return_dict like below:
```python
sampler=dict(
type='OHEMSampler',
num=512,
pos_fraction=0.25,
neg_pos_ub=-1,
add_gt_as_proposals=True,
loss_key='loss_cls_objectness',
),
```
> Make OHEM work with seesaw loss

- configs/pascal_voc/ssd300_voc0712.py
- configs/pascal_voc/ssd512_voc0712.py
- configs/ssd/ssd300_coco.py
- configs/ssd/ssd512_coco.py
- configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py
- configs/yolact/yolact_r50_1x8_coco.py
- configs/yolo/yolov3_d53_320_273e_coco.py
- configs/yolo/yolov3_d53_mstrain-416_273e_coco.py
- configs/yolo/yolov3_d53_mstrain-608_273e_coco.py
- configs/yolo/yolov3_mobilenetv2_320_300e_coco.py
- configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py
- mmdet/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform/test_transform.py
Speed up training and reduce memory cost when using PhotoMetricDistortion.
I benchmarked yolov3_mobilenetv2_mstrain-416_300e_coco
Training time before: 40h35m
Training time now: 32h39m
Speed up about 8 hours.
COCO metric before:
bbox_mAP: 0.2390, bbox_mAP_50: 0.4540, bbox_mAP_75: 0.2260, bbox_mAP_s: 0.1060, bbox_mAP_m: 0.2510, bbox_mAP_l: 0.3490
COCO metric now:
bbox_mAP: 0.2390, bbox_mAP_50: 0.4560, bbox_mAP_75: 0.2280, bbox_mAP_s: 0.0990, bbox_mAP_m: 0.2510, bbox_mAP_l: 0.3560
Almost no difference on mAP.
1. Support uint8 …
> [Enhance]: Optimize augmentation pipeline to speed up training.

- mmdet/apis/train.py
Since the function `register_training_hooks()` adds an argument `custom_hooks_config` in mmcv, there is no need to implement it again in mmdet/apis/train.py.
Remove some code in `mmdet/apis/train.py`, such as # user-defined hooks.
> [Refactor] Remove some code in `mmdet/apis/train.py`

- .github/workflows/build.yml
- README.md
- README_zh-CN.md
drop support for pytorch 1.3.1.
> drop support for pytorch 1.3.1.

- mmdet/models/backbones/pvt.py
- mmdet/models/backbones/swin.py
`constant_init` and `normal_init` in mmcv can only initialize nn.Module with weight and bias.
Fix `init_weights` in both Swin and PVT
None
> [Fix] Fix init weights in Swin and PVT.

- mmdet/datasets/dataset_wrappers.py
- tests/test_data/test_datasets/test_dataset_wrapper.py
When the parameter dataset in MultiImageMixDataset is ConcatDataset/RepeatDataset/ClassBalancedDataset and mixup is added in the pipeline, the get_indexes in mixup will crash since there are no get_ann_info in ConcatDataset/RepeatDataset/ClassBalancedDataset.
I submitted a PR before, but it was closed by me. I added a unit test on the basis of the previous PR
Related PR：
https://github.com/open-mmlab/mmdetection/pull/6352
https://github.com/open-mmlab/mmdetection/pull/6516
If this …
> Add 'get_ann_info' to dataset_wrappers

- mmdet/core/bbox/__init__.py
- mmdet/core/bbox/transforms.py
- mmdet/datasets/pipelines/transforms.py
Support `bbox_clip_border` argument for the data augmentations of YOLOX.
Add `bbox_clip_border` argument for `Mosaic`, `MixUp` and `RandomAffine` augmentations. The argument allow the augmentations not to clip the bboxes based on the image border, just like [`Resize`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L57).
No BC-breaking
Just set `bbox_clip_border=False` in these augmentations to not clip the bboxes. …
> Support `bbox_clip_border` for the augmentations of YOLOX

- mmdet/core/bbox/assigners/sim_ota_assigner.py
> [Fix] Fix SimOTA with no valid bbox.

- requirements/runtime.txt
Windows installation (compilation settings) were missing on the original pycocotools package so we started to using pycocotools-windows package for windows.
Now Windows installation is fixed on the original pycocotools pypi package, so we can update the dependency.
Fixes https://github.com/open-mmlab/mmdetection/pull/4939#issuecomment-997632171
> switch back to original pycocotools

- mmdet/datasets/lvis.py
Fix lvis classwise test error.
Add [] for catId to to be compatible with lvis API.
> [Fix]Fix lvis classwise test error.

- mmdet/datasets/pipelines/formating.py
Now, the padding value is set to 0 by default, but in `gt_semantic_seg` it needs to be 255.
So I modified the `DefaultFormatBundle` and added `padding_value` in the `DataContainer`.
In batch collating, the `DataContainer` will fill the data with the `padding_value`.
> [Fix] Support setting pad_val in batch collating

- mmdet/models/backbones/swin.py
the format of the  frozen_stages default value is different from others in the SwinTransformer class doc
-1 means not freezing any parameters. ---> Default: -1 (-1 means not freezing any parameters).
> [Docs] fix the format of default value in SwinTransformer class doc

- README.md
- README_zh-CN.md
- docker/serve/Dockerfile
- docs/en/changelog.md
- docs/en/get_started.md
- mmdet/__init__.py
- mmdet/version.py
Bump to version v2.20.0.
- Support [TOOD](configs/tood/README.md): Task-aligned One-stage Object Detection (ICCV 2021 Oral) (#6746)
- Support resuming from the latest checkpoint automatically (#6727)
- Fix yolox ci failed (#6864)
- Fix wrong bbox loss_weight of the PAA head (#6744)
- Fix the padding value of `gt_semantic_seg` in batch collating (#6837)
- Fix test error of lvis when using `classwise` (#6845)
- Avoid get_local_path bc-breaking (#6719)
- Fix norm sync bug (#6852)
- Cancel previous runs that are not completed in the workflow (#6772)
- Use pycocotools directly no matter what platform it is (#6838)
- Add unit test for SimOTA with no valid bbox (#6770)
- Use precommit to check readme (#6802)
- Support selecting GPU-ids in non-distributed testing time (#6781)
- Update …
> Bump to version v2.20.0

- tools/train.py
_I know the title is a bit frivolous, but I think it satisfies this PR._
Thanks for your excellent works, the `mmdetection` is a very flexible and powerful deep learning framework.
Currently, I was implementing the popular YOLOv5 model with `mmdetection`, but when I try to train my new model, I found out that the training speed is much slower than the official implementation of YOLOv5 (almost ~4x slower). I can't afford that time overhead. So I digged into it for some day and notice that the `mmdetection` always **spawn** thousands of threads for data preprocessing. Compare to `mmdetection`, offical YOLOv5 only **fork** hundreds of threads (~2000 v.s. 400). Because of such insane number of threads, almost half of the CPU workload is occupied by the kernel, which used to manager the …
> Add A Single Line to Save Your Life

- configs/_base_/default_runtime.py
- tools/train.py
This PR continues on #6867.
Not only limit the opencv multi-processing but also set OMP and MKL threads to 1 if not set in the environment.
Also, switch the start method from spawn to fork to speed up the start time.
system info:
```
sys.platform: linux                                                                                                                                                                                                                                    
Python: 3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]                                                                                                                                                                                            
CUDA available: True …
```
> [Enhance] Continue to speed up training.

- docker/Dockerfile
Fix "BadZipFile Error" when build docker. "BadZipFile Error" is same as [mmcv #1352](https://github.com/open-mmlab/mmcv/issues/1352)
```
(base) ➜  mmdetection git:(master) docker build -t mmdet docker/
Sending build context to Docker daemon  7.168kB
Step 1/15 : ARG PYTORCH="1.6.0"
Step 2/15 : ARG CUDA="10.1"
Step 3/15 : ARG CUDNN="7"
Step 4/15 : FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
---> bb833e4d631f
Step 5/15 : ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
---> Using cache
---> db65124ef61d
Step 6/15 : ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
---> Using cache
---> d83a99117aa2
Step 7/15 : ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
---> Using cache
---> 7bfd23a73348
Step 8/15 : RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git …
```
> Fix BadZipFile Error when build docker

- mmdet/datasets/voc.py
In VOCDdataset, the first item of output is `AP50`. When setting `save_best` as `auto` in evaluation, the `EvalHook` can not match a rule for `AP50` and will raise an error #7061. Thus, I put the `mAP` at the front of OrderedDict in VOCDataset. 
Add `eval_results.move_to_end('mAP', last=False)` in VOCDataset.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
> [Fix] Put the `mAP` at the front of OrderedDict in VOCDataset

- README.md
According to issue #6868, I created a table that makes the list of model zoo easy to understand. I hope this makes it easier for everyone to understand the models that mmdetection supports. For similar documentation, I referred to the [Overview of Kit Structures in Paddle Detection](https://github.com/PaddlePaddle/PaddleDetection#overview-of-kit-structures).  **At a minimum, separating Object Detection and Instance Segmentation makes it easier for users to understand the models supported by mmdetection.**
The list of Benchmark and model zoo in `README.md` is changed to table.
The Chinese version of the document can also be changed. We should also change the list of model zoos in the link (`docs/en/model_zoo.md`).
Only the models that exist in config are listed. Not all features of …
> Add Overview of Benchmark and Model Zoo

- mmdet/models/dense_heads/autoassign_head.py
- mmdet/models/dense_heads/fcos_head.py
FCOS and AutoAssign cannot run with PyTorch 1.10. 
Error message:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 4, 20, 20]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead.
```
After using  `with torch.autograd.set_detect_anomaly(True):` to debug and find out that it was caused by the ReLU in bbox branch.
Replace `F.relu(bbox_pred)` with `bbox_pred.clamp(min=0)`
> [Fix] Fix bbox clamp in pt1.10

- mmdet/models/dense_heads/tood_head.py
- mmdet/models/utils/__init__.py
- mmdet/models/utils/misc.py
- tests/test_models/test_dense_heads/test_tood_head.py
- tests/test_models/test_utils/test_model_misc.py
The training of TOOD often encounters None gradient during backpropagation, which would further cause None tensors in the next training step. Some issues in the original repo (https://github.com/fcjian/TOOD/issues/11) might be also due to this error. The problem is caused by the naive implementation of sigmoid geometric mean function ``cls_score = (cls_logits.sigmoid() * cls_prob.sigmoid()).sqrt()``. This output might be 0 if  ``cls_logits`` or ``cls_prob`` is a low negative value, which causes either inf grad of none grad …
> Fix None grad problem during training TOOD by adding SigmoidGeometricMean

- mmdet/datasets/dataset_wrappers.py
- tests/test_data/test_datasets/test_dataset_wrapper.py
The recent new feature https://github.com/open-mmlab/mmdetection/pull/6716 introduced a new assumption on the `PALETTE` attribute in all dataset wrappers, which breaks external references to these wrappers without such an attribute in their datasets. This PR turns this requirement optional.
Dataset wrappers take `PALETTE` from their dataset classes only if available, or None will be used to fill out the attribute otherwise.
None
> [Fix] Relax the requirement of PALETTE in dataset wrappers

- mmdet/core/bbox/assigners/max_iou_assigner.py
fix typos in comment
Replace `bbox B` witth `bbox 2`.
In the previous content, `bbox B` was not mentioned.
bbox A's assigned_gt_inds will be overwritten to be bbox 2 instead of bbox B.
> fix typos in comment

- mmdet/models/dense_heads/paa_head.py
Worried about "Fix wrong bbox loss_weight of the PAA head (#6744)" in MMDetection V2.20.0.
According to the PAA's source code, it seems that the authors calculated the cls_loss and reg_loss with the same weight (always equal to 1.0) before reassignment, and calculated the final loss with different loss_weight
https://github.com/kkhoot/PAA/blob/master/paa_core/modeling/rpn/paa/loss.py#L306
https://github.com/kkhoot/PAA/blob/master/paa_core/modeling/rpn/paa/loss.py#L356
Before reassignment, always set loss_weight as 1.0 (maybe it will lead to some confusion for setting all losses as self.loss_cls.loss_weight)
> [Fix] Keep the same weights before reassign in the PAA head

- mmdet/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform/test_transform.py
When using MixUp pipeline transform with the filter boxes enabled (skip_filter=False) there is the following failing case: when all boxes are marked to be removed the filtering step is skiped and all boxes are kept (opposite behavior).
Removed the conditional statment causing the skip.
Extended MixUp unit test adding the case that was failing in the same fashion as [RandomAffine test](https://github.com/open-mmlab/mmdetection/blob/dev/tests/test_data/test_pipelines/test_transform/test_transform.py#L871-L894)
> [Fix] Fix MixUp transform filter boxes failing case

- docs/en/get_started.md
- docs/zh_cn/get_started.md
- requirements/albu.txt
Continue to follow https://github.com/open-mmlab/mmdetection/pull/5868.
By default, installing `albumentations` by pip has `opencv-python-headless` dependency even if `opencv-python` has already been installed. This could cause different opencv versions installed in the environment and lead to unexpected errors. https://github.com/open-mmlab/mmdetection/pull/5868 has fixed this potential issue, but albumentations has updated their installing way, which changes `pip install albumentations --no-binary imgaug,albumentations` to `pip install -U albumentations --no-binary qudida,albumentations`. See its [docs](https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies) for details.
If simply use `pip install albumentations>=0.3.2 --no-binary qudida,albumentations` …
> [Fix] update albumentations installed way

- tools/analysis_tools/confusion_matrix.py
Fixes #6965 
A ValueError is raised on confusion_matrix.py tool when the confusion matrix contains NaN values.
Commonly happens when you generate results.pkl with a validation/test dataset where some categories do not have a single datapoint.
Reproduced the error using a very small subset of COCO val2017 where most categories are missing images/annotations.
Substituting NaN values for -1.
Assigning -1 makes the confusion matrix figure look like this (showing subregion):
The categories that don't have any datapoints are simply rendered as white empty cells.
> [Fix] confusion_matrix.py analysis tool NaN errors

- demo/MMDet_Tutorial.ipynb
- docs/en/get_started.md
- docs/zh_cn/get_started.md
- requirements/albu.txt
- tools/deployment/onnx2tensorrt.py
Fix a broken link in Colab tutorial.
Replace the broken doc to a valid link.
> Fix broken colab link

- mmdet/models/backbones/csp_darknet.py
Hi, Thanks for your great repo. It's been very helpful for my project. I deeply appreciate it!
In mmdet/models/backbones/csp_darknet.py, I found that the description for deepen_factor and widen_factor were interchanged like below. 
```python
"""
deepen_factor (float): Depth multiplier, multiply number of
channels in each layer by this amount. Default: 1.0.
widen_factor (float): Width multiplier, multiply number of
blocks in CSP layer by this amount. Default: 1.0.
"""
```
while they were being used as 
```python
in_channels = int(in_channels * widen_factor)
out_channels = int(out_channels * widen_factor)
```
```python
num_blocks = max(round(num_blocks * deepen_factor), 1)
```
The description should be fixed like below
```python
"""
deepen_factor (float): Depth multiplier, multiply number …
```
> [Fix] Fix description for args in CSPDarknet

- configs/maskformer/README.md
- configs/maskformer/maskformer_r50_mstrain_16x1_75e_coco.py
- mmdet/core/bbox/assigners/__init__.py
- mmdet/core/bbox/assigners/mask_hungarian_assigner.py
- mmdet/core/bbox/match_costs/__init__.py
- mmdet/core/bbox/match_costs/match_cost.py
- mmdet/core/bbox/samplers/__init__.py
- mmdet/core/bbox/samplers/mask_pseudo_sampler.py
- mmdet/core/bbox/samplers/mask_sampling_result.py
- mmdet/models/dense_heads/__init__.py
- mmdet/models/dense_heads/maskformer_head.py
- mmdet/models/detectors/__init__.py
- mmdet/models/detectors/maskformer.py
- mmdet/models/losses/dice_loss.py
- mmdet/models/plugins/__init__.py
- mmdet/models/plugins/pixel_decoder.py
- mmdet/models/utils/__init__.py
- mmdet/models/utils/panoptic_gt_processing.py
- tests/test_models/test_dense_heads/test_maskformer_head.py
- tests/test_models/test_forward.py
- tests/test_models/test_loss.py
- tests/test_models/test_plugins.py
- tests/test_utils/test_assigner.py
Add MaskFormer to mmdet. The older one (#6607 ) is too messy, so I make a new one.
- panoptic single stage segmentor
- maskformer segmentor
- maskformer head
- mask hungrarian assigner
- match cost: BinaryDiceCost, MaskFocalLossCost
- mask pseudo sampler, mask sample result (copy from  https://github.com/ZwwWayne/K-Net/blob/main/knet/det/mask_pseudo_sampler.py)
- one config files: maskformer_r50_mstrain_16x1_75e_coco.py
4. The documentation has been …
> [Feature] Add Maskformer to mmdet

- tools/deployment/onnx2tensorrt.py
- tools/deployment/pytorch2onnx.py
- tools/deployment/test.py
Related PR https://github.com/open-mmlab/mmclassification/pull/697
Motivation
Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future.
Modification
Add deprecation message in deployment tools.
Used package [colorama](https://github.com/tartley/colorama#colored-output)[](https://user-images.githubusercontent.com/28671653/154436568-9b36c248-812a-402f-bef8-5631ed8abd7a.png) to print cross-platform colored text.
BC-breaking (Optional)
None
Use cases (Optional)
And the message would look like it in Ubuntu18.04 terminal:
> Add deprecation message for deploy tools

- .github/workflows/build.yml
- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/zh_cn/get_started.md
- mmdet/core/bbox/assigners/assign_result.py
- mmdet/core/bbox/samplers/sampling_result.py
- mmdet/models/backbones/csp_darknet.py
- requirements/albu.txt
- tests/test_data/test_datasets/test_common.py
- tests/test_data/test_datasets/test_custom_dataset.py
- tests/test_utils/test_misc.py
- tools/deployment/onnx2tensorrt.py
> Add CI for windows

- mmdet/apis/inference.py
- mmdet/models/detectors/maskformer.py
1. support visualization for maskformer
2. Modified init_detector to be Compatible with models that do not contain `pretrained`.
demo:
> Maskformer Visualization

- .github/workflows/build.yml
- tests/test_data/test_datasets/test_common.py
Fix https://github.com/open-mmlab/mmdetection/issues/7269
- Fix and simplify `test_dataset_init`
- Fix CI: `mmcv: 1.10` == `mmcv: 1.1` causes a wrong URL https://download.openmmlab.com/mmcv/dist/cpu/torch1.1/index.html
> Fix VOC unit test not to remove data directory

- mmdet/datasets/custom.py
The motivation of this PR is to be able to use `self.file_client` in `self.get_classes` function instead of repeatedly creating `file_client` in `self.get_classes`.
1. CustomDataset
- Adjust the order of `self.get_classes` and `mmcv.FileClient`. Get `self.file_client` before `self.get_classes`.
No.
3. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
4. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
5. The documentation has been modified accordingly, like docstring or example tutorials.
> [Fix] Adjust the order of get_classes and FileClient.

- README.md
- tools/test.py
1. maskformer NeurIPS'2019 -> NeurIPS'2021 in readme. 
2. modified to be compatible with models which does not support pretrained.
> update readme and pretrained related

- README.md
- README_zh-CN.md
This PR update colab tutorials. The colab environment has been changed significant and at the release time mmcv-full does not have pre-built packages. So we update the colab tutorials to use the newest pytorch versions with pre-built mmcv-full packages. 
The modification can also resolve the following issues since the tutorials have been verified with no problems:
- resolve https://github.com/open-mmlab/mmdetection/issues/6909
- resolve https://github.com/open-mmlab/mmdetection/issues/7307
- resolve …
> [Enhancement]: Update colab tutorials

- mmdet/models/dense_heads/ssd_head.py
When use a input_size != 512, error will incur. Related issue #7264 
So we set `unmap_results = True` in ssd_head to be compalible with various input_size.
I ran a ssd_512 after set `unmap_results = True` for three times, results are 29.4,  29.3,  29.5 mAP.  And I ran two times for `unmap_results = False`, results are 29.5, 29.5 mAP. So I think it is reasonable to modify this.
> [Fix] set unmap_results=True in ssd_head

- configs/yolox/yolox_s_8x8_300e_coco.py
- configs/yolox/yolox_tiny_8x8_300e_coco.py
- mmdet/datasets/pipelines/transforms.py
- mmdet/models/detectors/yolox.py
- mmdet/utils/__init__.py
- mmdet/utils/logger.py
- tests/test_utils/test_logger.py
This PR updates the log messages and docstrings of YOLOX and its data augmentation to avoid wrong order of image shape.
Related issue: https://github.com/open-mmlab/mmdetection/issues/7149
- Add `log_img_scale` function to log image's height and width
- Call `log_img_scale` from `YOLOX`, `Mosaic`, and `MixUp` 
- Add a utility function `get_caller_name` to show the name of caller method without explicit passing of class name
- Update docstrings
> [Enhance] Update YOLOX log for non square input

- mmdet/datasets/api_wrappers/panoptic_evaluation.py
- mmdet/datasets/coco_panoptic.py
resolve #7309 
1. add arg `cpu_num` in  pq_compute_multi_core
2. add arg `cpu_num` and docstring for args in cocopanoptic
> [Enhance] add cpu_num in cocopanoptic for pq computing

- mmdet/datasets/pipelines/loading.py
- setup.cfg
- tests/test_data/test_pipelines/test_loading.py
Allow to set channel_order in LoadImageFromFile. 
The other downstream vision tasks, like tracking, may need images of `rgb`  channel order as inputs. 
The same [PR](https://github.com/open-mmlab/mmdetection/pull/5893) is created by others, but it's closed later though not merged.
set input parameters about `channel_order` in LoadImageFromFile.
If so, please describe how it breaks the compatibility and how the downstream …
> [Enhancement] Allow to set channel_order in LoadImageFromFile

- mmdet/models/dense_heads/centripetal_head.py
- mmdet/models/dense_heads/corner_head.py
- mmdet/models/dense_heads/yolox_head.py
Force the inputs of `get_bboxes` in yolox_head to float32.
Fix #6976
1. Pre-commit or other linting tools are …
> [Fix] Force the inputs of `get_bboxes` in yolox_head to float32.

- mmdet/datasets/pipelines/loading.py
New params added in `LoadAnnotation` misplaced by https://github.com/open-mmlab/mmdetection/pull/6331 , which cause that the value `True` passed to `denorm_bbox` instead of `poly2mask` in `LoadPanopticAnnotations`, see  https://github.com/open-mmlab/mmdetection/blob/70f6d9cfade4a2f0b198e4f64776521d181b28be/mmdet/datasets/pipelines/loading.py#L442
No
No
2. The modification is covered by …
> [Fix] new params misplaced in loadannotation

- mmdet/apis/test.py
- mmdet/datasets/coco.py
- mmdet/datasets/coco_panoptic.py
- tests/test_data/test_datasets/test_panoptic_dataset.py
modification:
1. coco dataset
2. cocopanoptic dataset
3. mmdet/apis/test.py
The test result format for a model (such as Mask2Former) which support instance segmentation and panoptic segmentation as follows:
```python
[
{
'pan_results': np.array, # shape = [h, w]
'ins_results': tuple[list, list],
'sem_results': np.array
},
...
]
```
Here is evaluation of mask2former_r50
```
Panoptic Evaluation Results:
+--------+--------+--------+--------+------------+
|        | PQ     | SQ     | RQ     | categories |
+--------+--------+--------+--------+------------+
| All    | 51.632 | 83.082 | 61.271 | 133        |
| Things | 57.416 | 84.124 | 67.678 | 80         |
| Stuff  | 42.901 | 81.509 | 51.601 | 53         |
+--------+--------+--------+--------+------------+
Average Precision  (AP) @[ …
```
> [Feature] add instance evalutation in coco_panoptic

- docs/en/projects.md
> Remove duplicate link

- mmdet/models/losses/cross_entropy_loss.py
This is part of Mask2Former( PR #6938 )
1. update docstring in `binary_cross_entropy`. When `pred`  have shape (N, 1), it will be  expanded to onehot, while for `pred` with shape (N, ), it will not be expanded to onehot.
> [Enhance] Update docstring of cross entropy loss

- mmdet/models/plugins/__init__.py
- mmdet/models/plugins/msdeformattn_pixel_decoder.py
- mmdet/models/plugins/pixel_decoder.py
- tests/test_models/test_plugins.py
Take MSDoformAttnPixelDocder out of the Mask2Former #6938 , make it a new small PR.
1 add MSDoformAttnPixelDocder which will be used in Mask2Former.
2 add unit test.
3. update format and docstring.
> [Feature] Support MSDeform attn pixel decoder

- configs/maskformer/maskformer_r50_mstrain_16x1_75e_coco.py
- mmdet/core/mask/__init__.py
- mmdet/core/mask/utils.py
- mmdet/models/dense_heads/maskformer_head.py
- mmdet/models/detectors/maskformer.py
- mmdet/models/seg_heads/panoptic_fusion_heads/__init__.py
- mmdet/models/seg_heads/panoptic_fusion_heads/maskformer_fusion_head.py
- tests/test_models/test_dense_heads/test_maskformer_head.py
- tests/test_models/test_seg_heads/test_maskformer_fusion_head.py
- tests/test_utils/test_masks.py
MaskFormer refactor, part of #6938 
1. a new panoptic fusion head `MaskFormerFusionHead` which will be used by MaskFormer and Mask2Former, containing `instance_postprocess`, `panoptic_postprocess`, `semantic_postprocess`(not implemanted yet), and move the panoptic_postprocess from `MaskFormerHead` to `MaskFormerFusionHhead`.
2. update the config.
3. update `simple_test` in MaskFormer detector, which will be reused by Mask2Former.
4. `mask2bbox` which generated bboxes from mask, may be used by other model in the future.
5. unit test
> [Enhance] MaskFormer refactor

- mmdet/models/dense_heads/free_anchor_retina_head.py
- mmdet/models/losses/cross_entropy_loss.py
- mmdet/models/losses/utils.py
- tests/test_models/test_loss.py
resolve #7367 
Fix avg_factor in CELoss with ignore index.
2. The modification is covered by …
> [Fix] Fix reduction=mean in CELoss.

- configs/mask2former/mask2former_r50_lsj_8x2_50e_coco.py
- configs/mask2former/mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco.py
- mmdet/core/bbox/match_costs/__init__.py
- mmdet/core/bbox/match_costs/match_cost.py
- mmdet/datasets/coco.py
- mmdet/datasets/coco_panoptic.py
- mmdet/models/dense_heads/__init__.py
- mmdet/models/dense_heads/mask2former_head.py
- mmdet/models/detectors/__init__.py
- mmdet/models/detectors/mask2former.py
- tests/test_models/test_dense_heads/test_mask2former_head.py
- tests/test_models/test_forward.py
- tests/test_utils/test_assigner.py
This PR Mask2former is based on maskformer's PR(#6607 ).The components of maskformer in mask2former are same with the origin PR(#6607 ).
Add a greater panoptic segmentation model to mmdet.
- Components in maskformer(not list here).
- Multi-scale-Deformable-Attention Pixeldecoder.
- mask2former head and detector.
- two configs for r50 and swin-tiny.
- instance segmentation evaluation in CocoPanopticDataset.
```
evaluation result of mask2former_r50_lsj_8x2_50e_coco
{
'PQ': 51.85113493826705, 'SQ': 83.07220152800042, 'RQ': 61.59141241640433, 'PQ_th': 57.712003700037954, 'SQ_th': 84.06726498653896, 'RQ_th': 68.07799535626707, 'PQ_st': 43.00454058087707, 'SQ_st': 81.57021894907417, 'RQ_st': 51.80034382793225, 
'PQ_copypaste': '51.9 83.1 61.6 57.7 84.1 68.1 43.0 81.6 51.8', 
'bbox_mAP': 0.443, …
```
> [Feature] add Mask2former to mmdet

- tests/test_utils/test_assigner.py
Update `unit test of CrossEntropyCost`.
> [Fix] Update unit test of CrossEntropyCost

- configs/mask2former/mask2former_r50_lsj_8x2_50e_coco.py
- mmdet/datasets/api_wrappers/panoptic_evaluation.py
- tests/test_utils/test_assigner.py
Related issue https://github.com/cocodataset/panopticapi/issues/27
Add `workers.close()` and `workers.join()`  after https://github.com/open-mmlab/mmdetection/blob/14f0e9585c15c28f0c31dcc3ea352449bbe5eb96/mmdet/datasets/api_wrappers/panoptic_evaluation.py#L207
> [Fix] Memory leaking in panpotic segmentation evaluation

- mmdet/models/losses/cross_entropy_loss.py
The inplace writing method will have a mismatched broadcast shape error if the weight and valid_mask dimensions  are inconsistent such as (B,N,1) and (B,N,C).
`weight *= valid_mask` -> `weight = weight * valid_mask`
If this PR introduces a new feature, it is better to list some use …
> fix broadcast shape bug in yolov3

- mmdet/models/dense_heads/tood_head.py
After deform_sampling, some boxes will become illegal (the left-top point is at the right or bottom of the right-bottom point), which will make the GIoULoss negative.
Have no effect on performance (origin: 42.3, after: 42.2 & 42.4).
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …
> [Fix] Avoid invalid bbox after deform_sampling

- mmdet/core/bbox/assigners/sim_ota_assigner.py
Changing INF to 100000.0 in sim_ota_assigner.py is in line with Megvii YOLOX repo and it also gave better result on my custom dataset. Might close the gap with Megvii YOLOX results if retrained with COCO.
Updated INF to 100000.0 in sim_ota_assigner.py.
> Updated INF to 100000.0 to be in line with original YOLOX implementation

- mmdet/apis/train.py
- mmdet/core/data_structures/general_data.py
- mmdet/datasets/samplers/distributed_sampler.py
- mmdet/utils/__init__.py
- mmdet/utils/util_distribution.py
- tools/test.py
- tools/train.py
* Mmdet support PyTorch backend on MLU (with Cambricon PyTorch).
Support Cambricon MLU device for PyTorch backend.
mmdet/apis/train.py : model copy and get current device before MMDataParallel and MMDistributedDataParallel
tool/train.py : moifyed to support mlu init_random_seed;
mmdet/core/data_structures/general_data.py: add Tensor-like methods.
No BC-breaking
> feat(mlu): Support PyTorch backend on MLU.

- mmdet/apis/train.py
- mmdet/datasets/samplers/distributed_sampler.py
- mmdet/utils/__init__.py
- mmdet/utils/util_distribution.py
- tools/test.py
- tools/train.py
Fix lint in dev branch
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
mmdet/apis/train.py:8:1: F401 'mmcv.parallel.MMDataParallel' imported but unused
mmdet/apis/train.py:8:1: F401 'mmcv.parallel.MMDistributedDataParallel' imported but unused
mmdet/apis/train.py:17:25: E128 continuation line under-indented for visual indent
mmdet/apis/train.py:19:1: E302 expected 2 blank lines, found 1
mmdet/datasets/samplers/distributed_sampler.py:10:1: E302 expected 2 blank …
> [Fix] Fix lint in dev branch

- configs/centernet/centernet_resnet18_dcnv2_140e_coco.py
solve #7842
Fix KeyError: 'ori_filename' in testing the config named centernet_resnet18_dcnv2_140e_coco.py
1. …
> [Fix] Fix KeyError: 'ori_filename' when using --show-dir with centernet_resnet18_dcnv2_140e_coco.py

- mmdet/models/backbones/swin.py
Found a small typo in docstring
corrected a small typo in docstring
> fixtypo:name of default act func is wrong

- mmdet/models/detectors/yolox.py
- tests/test_models/test_forward.py
YOLOX training is only available on Cuda. Make it possible to run on an arbitrary device.
Send tensor to the appropriate device on the random resizing step. …
> [FIX] Enable YOLOX training on different devices

- tools/test.py
During testing, the `cfg.evaluation.gpu_collect` does not take effect. Rather, users need to specify `gpu_collect` from the command line.
This behavior is inconsistent with the evaluation during training, where `cfg.evaluation.gpu_collect` decides whether to use `gpu_collect`.
`gpu_collect = args.gpu_collect or cfg.evaluation.gpu_collect` in `tools/test.py` line 238-239
```python
outputs = multi_gpu_test(model, data_loader, args.tmpdir,
args.gpu_collect)
```
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or …
> [Enhance] Support reading `gpu_collect` from cfg.evaluation.gpu_collect

- mmdet/core/evaluation/mean_ap.py
- tests/test_metrics/test_mean_ap.py
- tools/analysis_tools/analyze_results.py
Fix #7631
The time spent on [`eval_fn`](https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/tools/analysis_tools/analyze_results.py#L130) costs 1.5s, and on ['dataset.prepare_train_img(i)'](https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/tools/analysis_tools/analyze_results.py#L129) costs 0.01~0.05s. It is clear that we should accelerate the `eval_fn`. There are three nested loops in eval_fn: a loop for iou_thresh(0.5 ~ 0.95), a nested loop for classes, …
> [Enhance] Accelerate analyze result

- mmdet/models/dense_heads/yolo_head.py
- mmdet/models/dense_heads/yolox_head.py
#7728
Wrap lists in `np.array`
> convert scale_factors from list to array to prevent UserWarning

- docs/en/useful_tools.md
- tools/analysis_tools/analyze_logs.py
Thanks for maintaining such a wonderful project. I encountered some problems and tried to fix them as the following.
I encountered three small problems while using [analyze_logs.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_logs.py). When **plotting epoch-based metrics**:
1. It can't work with evaluation interval greater than 1. Although the parameter `--eval-interval` allows a value to be entered, it will raise error in practice. The reason is that [line 57](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_logs.py#L57) requires the metric to be present in the starting epoch. Use [log of yolox-l ](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_l_8x8_300e_coco/yolox_l_8x8_300e_coco_20211126_140236.log.js …
> Fix the log plot error when evaluation interval != 1

- docs/en/tutorials/index.rst
- docs/en/tutorials/test_results_submission.md
- docs/en/tutorials/useful_hook.md
- docs/en/tutorials/useful_hooks.md
- mmdet/core/hook/memory_profiler_hook.py
- tests/test_models/test_necks.py
Add a tutorial to introduce useful hooks provided by MMDetection and MMCV.
1. Pre-commit or other linting tools …
> [Docs] userful hooks

- .github/workflows/build.yml
Clean pillow version check.
modify .github/workflows/build.yml.
2. The modification is covered …
> [Enhance] Clean pillow version check

- docker/Dockerfile
I resolved <https://github.com/open-mmlab/mmdetection/issues/7951>.
I fixed GPG key. I applied <https://github.com/open-mmlab/mmsegmentation/pull/1534>.
And, I checked by the following command.
```shell
cd mmdetection
docker build -t mmdetection -f docker/Dockerfile .
```
My environment is as follows.
- Ubuntu 22.04
- nvidia-driver-515
- Docker 20.10.16
> [Fix] fixed GPG key error in Dockerfile

- mmdet/models/dense_heads/rpn_head.py
- mmdet/models/dense_heads/solov2_head.py
- mmdet/models/necks/dyhead.py
- mmdet/models/necks/pafpn.py
- mmdet/models/roi_heads/htc_roi_head.py
- mmdet/models/roi_heads/roi_extractors/generic_roi_extractor.py
- mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py
- mmdet/models/roi_heads/scnet_roi_head.py
fix runtime error of "+=" inplace operation in PyTorch 1.10
Closes #7933, 
Closes #8221,
Closes #8443,
> [Fix] fix runtime error of "+=" inplace operation in PyTorch 1.10

- tools/deployment/pytorch2onnx.py
I'm the author of onnx-simplifier. Recently I published onnxsim v0.4.0. In the latest version, dynamic input shapes are natively supported with no need for extra flags like `dynamic_input_shapes`. `custom_lib` and `input_data` is also not needed.
> Upgrade onnxsim to at least 0.4.0

- .github/workflows/stale.yml
Add a new feature to repo's CI:
1.automatically add "stale" label to inactive issues and prs with both "invalid" and "awaiting response" labels
2.automatically close issues and prs which are labeled "stale" for a certain amount of time.
Add .github/workflow/stale.yml
see  ![Close …
> Add .github/workflow/stale.yml

- mmdet/models/necks/dyhead.py
the parameter of offset is not set as continuous will trigger the runtime error: offset must be continuous
If this PR introduces …
> Fix DyDCNv2 RuntimeError

- mmdet/core/bbox/iou_calculators/iou2d_calculator.py
Fix method docstring typo
- Change m in second bbox shape with n
- Remove duplicated explanation for "is_aligned" parameter
> Fix method doc

- mmdet/models/dense_heads/__init__.py
CascadeRPNHead repeat.
Remove duplicate class name.
No.
No.
> [repeat] CascadeRPNHead

- mmdet/models/utils/gaussian_target.py
Missing newlines cause a wrong rendering of the formulas.
> Fix mistakes in formula

- mmdet/models/backbones/swin.py
- tests/test_models/test_backbones/test_swin.py
The Swin transformer backbone is currently unable to process input images differing in size from the pretraining resolution when absolute positional embedding is enabled, due to lack of dynamic pos embed resizing in the forward pass.
When absolute positional embedding is enabled, the backbone now checks the input shape against the pos embed shape and performs a bicubic interpolation to the correct shape if necessary. This is based on the original Mask2former code: https://github.com/facebookresearch/Mask2Former/blob/main/mask2former/modeling/backbone/swin.py#L656.
The pos embed parameter's shape has also been changed from [B * (H*W) * D] -> [B * D * H * W] to bring the model into consistency with the checkpoint loading code, which expects the new shape.
This fix should not break backwards …
> Fix swin backbone absolute pos_embed

- tools/train.py
When using a Wrapper Dataset, for example, `RepeatDataset`, an internal dataset with the dataset key is used. If you additionally use several workflows `workflow = [('train', 2), ('val', 1)]`, an error occurs on the line, since this key does not exist.
```
val_dataset.pipeline = cfg.data.train.pipeline
AttributeError: 'ConfigDict' object has no attribute 'pipeline'
```
Added name matching check. Also added the ability to get **train_pipeline** from the Wrapper Dataset.
`tools/train.py`
No
When using a wrapper Dataset, for example, `RepeatDataset`, an internal dataset with the dataset key is used. If you additionally use several workflows `workflow = [('train', 2), ('val', 1)]`, an error occurs on the line, since this key does not exist.
`configs/_base_/datasets/voc0712.py`
``` …
```
> [Fix]: Fix get train_pipeline method of val workflow

- mmdet/models/dense_heads/solo_head.py
- mmdet/models/dense_heads/solov2_head.py
- mmdet/utils/misc.py
In SOLO code, __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. 
torch.div(a, b, rounding_mode='trunc') is used to replace floordiv.
> Fix floordiv warning.

- .circleci/test.yml
- mmdet/datasets/transforms/transforms.py
- tests/test_datasets/test_transforms/test_transforms.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_visualization/test_local_visualizer.py
> [Fix] Fix UT to be compatible with pytorch 1.6

- mmdet/models/dense_heads/mask2former_head.py
Fix the wrong shape comments of the mask2former head
Fix the wrong shape comments of the mask2former head
> [Fix] Fix the wrong shape comments of the mask2former head

- mmdet/models/dense_heads/anchor_head.py
- mmdet/models/dense_heads/base_dense_head.py
- mmdet/models/dense_heads/retina_head.py
- mmdet/models/detectors/base.py
- mmdet/models/task_modules/assigners/iou2d_calculator.py
- mmdet/models/task_modules/coders/base_bbox_coder.py
- mmdet/models/task_modules/coders/bucketing_bbox_coder.py
- mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py
- mmdet/models/task_modules/coders/distance_point_bbox_coder.py
- mmdet/models/task_modules/coders/legacy_delta_xywh_bbox_coder.py
- mmdet/models/task_modules/coders/pseudo_bbox_coder.py
- mmdet/models/task_modules/coders/tblr_bbox_coder.py
- mmdet/models/task_modules/coders/yolo_bbox_coder.py
- mmdet/models/task_modules/prior_generators/anchor_generator.py
- mmdet/models/task_modules/prior_generators/utils.py
- mmdet/models/task_modules/samplers/base_sampler.py
- mmdet/models/task_modules/samplers/sampling_result.py
- mmdet/models/utils/__init__.py
- mmdet/models/utils/misc.py
- mmdet/structures/bbox/base_boxes.py
- mmdet/structures/bbox/horizontal_boxes.py
- mmdet/testing/_utils.py
- tests/test_datasets/test_transforms/test_geometric.py
- tests/test_datasets/test_transforms/test_transforms.py
- tests/test_datasets/test_transforms/utils.py
- tests/test_models/test_data_preprocessors/test_data_preprocessor.py
- tests/test_structures/test_bbox/test_base_boxes.py
Refactor anchor head and base head with boxlist.
1. Pre-commit or other linting …
> [Refactor] Refactor anchor head and base head with boxlist

- mmdet/models/detectors/panoptic_two_stage_segmentor.py
- mmdet/models/detectors/two_stage.py
During an iteration, the dictionary should not be modified. Add `list` to make a list copy.
No error is raised when the value of the loss dict is a Tensor, but this does not make sense. The error raised when the value of the loss dict is a List.
The fix can support use retinanet as an rpn head.
If so, please describe how it breaks the compatibility and how the …
> [Fix] Add list to dict keys to avoid modify loss dict

- mmdet/engine/hooks/__init__.py
- mmdet/engine/hooks/utils.py
- mmdet/utils/__init__.py
- mmdet/utils/misc.py
- tools/test.py
> [Feature]Implement dump results

- mmdet/models/dense_heads/fsaf_head.py
- mmdet/models/dense_heads/reppoints_head.py
We should fill the background label just like other dense heads, not 0.
> [Fix] Bug in reppoints_head and fsaf_head

- mmdet/core/hook/wandblogger_hook.py
I got the following error when I used `MMDetWandbHook` in the offline mode:
```
wandb: Tracking run with wandb version 0.13.2
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Traceback (most recent call last):
File "tools/train.py", line 242, in <module>
main()
File "tools/train.py", line 238, in main
meta=meta)
File "/content/mmdetection/mmdet/apis/train.py", line 244, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 117, in run
self.call_hook('before_run')
File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 317, in call_hook
getattr(hook, fn_name)(self)
File …
```
> [Fix ] MMDetWandbHook does not support offline mode

- README.md
- README_zh-CN.md
The link to the tutorial(semi-supervise detection and RPN) does not work.
edit the readme, and fix the semi-supervise detection and RPN link.
> fix the link to 3.x doc.

- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/en/user_guides/config.md
- docs/en/user_guides/dataset_prepare.md
- docs/zh_cn/get_started.md
Updated a little bit on some documents.
modified:   README.md
modified:   README_zh-CN.md
modified:   docs/en/get_started.md
modified:   docs/en/user_guides/config.md
modified:   docs/en/user_guides/dataset_prepare.md
modified:   docs/zh_cn/get_started.md
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the …
> revise eng docs

- mmdet/datasets/builder.py
The `ConcatDataset` Class is moved to mmengine, so the relative import in mmdet builder function is not correct and will raise the following error:
```shell
ImportError: cannot import name 'ConcatDataset' from 'mmdet.datasets.dataset_wrappers'
```
Remove the old relative import line and add the code to import `ConcatDataset` from mmengine
Does the modification introduce changes …
> fix ConcatDataset ImportError

- .pre-commit-config.yaml
- docs/en/advanced_guides/customize_runtime.md
- docs/en/advanced_guides/customize_transforms.md
- docs/en/notes/changelog_v2.x.md
- docs/en/user_guides/config.md
- docs/en/user_guides/useful_tools.md
- mmdet/models/dense_heads/detr_head.py
- mmdet/models/losses/focal_loss.py
- mmdet/models/losses/mse_loss.py
- mmdet/models/roi_heads/htc_roi_head.py
- mmdet/models/task_modules/samplers/sampling_result.py
- setup.cfg
- tests/test_structures/test_bbox/test_box_type.py
The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade some versions of pre-commit hooks in dev-3.x.
No …
> Upgrade pre commit hooks in dev-3.x

- .circleci/test.yml
- docs/en/user_guides/useful_hooks.md
- requirements/optional.txt
- tests/test_models/test_seg_heads/test_panoptic_fpn_head.py
Fix CI
Note: 
The following writing will cause `readthedoc` to fail to build and the code can't use relative paths
`## [MemoryProfilerHook](../../../mmdet/engine/hooks/memory_profiler_hook.py)`
The correct writing is as follows
```shell
[Memory profiler hook](https://github.com/open-mmlab/mmdetection/blob/3.x/mmdet/engine/hooks/memory_profiler_hook.py) 
```
None
> Fix CircleCI and readthedoc build failed

- mmdet/datasets/transforms/formatting.py
When key is not in `results` may raise an exception.
```python
pipeline = [
dict(type='LoadImageFromFile', file_client_args=file_client_args),
dict(type='LoadAnnotations', with_bbox=True),
dict(
type='mmdet.PackDetInputs',
meta_keys=('test'))
]
```
> KeyError: 'test'
> add assert

- mmdet/models/dense_heads/retina_head.py
When `stacked_convs` is 0, the value of `feat_channels` and `in_channels` may be different.
> Fixed inconsistency in 'nn.Conv2d' weight channels

- .github/workflows/build.yml
- requirements/optional.txt
1. Remove timm from requirements/optional.txt like https://github.com/open-mmlab/mmdetection/pull/8980 because timm v0.6.11 requires torch>=1.7 and breaks CI.
Another possible way to fix this issue: https://github.com/open-mmlab/mmaction2/pull/1975
2. Fix CI for pycocotools by setting CFLAGS like https://github.com/open-mmlab/mmaction2/pull/1831 and https://github.com/open-mmlab/mmdeploy/pull/945
3. Fix CI for onnx by setting CXXFLAGS
For 2. and 3., a more direct cause of behavioral change in GitHub Actions may be related to https://github.com/actions/setup-python/issues/485 and https://github.com/actions/setup-python/issues/507 .
> [CI] Fix CI for timm, pycocotools, onnx

- mmdet/core/bbox/samplers/random_sampler.py
neg_pos_up -> neg_pos_ub
minor typo fix
Debugging today was difficult because searching with ctrl+shift+f was not possible due to a typo.
I just changed one letter. neg_pos_up -> neg_pos_ub
I just want to fix this typo, and I was thinking about whether to drop it in an issue or make a pull request and post it here. If you've read this, I'd appreciate it if you could correct the typo. thx !
2. The modification is covered by complete unit tests. If …
> minor typo

- mmdet/models/dense_heads/anchor_head.py
- mmdet/models/dense_heads/cascade_rpn_head.py
- mmdet/models/dense_heads/gfl_head.py
- mmdet/models/dense_heads/guided_anchor_head.py
- mmdet/models/dense_heads/mask2former_head.py
- mmdet/models/dense_heads/maskformer_head.py
- mmdet/models/dense_heads/pisa_retinanet_head.py
- mmdet/models/dense_heads/reppoints_head.py
- mmdet/models/dense_heads/rtmdet_head.py
- mmdet/models/dense_heads/sabl_retina_head.py
- mmdet/models/dense_heads/yolo_head.py
- mmdet/models/dense_heads/yolox_head.py
If `AnchorHead` is used as the net head and `dict` is used as the `train_cfg` parameter, an error will be reported. 
That is because `dict` does not support python object attributes interface like `train_cfg.assigner`, but `ConfigDict` does.
```python
cfg = dict(
type='mmdet.AnchorHead',
num_classes=80,
in_channels=256,
train_cfg=dict(
assigner=dict(type='MaxIoUAssigner', pos_iou_thr=0.5,
neg_iou_thr=0.3)))
anchor_head = MODELS.build(cfg)
```
> AttributeError: class `AnchorHead` in mmdet/models/dense_heads/anchor_head.py: 'dict' object has no attribute 'assigner'
> make compatible with `ConfigDict` and `dict`

- configs/_base_/datasets/openimages_detection.py
we found an error in openimages config file: parameters "iou_thr" and "ioa_thr" in `OpenImagesMetric`  should actually be ""iou_thrs" and "ioa_thrs" according to it's defination.
> fix config file error

- mmdet/models/losses/__init__.py
- mmdet/models/losses/iou_loss.py
- tests/test_models/test_losses/test_loss.py
In paper: [A Systematic IoU-Related Method: Beyond Simplified Regression for Better Localization](https://ieeexplore.ieee.org/document/9429909) of TIP2021, we propose a new Extended-IOU loss, which outperforms the commonly used GIOU and DIOU in object detection.
add implementation of the proposed Extended-IOU Loss (EIOU).
In config:
`loss_bbox=dict(type='EIoULoss',  loss_weight=1.0, smooth_point=0.1)`
> add eiou impl

- requirements/docs.txt
> [Fix] Fix readthedocs.

- mmdet/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform/test_transform.py
It's much more expensive for us to annotate a mask label than bbox. So, How copypaste can be utilized when only bbox provided?
If only gt_bboxes provided, gt_masks can be generated by the gt_bboxes to get a second best preformance.
> copypaste_based_on_bbox

- mmdet/models/dense_heads/solov2_head.py
Solve PR: https://github.com/open-mmlab/mmdetection/issues/9159
`loss_mask` may empty when `num_pos = 0`. Hence, fix the num_pos=0  case to support dealing with empty gt image
> [Fix] Fix solov2 cannot dealing with empty gt image

- mmdet/core/bbox/assigners/hungarian_assigner.py
- mmdet/core/bbox/assigners/mask_hungarian_assigner.py
- requirements/optional.txt
- requirements/runtime.txt
Since DETR series become very popular, bipart matching becomes a default.
Therefore, it would be better to make scipy a default runtime dependency rather than optional
Resolve PR: https://github.com/open-mmlab/mmdetection/issues/8962
> [Enhance] Make scipy as a default dependency in runtime

- mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py
- tests/test_models/test_task_modules/test_assigners/test_dynamic_soft_label_assigner.py
Add box_type support for Dynamic Soft Label Assigner.
Allow mmrotate to use `DynamicSoftLabelAssigner` directly with out any modify.
Also i found that the `find_inside_points` method results are slightly different than the original version, `find_inside_points` allow the points on the edge.
https://github.com/open-mmlab/mmdetection/blob/816637e1677146d790b4b4a1fc05c400d9260dfb/mmdet/structures/bbox/horizontal_boxes.py#L333-L334
I think we could add a `keep_edge` or `eps` arg in `find_inside_points` to control that behavior, also …
> [Enhance] Add box_type support for `DynamicSoftLabelAssigner`

- mmdet/models/roi_heads/bbox_heads/bbox_head.py
- mmdet/models/roi_heads/cascade_roi_head.py
- mmdet/models/roi_heads/standard_roi_head.py
- mmdet/models/utils/misc.py
When `rcnn_test_cfg is None` the score of a empty instance need to have shape of (0, num_classes + 1). But now, it has shape (0, ). This will cause soft teacher crashes sometimes.
If this PR introduces a new feature, it …
> [Fix] Fix bugs of `empty_instances` when predicting without nms in roi_head.

- mmdet/structures/bbox/horizontal_boxes.py
- tests/test_structures/test_bbox/test_horizontal_boxes.py
Fix corner2hbox of HorizontalBoxes for supporting empty bboxes.
1. Pre-commit or other linting tools are used to …
> [Fix]Fix horizontal boxes

- mmdet/datasets/xml_style.py
The image size should be `height, width = img.shape[:2]` if xml.size is None.
> [Fix] Fix image size error in XML dataset

- configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person-bicycle-car.py
- configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person.py
When handling the coco subset on MMDet 3.x, should change the dataset configs in faster-rcnn
> [Fix]: fix handle coco subsets on MMDet 3.x

- configs/_base_/datasets/voc0712.py
- configs/pascal_voc/ssd300_voc0712.py
- configs/pascal_voc/ssd512_voc0712.py
- mmdet/__init__.py
VOCDataset has `DATASET_TYPE` key in metainfo which is different in VOC2007 and VOC2012. This will get an error when using ConcatDataset. Hence, we add an `ignore_key` in ConcatDataset to fix this error.
add an `ignore_key` in ConcatDataset to fix this error.
This PR should be merged after https://github.com/open-mmlab/mmengine/pull/556  has been merged in MMEngine.
Before merging this PR, https://github.com/open-mmlab/mmdetection/pull/8847 can be temporarily fixed VOC ConcatDataset error.
This PR change the minimum version of mmengine to 0.3.0.
> [Fix] Add `ignore_key` in voc dataset to fix error

- mmdet/datasets/transforms/transforms.py
> [Fix]: fix (Cached) MixUp padding

- tools/train.py
If `args.resume` is None, `cfg.resume = args.resume` will always set `resume` to `None` even if you set `resume=True` in config or through `--cfg-options`.
Only overwrite the cfg.resume when args.resume is not None.
If this PR introduces a new feature, it is better to list some use …
> [Fix] Fix resume arg conflict.

- mmdet/datasets/transforms/loading.py
- mmdet/datasets/transforms/transforms.py
"counts" in COCO’s compressed RLE format has type of 'str' or 'list'.
> [Fix] type of "counts" in COCO’s compressed RLE

- configs/fcos/fcos_r50_caffe_fpn_gn-head_fp16_1x_bs8x8_coco.py
- configs/ssd/ssd300_fp16_coco.py
- mmdet/apis/inference.py
- mmdet/apis/train.py
- mmdet/core/data_structures/general_data.py
- mmdet/utils/util_distribution.py
- tools/test.py
Added NPU(ascending device) support in mmdet
The main modification points are:
1. add NPUDataParallel、NPUDistributedDataParallel
None
Provides configuration information that can be worked on the NPU
| config |  map | map_gpu |
| ----------- | ----------- | ----------- |
| configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_bs8x8_coco.py | 36.2 | 36.1 |
| configs/ssd/ssd300_coco_fp16.py | 25.6 | 25.5 |
3. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
4. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
5. The documentation has been modified accordingly, like …
> [Feature] Support mmdet with NPU backend

- mmdet/datasets/cityscapes.py
Issue: #9329
A new entry `seg_suffix` is added for CustomDataset.__init__() but missing in `self_coco = CocoDataset` in function `evaluate()`, `mmdet/datasets/cityscapes.py`.
Signed-off-by: Shengjiang QUAN <qsj287068067@126.com>
Issue: #9329
A new entry `seg_suffix` is added for CustomDataset.__init__() but missing in `self_coco = CocoDataset` in function `evaluate()`, `mmdet/datasets/cityscapes.py`.
There is an arguments mismatch between the arguments of `self_coco = CocoDataset` in `mmdet/datasets/cityscapes.py` with the new `__init__` in `mmdet/datasets/custom.py`. `self.proposal_file` in `CocoDataset` class in `mmdet/datasets/cityscapes.py` is assigned to `seg_suffix` in `CustomDataset.__init__()` in `mmdet/datasets/custom.py`.
Complement the missing argument `seg_suffix: str = …
> [datasets] cityscapes.py: complement necessary arg seg_suffix

- mmdet/datasets/pipelines/transforms.py
> Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
> Please describe the motivation of this PR and the goal you want to achieve through this PR.
Random flip in MixUp augmentation seems to have a bug.
In current implementation, when `flip_ratio` is set to 0, mixup image is always flipped.
> Please briefly describe what modification is made in this PR.
Fixed the above behavior.
> Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should …
> fix a bug of random flip in MixUp

- mmdet/models/necks/yolo_neck.py
超级视客营mmdet基础任务，选择链接中任一part代码添加type hints，为part-9的yolo_neck.py添加type hints
为yolo_neck.py中的DetectionBlock和YOLOV3Neck相关函数添加type hints
> [fix] add type hints for yolo_neck

- mmdet/models/dense_heads/condinst_head.py
When set batch_size>1 in val_dataloader, got an error like this:
```
File "/workspace/mmdetection/mmdet/models/detectors/single_stage_instance_seg.py", line 175, in predict
results_list = self.mask_head.predict(
File "/workspace/mmdetection/mmdet/models/dense_heads/base_mask_head.py", line 121, in predict
results_list = self.predict_by_feat(
File "/workspace/mmdetection/mmdet/models/dense_heads/condinst_head.py", line 1191, in predict_by_feat
im_mask = self._predict_by_feat_single(
File …
```
> [Fix] Fix Condinst predict error when val batch_size>1

- mmdet/datasets/transforms/transforms.py
For image(type=float32), after convert bgr to hsv by opencv, valid saturation value range is [0, 1].
> clip saturation value to valid range [0, 1]

- mmdet/visualization/local_visualizer.py
- tools/analysis_tools/browse_dataset.py
Fix the bug of visualization when the dtype of the pipeline output image is not uint8.
Before:
After: …
> [Fix] Fix browse dataset.

- tools/analysis_tools/analyze_logs.py
Fix `analyze_logs.py` to
1.  plot mAP correctly.
1. If `--eval-interval` is not set when plotting mAP, it will raise `KeyError: 'log.json does not contain metric bbox_mAP. Please check if "--no-validate" is specified when you trained the model.`.
2. If `--eval-interval` is set correctly, it will raise `ValueError: x and y must have same first dimension, but have shapes (300,) and (30,)`.
2. calculate train time correctly.
`tools/analyze_logs.py`
> [Fix] `analyze_logs.py` to plot mAP and cal train time correctly

- mmdet/models/necks/bfp.py
- mmdet/models/necks/channel_mapper.py
超级视客营 mmdet 基础任务，为part-9的 `bfp.py` 和 `channel_mapper.py` 添加 type hints
1. 昨天修改好了 `bfp.py` 并提交PR且已经过审，但不太熟悉PR操作，没有签署 commit sign 导致无法合并
2. 为 `channel_mapper.py` 中相关函数添加 type hints
> CodeCamp #34 add type hints for bfp and channel_mapper

- tools/model_converters/upgrade_model_version.py
- tools/model_converters/upgrade_ssd_version.py
`import Config` has been changed in openmmlab-2.0, update the import code in the `./tools/model_converters`
Replace `from mmcv import Config, DictAction` with `from mmengine import Config, DictAction`
Two files are changed, including  `./tools/model_converters/upgrade_ssd_version.py` and `./tools/model_converters/upgrade_model_version.py`
If so, please describe how it breaks the compatibility and how the downstream projects …
> fix config import links in model converters

- .github/workflows/build.yml
- .github/workflows/build_pat.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/stale.yml
- .github/workflows/test_mim.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/open-mmlab/mmdetection/actions/runs/3095931510/jobs/5010897300#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- build.yml
- build_pat.yml
- deploy.yml
- lint.yml
- stale.yml
- test_mim.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub …
> ci: add minimum GitHub token permissions for workflows

- mmdet/models/losses/focal_loss.py
- mmdet/models/losses/gfocal_loss.py
- tests/test_models/test_losses/test_loss.py
> Adjust FocalLoss and QualityFocalLoss to fit MMYOLO

- docs/en/get_started.md
- docs/en/overview.md
- docs/zh_cn/get_started.md
- docs/zh_cn/overview.md
> [Docs] Update `get_started`

- tools/model_converters/publish_model.py
The checkpoint saved by mmengine contains more keys (e.g. message_hub, param_scheduler). These parts are very large and may take dozens or even hundreds of MB.
Pop the keys except for meta and state_dict.
> Only keep meta and state_dict when publish model.

- mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py
SenseParrots has already aligned some apis of autograd with pytorch so that requiring grad of "feats" is no longer needed by parrots, which will also cause an error.
We deleted a bunch of parrots-awared code within roi extractor so that the parameter "feats" no longer requires grad.
> delete parrots-awared code of roi extractor

- configs/yolox/yolox_s_8xb8-300e_coco.py
- configs/yolox/yolox_tiny_8xb8-300e_coco.py
- docs/en/advanced_guides/conventions.md
- docs/zh_cn/advanced_guides/conventions.md
- mmdet/datasets/transforms/formatting.py
- mmdet/datasets/transforms/transforms.py
- tests/test_datasets/test_transforms/test_transforms.py
> [BC Breaking] Make sure the pipeline input shape is in WH order

- .pre-commit-config.yaml
- mmdet/core/evaluation/mean_ap.py
- mmdet/core/export/model_wrappers.py
- mmdet/core/mask/structures.py
- mmdet/datasets/openimages.py
- tests/test_metrics/test_mean_ap.py
Gets rid of instances of `np.bool` to increase compatibility with newer versions of `numpy`. For more details see: https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations. 
_Note: `np.bool` has just been an alias for `bool`_ 
Replaces all `np.bool` instances w/ `bool`.
Not applicable
Not applicable
3. If the modification has …
> Deprecating `np.bool` Type Alias

- mmdet/datasets/transforms/augment_wrappers.py
- mmdet/datasets/transforms/loading.py
- mmdet/datasets/transforms/transforms.py
- mmdet/evaluation/functional/mean_ap.py
- mmdet/models/task_modules/samplers/iou_balanced_neg_sampler.py
- mmdet/structures/mask/structures.py
- mmdet/testing/_utils.py
- mmdet/visualization/local_visualizer.py
- tests/test_datasets/test_transforms/test_formatting.py
- tests/test_datasets/test_transforms/test_loading.py
- tests/test_datasets/test_transforms/test_transforms.py
- tests/test_models/test_dense_heads/test_boxinst_head.py
- tests/test_models/test_dense_heads/test_condinst_head.py
- tests/test_models/test_dense_heads/test_solo_head.py
- tests/test_models/test_dense_heads/test_solov2_head.py
- tools/analysis_tools/browse_dataset.py
Deprecating old type alias due to new version of numpy.
1. Replace all `np.int` with `np.int64`.
2. Replace all `np.bool` with `bool`.
> [Fix] Deprecating old type alias due to new version of numpy

- configs/rtmdet/README.md
Fix the wrong link of RTMDet-x log.
> [Fix] the wrong link of RTMDet-x log

- mmdet/models/layers/normed_predictor.py
- mmdet/models/layers/positional_encoding.py
- mmdet/models/layers/res_layer.py
- mmdet/models/layers/se_layer.py
超级视客营mmdet基础任务，选择链接中任一 part 代码添加 type hints，为part6的res_layer添加type hints
为其中的Reslayer和SimplifiedBasicBlock添加了type hint
If this PR introduces a new feature, it is better to list some use cases here, and update the …
> CodeCamp #33 [Fix]:add type hints for res_layer, se_layer,normed_predictor,positional_encoding

- mmdet/datasets/pipelines/formatting.py
- requirements/optional.txt
`numpy.transpose()` is mush more slow than `torch.permute()` according to my benchmarks on a jupyter notebook:
1. If the input image size (1366, 800, 3) is the size of COCO dataset image
```
import numpy as np
import torch
img = np.random.randn(1366, 800, 3)
```
```
%%timeit
img_np = np.ascontiguousarray(img.transpose(2, 0, 1))
input = torch.from_numpy(img_np)
```
Output: 7.69 ms ± 314 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
%%timeit
input = torch.from_numpy(img).permute(2, 0, 1).contiguous()
```
Output: 1.65 ms ± 123 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2. If the input image size is large, especially when inferencing a large image ((3648, 5472, 3) in my case)
```
img = np.random.randn(3648, 5472, 3)
```
```
%%timeit
img_np = …
```
> Replace numpy transpose with torch permute to speed-up

- README.md
- README_zh-CN.md
- docs/en/changelog.md
> update v2.27.0 changelog

- mmdet/datasets/coco.py
- mmdet/datasets/lvis.py
- tests/test_data/test_datasets/test_panoptic_dataset.py
In coco.py and lvis.py, the float precision of bbox mAP of eval_result of evaluate() function is .3f,
However, in the float precision when printing log in mmcv is .4f, 
see:
https://github.com/open-mmlab/mmcv/blob/ea173c9f07f0abf6873d2b7d786fb6411843cf00/mmcv/runner/hooks/logger/text.py#L178-L179
This PR suggests using the same .4f float precision. Another solution is not to limit the float precision in eval_result.
Fix #9569
> [Fix] Fix inconsistent float precision between mmdet and mmcv

- mmdet/models/layers/csp_layer.py
Add typehint for `DarknetBottleneck`
`mmdetection/mmdet/models/layers/csp_layer.py`
> [Fix] Add typehint for `DarknetBottleneck`

- mmdet/models/dense_heads/deformable_detr_head.py
In `DeformableDETRHead`, there were wrong argument name for fp32.
Fix to the appropriate name
Note that `torch.cdist` in `BBoxL1Cost` only supports fp32 so the predicted tensors should be converted to fp32.
It will be able to run Deformable DETR with fp16 after https://github.com/open-mmlab/mmcv/pull/2541 is merged.
> [Fix] Fix argument name for fp32 in `DeformableDETRHead`

- .circleci/test.yml
- docs/en/get_started.md
- docs/zh_cn/get_started.md
- setup.py
[Fix] Adjust the minimum supported python version to 3.7
If this PR introduces a new feature, it is better to list some use cases …
> [Fix] Adjust the minimum supported python version to 3.7

- configs/dcnv2/metafile.yml
- configs/gn+ws/metafile.yml
- configs/rfnext/metafile.yml
- configs/seesaw_loss/metafile.yml
While I look thorough the model zoo using mim, I found that there are some models failed to download because of the wrong config file path in metafile.yml (all weights links are OK btw.)
Related: https://github.com/open-mmlab/mim/pull/192
Fix all possible typos in metafile.yml. Now mim should be able to download all model configs without error!
> [Fix] Metafile.yml: Fix typo of all config file path.

- projects/ConvNeXt-V2/README.md
- projects/ConvNeXt-V2/configs/mask-rcnn_convnext-v2-b_fpn_lsj-3x-fcmae_coco.py
This PR gives an example of using ConvNeXt-V2 in mmdetection.
It requires the latest version of mmclassification-1.x.
The **official finetuning setting of object detection is not released yet**. 
There are at least three settings unknown:
Training result:
```
01/14 20:43:26 - mmengine - [4m[37mINFO[0m - Evaluating bbox...
Loading and preparing results...
DONE (t=0.94s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=39.44s).
Accumulating evaluation results...
DONE (t=6.56s).
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.529
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.727
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.587
Average Precision (AP) @[ IoU=0.50:0.95 …
```
> [Feature] Support ConvNeXt-V2.

- mmdet/core/bbox/assigners/__init__.py
- mmdet/core/bbox/assigners/ascend_assign_result.py
- mmdet/core/bbox/assigners/ascend_max_iou_assigner.py
- mmdet/models/dense_heads/__init__.py
- mmdet/models/dense_heads/ascend_anchor_head.py
- mmdet/models/dense_heads/ascend_retina_head.py
- mmdet/models/dense_heads/ascend_ssd_head.py
- mmdet/utils/__init__.py
- mmdet/utils/ascend_util.py
- tests/test_models/test_dense_heads/test_ascend_head.py
- tests/test_utils/test_assigner.py
Suitable for Ascend. Modify SSD and RetinaHead Model.
- The main modification points are as follows:
1. Create a new file `mmdet/models/dense_heads/ascend_anchor_head.py`. Create class AscendAnchorHead that inherits class AnchorHead.
2. Create a new file `mmdet/models/dense_heads/ascend_retina_head.py`. Create class AscendRetinaHead that inherits class RetinaHead and class AscendAnchorHead. 
3. Create a new file `mmdet/models/dense_heads/ascend_ssd_head.py`. Create class AscendSSDHead that inherits class SSDHead and class …
> Suitable for Ascend. Modify SSD and RetinaHead Model

- docs/en/1_exist_data_model.md
Fixed a small syntax error in the command.
> [Doc]: added missing `-` to `--format-only` option

- configs/_base_/models/ascend_retinanet_r50_fpn.py
- configs/_base_/models/ascend_ssd300.py
- configs/retinanet/ascend_retinanet_r18_fpn_1x8_1x_coco.py
- configs/ssd/ascend_ssd300_coco.py
- docs/en/device/npu.md
- docs/zh_cn/device/npu.md
> Ascend Acceleration Module doc and samples

- mmdet/models/detectors/base.py
The validation loss is currently not logged in the setting of both train and val workflow modes.
The problem is described in this issue:
https://github.com/open-mmlab/mmsegmentation/issues/1396
This PR replicates the changes made in this PR to the mmsegmentation library: https://github.com/open-mmlab/mmsegmentation/pull/1494
`val_step` is modified to add `_val` suffix to all validation losses, to distinguish those losses from those in the training step. This enables both training and validation loss logging.
> Fix validation loss logging

- mmdet/models/backbones/swin.py
In the original implementation, the `mlp_ratio` parameter in the `SwinTransformer`  can be float,  but the current mmdet's implementation does not support non-integer `mlp_ratio` (an Exception will be raised if a non-integer value is given).
I have found the same fix in mmsegmentation:
see, https://github.com/open-mmlab/mmsegmentation/pull/1274
When a float `mlp_ratio` is given, dims of mlp's out channels are truncated to an integer.
I think this does not break BC.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet …
> [Fix] Enable to set float mlp_ratio in SwinTransformer

- mmdet/models/backbones/csp_darknet.py
- mmdet/models/layers/se_layer.py
Pooling, mostly avg pooling and max pooling, in amp(float16) mode may overflow, because when every element in one channel sums up, it might be greater than the upper limit of float16, which is only 65536, then it overflows and starts from the lower limit. This is very common when the weights are not converged.
I trained coco with rtmdet from scratch in amp mode, I encounter nan loss issue. I thought this may be overflowing. And when I turn off amp mode, no more nan issue. So I confirmed this is pooling overflow issue, I know it …
> fix amp pooling overflow

- .pre-commit-config.yaml
Link https://github.com/open-mmlab/mmeval/pull/86.
> dev: Use official isort

- docs/en/notes/faq.md
- mmdet/__init__.py
According to #9692 and [#2444](https://github.com/open-mmlab/mmcv/pull/2444), tackling the _value error_ of optimizer requires the **minimum** version of **MMCV** to be **2.0.0rc4** for supporting dev-3.x branch.
> [Fix]: Change MMCV minimum version to 2.0.0rc4 for dev-3.x branch

- docs/en/user_guides/dataset_prepare.md
- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/dataset_prepare.md
- docs/zh_cn/user_guides/useful_tools.md
opendatalab下载链接增加一个后缀，方便平台定位访问来源
> [Doc] update opendatalab download link (add postfix)

- mmdet/models/layers/transformer/dino_layers.py
```python
rand_sign # [low, high), 1 or -1, randomly
```
https://github.com/open-mmlab/mmdetection/blob/78030a65608819080f6d9c5b1bfad95f0a36ac97/mmdet/models/layers/transformer/dino_layers.py#L410-L413
Current code is written as `neg: (-2, 1] U [1, 2)`, but it is actually `neg: (-2, -1] U [1, 2)`.
(Fig.3. of the original paper)
Fix `neg: (-2, 1] U [1, 2)` to `neg: (-2, -1] U [1, 2)`.
If so, please describe how it breaks the …
> [Fix] Fix docstring about noise in DINO

- docs/en/user_guides/inference.md
visualizer has been created in line 31 and 34, if you run this demo in one notebook, we need not **build** the visualizer again.
```
visualizer = VISUALIZERS.build(model.cfg.visualizer)
visualizer.dataset_meta = model.dataset_meta
```
If so, please describe how it breaks the …
> comment repeater visualizer register

- mmdet/evaluation/metrics/dump_det_results.py
- mmdet/evaluation/metrics/voc_metric.py
1. Fixed VOC metrics, add `eval_mode` in `eval_map`, or it will used `area` when calculating VOC2007, which is wrong.
> [Fix] Fix VOC metrics

- docs/en/user_guides/finetune.md
- docs/en/user_guides/inference.md
- docs/zh_cn/user_guides/finetune.md
- docs/zh_cn/user_guides/inference.md
Update user guide based on English version.
**Update**
Two user guides were updated based on English version
- docs/zh_cn/user_guides/finetune.md
- docs/zh_cn/user_guides/inference.md
**Fixed**
Fixed a misspelling in inference.md
- docs/en/user_guides/finetune.md
If this PR …
> [Doc]: update user guide: "finetune.md, inference.md"

- configs/rtmdet/README.md
> [Doc] Add RTMDet-Ins deployment guide.

- configs/fsaf/metafile.yml
- configs/paa/metafile.yml
- configs/yolact/metafile.yml
Unifying metafile.yml
1. Delete the brackets in `box_ap` to make the command, `mim search mmdet --dataset COCO --sort coco/box_ap --descending`, run successfully. Or it would raise an error, `TypeError: '>' not supported between instances of 'str' and 'int'`.
2. Add missing information on the training epochs in `paa/metafile.yml` and `yolact/metafile.yml`
> [Fix] Unifying metafile.yml

- tools/misc/browse_dataset.py
to fix an import error with python 3.10 below
```
from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
change the imported module following [this line](https://github.com/open-mmlab/mmdetection/blob/e9cae2d0787cd5c2fc6165a6061f92fa09e48fb1/mmdet/core/evaluation/recall.py#L2)  …
> [Fix] fix Sequence import error

- docs/en/1_exist_data_model.md
- docs/zh_cn/1_exist_data_model.md
To remove tools/test.py:116: UserWarning: --options is deprecated in favor of --eval-options warnings.warn('--options is deprecated in favor of --eval-options')
Replace options with eval-options in docs/zh_cn/1_exist_data_model.md and docs/en/1_exist_data_model.md 
If this PR …
> [Docs] Replace options with eval-options

- mmdet/datasets/samplers/infinite_sampler.py
The code raise error when i am running mmdet3d pgd network on MLU device:
Add utils function to get current device and pass it to `sync_random_seed` function.
1. Pre-commit …
> [Fix] fix only cuda device bug in datasets sampler

- docs/en/1_exist_data_model.md
- docs/zh_cn/1_exist_data_model.md
- mmdet/apis/test.py
- mmdet/core/visualization/image.py
- mmdet/models/detectors/base.py
- tools/test.py
Currently to visualize results, '--show-dir' plots both bounding boxes and instance masks if the network outputs them both. But bbox and masks can be compared independently in practice (e.g. in an academic paper). This PR provides two options `--box-only` and `--mask-only` for tools/test.py to control the output style.
In `tools/test.py`, options `--box-only` and `--mask-only` are added to argparser. And they are finally applied to `mmdet\core\visualization\image.py`.
```python
if bboxes is not None and not mask_only:
...
if segms is not None and not box_only:
...
```
Neithor `--show-mask-only` nor `--show-box-only`
```bash
python .\tools\test.py .\configs\mask2former\mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco.py .\ckpt\mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco_20220508_091649-4a943 …
```
> [Enhance] tools/test.py: add options `--show-box-only` and `--show-mask-only`

- mmdet/structures/mask/structures.py
- requirements/runtime.txt
The crop method of PolygonMasks is actually translating the coordinates, not actually clipping the polygon.
Fix this bug by applying geometrical intersection.
This solution refers to https://github.com/facebookresearch/fvcore/blob/main/fvcore/transforms/transform.py.
Fix the `crop` method of `PolygonMasks` with `shapely.geometry.intersection`.
The geometry intersection is a little bit slower than shifting coordinates after interpolating boundary. But interpolating will generate 1000x more points which will slow down other …
> [Fix] Fix cropping polygon mask.

- mmdet/core/evaluation/mean_ap.py
- mmdet/datasets/voc.py
To fix a print error when evaluating VOCDataset (#9878).
Assign `ds_name` by `self.CLASSES` directly without the condition on `year` attribute.
3. If the modification has potential influence on downstream projects, this PR should be tested …
> [Fix] Fix VOCDataset print wrong class names (#9878)

- mmdet/evaluation/metrics/coco_occluded_metric.py
There is no `self.data_root` in Metric. Hence, should delete related logic
> [Fix] delete `data_root` in `CocoOccludedSeparatedMetric` to fix bug

- mmdet/core/bbox/assigners/point_assigner.py
When training RepPoints, `points_range` will be on CPU and `lvl_idx` will be on GPU, while `points_range[lvl_idx]` is called.
points_range.to(gt_bboxes_lvl.device)
> Fixed potential device mismatch

- mmdet/models/task_modules/coders/bucketing_bbox_coder.py
- mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py
- mmdet/models/task_modules/coders/distance_point_bbox_coder.py
- mmdet/models/task_modules/coders/legacy_delta_xywh_bbox_coder.py
- mmdet/models/task_modules/coders/pseudo_bbox_coder.py
- mmdet/models/task_modules/coders/tblr_bbox_coder.py
- mmdet/models/task_modules/coders/yolo_bbox_coder.py
mmdet/models/task_modules/coders/bucketing_bbox_coder.py
mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py
mmdet/models/task_modules/coders/distance_point_bbox_coder.py
mmdet/models/task_modules/coders/legacy_delta_xywh_bbox_coder.py
mmdet/models/task_modules/coders/pseudo_bbox_coder.py
mmdet/models/task_modules/coders/tblr_bbox_coder.py
mmdet/models/task_modules/coders/yolo_bbox_coder.py
Does the modification introduce changes …
> Update type hints on part 10.

- mmdet/utils/benchmark.py
Fix the issue that `benchmark.py` cannot be used on Windows due to the inability to obtain Proportional Set Size on Windows.
The error occurs when running [tools/analysis_tools/benchmark.py](https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/tools/analysis_tools/benchmark.py) on Windows environment because memory_full_info.pss [**cannot** be obtained on Windows](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_info:~:text=terminated%20right%20now.-,pss,-(Linux)%3A%20aka).
https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/mmdet/utils/benchmark.py#L53-L61
Added a check for the existence of `memory_full_info.pss`, and if it does not exist, Proportional Set Size will not be obtained and displayed.
As far …
> [Fix] benchmark in windows.

- docs/en/migration/config_migration.md
Just a small edit, the version when comparing configs in the MIGRATE CONFIGURATION FILE FROM MMDETECTION 2.X TO 3.X were both `2.x` I just updated it.
Change `2.x Config` to `3.x Config` in `docs/en/migration/config_migration.md`
Not breaking
Not applicable 
> update version in config_migration.md

- mmdet/models/losses/__init__.py
- mmdet/models/losses/iou_loss.py
- tests/test_models/test_losses/test_loss.py
The paper [SIoU Loss: More Powerful Learning for Bounding Box Regression](https://arxiv.org/abs/2205.12740) proposes SIoU that calculates IoU, shape, and distance loss, and outperforms the commonly used GIOU and DIOU in object detection.
- Add implementation of SIoU Loss in `mmdet/models/losses/iou_loss.py`, modified from [YOLOv6](https://github.com/meituan/YOLOv6)
- Different from original realization `gamma=2-angle_cost`, setting `neg_gamma` parameter to use `gamma=angle_cost-2` seems to make training more stable.
In config: …
> [Feature] add SIoULoss implementation

- mmdet/core/utils/dist_utils.py
Currently, the input parameter  of the sync_random_seed function defaults to 'cuda'. When using this function, the device parameter is usually not specified, so an error will occur when the model runs on the NPU/CPU.
Modify the default input parameter to None, and when the parameter is None, set it to an available device.
We have verified the correctness on related configs such as faster_rcnn_r50_caffe_fpn_mstrain_90k_coco.py、faster_rcnn_r50_caffe_fpn_90k_coco.py.
> [Fix] sync_random_seed func adapts to different devices

- mmdet/models/losses/smooth_l1_loss.py
#4982 #10323 All similar problems are caused by `weight`. Should we take them to `weighted_loss` for processing.
> [fix] fix `pred` and `weight` dims unmatch in [Smooth]L1Loss

- mmdet/models/roi_heads/bbox_heads/multi_instance_bbox_head.py
Fixed `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)` when running CrowdDet model on cuda device (the model uses MultiInstanceBBoxHead roi_head)
Just added `tensor.to(device)` to fix the issue in `set_nms` method.
```
keep = keep.to(bboxes.device)
ruler = ruler.to(bboxes.device)
```
versions:
- torch==2.0.1
- mmdet==3.0.0
- mmengine==0.7.4
> Fix device of the tensors in set_nms

- configs/convnext/README.md
- configs/dsdl/README.md
- docs/en/get_started.md
- docs/en/migration/config_migration.md
- docs/en/notes/changelog.md
- docs/en/stat.py
- docs/en/user_guides/dataset_prepare.md
- docs/en/user_guides/init_cfg.md
- docs/en/user_guides/semi_det.md
- docs/en/user_guides/test.md
- docs/en/user_guides/train.md
- docs/en/user_guides/useful_tools.md
- mmdet/datasets/transforms/loading.py
- mmdet/datasets/transforms/transforms.py
- mmdet/datasets/utils.py
- mmdet/evaluation/metrics/crowdhuman_metric.py
- mmdet/models/data_preprocessors/data_preprocessor.py
- mmdet/models/data_preprocessors/track_data_preprocessor.py
- mmdet/models/dense_heads/base_dense_head.py
- mmdet/models/dense_heads/centernet_update_head.py
- mmdet/models/dense_heads/rtmdet_ins_head.py
- mmdet/models/dense_heads/yolof_head.py
- mmdet/models/detectors/glip.py
- mmdet/models/detectors/rtmdet.py
I am trying to `make latexpdf` the `en/` docs.
Fullwidth chars cause issues for `latexpdf` build targets, so I replaced them with their normal (half-width) variants.
- Added some missing `papertype` indicators in docs
- Replaced some unicode fullwidth chars with their halfwidth variants in docs and python code
You used to be able to download the docs as `pdf` until `v3.1.0`.
I don't know what broke this, but at least some of the work done in this branch should help narrow down probable causes of the pdf build breakage.
1. ✅ Pre-commit or other linting tools are used to fix the potential lint issues.
2. ✅ The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. ✅ If the modification has potential influence on downstream projects, …
> Fix: remove some unicode chars from `en/` docs

- configs/mask_rcnn/mask-rcnn_r50_fpn_1x-wandb_coco.py
Fix the typo to make mmengine find `WandbVisBackend` correctly.
`WandBVisBackend` --> `WandbVisBackend`
> [Fix] Fix typo in mask-rcnn_r50_fpn_1x-wandb_coco

- mmdet/evaluation/metrics/voc_metric.py
When using `recall` in VOCMetric, `compute_metrics()` return error like this:
```
Traceback (most recent call last):
File "tools/train.py", line 145, in <module>
main()
File "tools/train.py", line 141, in main
runner.train()
File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1721, in train
model = self.train_loop.run()  # type: ignore
File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 102, in run
self.runner.val_loop.run()
File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 366, in run
metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
_results = metric.evaluate(size)
File …
```
> [Fix] fix the input variables of eval_recalls in voc_metric

- docs/zh_cn/user_guides/tracking_train_test_zh_cn.md
translate  tracking_train_test_zh_cn.md
[CodeCamp2023-498] Translation into Chinese of an English document. (4)
translate tracking_train_test_zh_cn.md into chinese
1. …
> [CodeCamp2023-498] Translation into Chinese of `tracking_train_test_zh_cn.md`

- tools/analysis_tools/analyze_results.py
```
File "/usr/local/lib/python3.10/dist-packages/mmdet/.mim/tools/analysis_tools/analyze_results.py", line 398, in <module>
main()
File "/usr/local/lib/python3.10/dist-packages/mmdet/.mim/tools/analysis_tools/analyze_results.py", line 393, in main
result_visualizer.evaluate_and_show(
File "/usr/local/lib/python3.10/dist-packages/mmdet/.mim/tools/analysis_tools/analyze_results.py", line 200, in evaluate_and_show
self._save_image_gts_results(
File "/usr/local/lib/python3.10/dist-packages/mmdet/.mim/tools/analysis_tools/analyze_results.py", line 127, in _save_image_gts_results
gt_instances.bboxes = results[index]['gt_instances']['bboxes']
KeyError: 'gt_instances'
```
`results` doesn't have `gt_instances`.
https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760 …
> [Bugfix] analyze_results

- configs/dino/dino-5scale_swin-l_8xb2-12e_coco.py
- mmdet/configs/dino/dino_4scale_r50_8xb2_12e_coco.py
- mmdet/configs/dino/dino_4scale_r50_8xb2_24e_coco.py
- mmdet/configs/dino/dino_4scale_r50_8xb2_36e_coco.py
- mmdet/configs/dino/dino_4scale_r50_improved_8xb2_12e_coco.py
- mmdet/configs/dino/dino_5scale_swin_l_8xb2_12e_coco.py
- mmdet/configs/dino/dino_5scale_swin_l_8xb2_36e_coco.py
Add new configuration files for DINO algorithm in mmdetection.
new config file for DINO algorithm in mmdet dev-3.x.
4. The documentation has been modified accordingly, like docstring or …
> [CodeCamp2023-474] Add new configuration files for DINO algorithm in mmdetection. 

- .dev_scripts/gather_models.py
- mmdet/models/layers/normed_predictor.py
- tools/analysis_tools/get_flops.py
- tools/model_converters/publish_model.py
- tools/model_converters/upgrade_ssd_version.py
I notice that there's
1. inconsistency in version comparison since some file use `mmengine.utils.digit_version` while some just compare string
2. misuse of string comparison, for example: `'1.9.0' < '1.12'` and you get `False` with python
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
> [fix]fix torch version comparison

- mmdet/configs/deformable_detr/deformable_detr_r50_16xb2_50e_coco.py
- mmdet/configs/deformable_detr/deformable_detr_refine_r50_16xb2_50e_coco.py
- mmdet/configs/deformable_detr/deformable_detr_refine_twostage_r50_16xb2_50e_coco.py
Add new configs of deformable_detr
Order of inheritance: `deformable_detr_refine_twostage_r50_16xb2_50e_coco` -> `deformable_detr_refine_r50_16xb2_50e_coco` -> `deformable_detr_r50_16xb2_50e_coco`
So I only test the `deformable_detr_refine_twostage_r50_16xb2_50e_coco`.
> [CodeCamp2023-605] Add new configs of deformable_detr

- mmdet/models/detectors/deformable_detr.py
- projects/AlignDETR/README.md
- projects/AlignDETR/align_detr/__init__.py
- projects/AlignDETR/align_detr/align_detr_head.py
- projects/AlignDETR/align_detr/mixed_hungarian_assigner.py
- projects/AlignDETR/align_detr/utils.py
- projects/AlignDETR/configs/align_detr-4scale_r50_8xb2-12e_coco.py
- projects/AlignDETR/configs/align_detr-4scale_r50_8xb2-24e_coco.py
Support training and inference of the AlignDETR algorithm in mmdet, with reference to the open source code [AlignDETR](https://github.com/FelixCaae/AlignDETR).
Task: [OpenMMLabCamp#658](https://github.com/open-mmlab/OpenMMLabCamp/discussions/658)
1. Add files under `projects/AlignDETR`.
2. Update `mmdet/models/detectors/deformable_detr.py` to Fix bug: RuntimeError: shape '[2, 1, 1, 2]' is invalid for input of size 2.
```
mmdet/models/detectors/deformable_detr.py
projects/AlignDETR/README.md …
```
> Support AlignDETR 

- tools/analysis_tools/analyze_results.py
According to the implementation of `ConcatDataset` class from [mmengine](https://github.com/open-mmlab/mmengine/blob/daacb1878b5dc01023ff9390dca6c6744ad87e92/mmengine/dataset/dataset_wrapper.py#L41), the `datasets` variable is a list.
https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/tools/analysis_tools/analyze_results.py#L374
We should use `cfg.train_dataloader.dataset.datasets[0].pipeline`, instead of `cfg.train_dataloader.dataset.dataset.pipeline`.
* Add an if condition to check the …
> [Fix] Fix incorrect behavior to access train pipeline from `ConcatDataset` in analyze_results.py

- mmdet/models/detectors/grounding_dino.py
Grounding DINO tokenizes class names using GLIP code, and associates tokens with original class names. However, "max_num_entities" is capped at 256. 
https://github.com/open-mmlab/mmdetection/blob/fe3f809a0a514189baf889aa358c498d51ee36cd/mmdet/models/detectors/glip.py#L98-L100
This causes issues when Grounding DINO is run (fine-tune or zero-shot inference) with a large number of class names whose total number of tokens exceed this amount. In my use case, 100~ classes ended up yielding 280 tokens. This causes nans in the prediction scores, because later class names are not associated with any tokens.
Simply set the max_num_entities as `max_text_len` defined for Grounding DINO contrastive objective. This does not break original code, as `max_text_len` by default is 256.
Note that …
> Fix Grounding DINO nan when class tokens exceeds 256

- configs/odinw/README.md
- configs/odinw/grounding_dino_swin-b_pretrain_odinw13.py
- configs/odinw/grounding_dino_swin-b_pretrain_odinw35.py
- configs/odinw/grounding_dino_swin-t_pretrain_odinw13.py
- configs/odinw/grounding_dino_swin-t_pretrain_odinw35.py
- mmdet/models/detectors/grounding_dino.py
> Add GroundingDINO on ODinW results, and support caption prompt of GroundingDINO

- projects/CO-DETR/configs/codino/co_dino_5scale_swin_l_16xb1_16e_o365tococo.py
Training the CO-DETR model resulted in an error like https://github.com/open-mmlab/mmdetection/issues/11167
The URL in config is inaccessible, replace it with the URL in the README
> Fix CO-DETR load_from url in config

- mmdet/datasets/transforms/transforms.py
If the augmented image (mask) is for example rotated by 90 or 270 deg. using "RandomRotate90" and the original image (mask) is rectangular, it could end up with height and width inverted, therefore we need to use dimensions of the augmented mask (image) to convert.
Take the augmented mask shape instead of the original mask shape. 
None.
RandomRotate90
> Fixed mask shape after Albu postprocess

- projects/CO-DETR/configs/codino/co_dino_5scale_swin_l_lsj_16xb1_3x_coco.py
The motivation of this PR is to fix one of the config files for CO-DETR project. Currently, running
```shell
python tools/train.py D:\Projects\Cereal\mmdetection\projects\CO-DETR\configs\codino\co_dino_5scale_swin_l_
lsj_16xb1_3x_coco.py
```
throws a following exception:
```shell
AssertionError: Each parameter scheduler should contain the key type, but got {'milestones': [30]}
```
I assume that when modifying a particular item within a list, users are required to add a `type` key to distinguish it from other possible items in that particular list. 
This PR resolves the error by adding the type key that is inherited from some of the base configs: `co_dino_5scale_r50_lsj_8xb2_1x_coco.py`.
N/A
Anyone extending the modified config can now do so without running into this error.
1. Pre-commit …
> Fix one of the CO-DETR config files

- mmdet/datasets/api_wrappers/coco_api.py
- mmdet/datasets/coco_panoptic.py
- mmdet/evaluation/metrics/coco_panoptic_metric.py
The Mapillary Vistas Dataset validation split contains random strings as filenames, one of which has 'jpg' as part of the random filename. 
this results in a file not found error during validation when training with mapillary vistas dataset as a panoptic dataset
The Mapillary Vistas Dataset validation split contains random strings as filenames, one of which has 'jpg' as part of the random filename. 
this results in a file not found error during validation when training with mapillary vistas dataset as a panoptic dataset
replace …
> replace '.jpg' instead of 'jpg' to guarantee replacing file ending
